import { expect, test } from "bun:test";
import { runShellOracle } from "../driver/src/scripts/shell_oracle_test_runner.ts";

// W-111: Bun registers this parity oracle. Its existing shell assertions remain
// verbatim while every Garelier CLI under test is invoked directly with Bun.
const shellScript = [
  "#!/usr/bin/env bash",
  "#",
  "# runtime_recovery_hook.test.ts — pins the W-035 runtime recovery hook.",
  "set -uo pipefail",
  "",
  "SELF_DIR=\"$(cd \"$(dirname \"$0\")\" && pwd)\"",
  "HOOK=\"$SELF_DIR/runtime_recovery_hook.ts\"",
  "[ -f \"$HOOK\" ] || { echo \"runtime_recovery_hook.test: hook missing\" >&2; exit 1; }",
  "command -v bun >/dev/null 2>&1 || { echo \"runtime_recovery_hook.test: bun not on PATH\" >&2; exit 1; }",
  "",
  "TMP=\"$(mktemp -d)\"",
  "trap 'rm -rf \"$TMP\"' EXIT",
  "fail() { echo \"  FAIL: $*\" >&2; exit 1; }",
  "",
  "OUT=\"\" RC=0",
  "fire() {",
  "  set +e",
  "  OUT=\"$(printf '%s' \"$1\" | bun \"$HOOK\" 2>&1)\"",
  "  RC=$?",
  "  set -e",
  "}",
  "",
  "# W-188: hook state is contained under __garelier/<pm>/runtime/hooks/ (guardRuntimeDir),",
  "# never the consuming project's root .claude/. pm defaults to the sole pm 'pm'.",
  "incident_file() { printf '%s/__garelier/%s/runtime/hooks/incidents.jsonl' \"$1\" \"${2:-pm}\"; }",
  "state_file() { printf '%s/__garelier/%s/runtime/hooks/state.json' \"$1\" \"${2:-pm}\"; }",
  "# sole_pm: scaffold a single pm under __garelier so a cwd at the project root",
  "# resolves to that pm's runtime/hooks/ (guardRuntimeDir sole-pm branch).",
  "sole_pm() { mkdir -p \"$1/__garelier/${2:-pm}\"; }",
  "hook_cwd() {",
  "  if command -v cygpath >/dev/null 2>&1; then",
  "    cygpath -m \"$1\"",
  "  else",
  "    printf '%s' \"$1\"",
  "  fi",
  "}",
  "",
  "case_dir() { mkdir -p \"$TMP/$1\"; printf '%s/%s' \"$TMP\" \"$1\"; }",
  "",
  "# 1. PostToolUseFailure creates an incident and injects recovery context.",
  "D1=\"$(case_dir failure)\"",
  "sole_pm \"$D1\"",
  "C1=\"$(hook_cwd \"$D1\")\"",
  "fire '{\"hook_event_name\":\"PostToolUseFailure\",\"session_id\":\"s1\",\"cwd\":\"'\"$C1\"'\",\"agent_id\":\"a1\",\"agent_type\":\"worker\",\"tool_name\":\"Bash\",\"tool_input\":{\"command\":\"bun test\"},\"exit_code\":124,\"error_message\":\"Command timed out after 120000ms\"}'",
  "[ \"$RC\" -eq 0 ] || fail \"failure: expected exit 0, got $RC\"",
  "printf '%s' \"$OUT\" | grep -q 'GARELIER_RUNTIME_INCIDENT' || fail \"failure: missing recovery context: $OUT\"",
  "[ -f \"$(incident_file \"$D1\")\" ] || fail \"failure: incidents.jsonl not written\"",
  "grep -q '\"kind\":\"bash_command_timeout\"' \"$(incident_file \"$D1\")\" || fail \"failure: timeout kind not recorded\"",
  "grep -q '\"exit_code\":124' \"$(incident_file \"$D1\")\" || fail \"failure: exit_code not recorded\"",
  "grep -q '\"error_message\":\"Command timed out after 120000ms\"' \"$(incident_file \"$D1\")\" || fail \"failure: error_message not recorded\"",
  "grep -q '\"a1\"' \"$(state_file \"$D1\")\" || fail \"failure: state missing agent_id key\"",
  "",
  "# 2. PostToolUse output spill is detected but framed as not a command failure.",
  "D2=\"$(case_dir spill)\"",
  "sole_pm \"$D2\"",
  "C2=\"$(hook_cwd \"$D2\")\"",
  "fire '{\"hook_event_name\":\"PostToolUse\",\"session_id\":\"s2\",\"cwd\":\"'\"$C2\"'\",\"agent_id\":\"a2\",\"agent_type\":\"worker\",\"tool_name\":\"Bash\",\"tool_input\":{\"command\":\"cargo test\"},\"tool_response\":{\"text\":\"Output was truncated because it exceeded maximum output; full log saved to /tmp/build.log\"}}'",
  "[ \"$RC\" -eq 0 ] || fail \"spill: expected exit 0, got $RC\"",
  "printf '%s' \"$OUT\" | grep -q 'not a command failure' || fail \"spill: missing non-failure context: $OUT\"",
  "grep -q '\"kind\":\"bash_output_spilled\"' \"$(incident_file \"$D2\")\" || fail \"spill: incident not recorded\"",
  "",
  "# 3. SubagentStop blocks first and second time for an open incident without ok marker.",
  "D3=\"$(case_dir stop)\"",
  "sole_pm \"$D3\"",
  "C3=\"$(hook_cwd \"$D3\")\"",
  "fire '{\"hook_event_name\":\"PostToolUseFailure\",\"session_id\":\"s3\",\"cwd\":\"'\"$C3\"'\",\"agent_id\":\"a3\",\"agent_type\":\"worker\",\"tool_name\":\"PowerShell\",\"tool_input\":{\"command\":\"bun test\"},\"exit_code\":1,\"error_message\":\"failed\"}'",
  "fire '{\"hook_event_name\":\"SubagentStop\",\"session_id\":\"s3\",\"cwd\":\"'\"$C3\"'\",\"agent_id\":\"a3\",\"agent_type\":\"worker\",\"last_assistant_message\":\"done but no marker\"}'",
  "printf '%s' \"$OUT\" | grep -q '\"decision\":\"block\"' || fail \"stop #1: expected block: $OUT\"",
  "printf '%s' \"$OUT\" | grep -q 'GARELIER_RUNTIME_STATUS' || fail \"stop #1: missing marker instruction\"",
  "fire '{\"hook_event_name\":\"SubagentStop\",\"session_id\":\"s3\",\"cwd\":\"'\"$C3\"'\",\"agent_id\":\"a3\",\"agent_type\":\"worker\",\"last_assistant_message\":\"still no marker\"}'",
  "printf '%s' \"$OUT\" | grep -q '\"decision\":\"block\"' || fail \"stop #2: expected block: $OUT\"",
  "",
  "# 4. Third SubagentStop escalates to PM instead of blocking again.",
  "fire '{\"hook_event_name\":\"SubagentStop\",\"session_id\":\"s3\",\"cwd\":\"'\"$C3\"'\",\"agent_id\":\"a3\",\"agent_type\":\"worker\",\"last_assistant_message\":\"still no marker\"}'",
  "printf '%s' \"$OUT\" | grep -q 'GARELIER_PM_ESCALATION' || fail \"stop #3: missing PM escalation: $OUT\"",
  "printf '%s' \"$OUT\" | grep -vq '\"decision\":\"block\"' || fail \"stop #3: must not block: $OUT\"",
  "",
  "# 5. ok marker clears the open incident and passes silently.",
  "D5=\"$(case_dir okmarker)\"",
  "sole_pm \"$D5\"",
  "C5=\"$(hook_cwd \"$D5\")\"",
  "fire '{\"hook_event_name\":\"PostToolUseFailure\",\"session_id\":\"s5\",\"cwd\":\"'\"$C5\"'\",\"agent_id\":\"a5\",\"agent_type\":\"worker\",\"tool_name\":\"Bash\",\"tool_input\":{\"command\":\"cargo check\"},\"exit_code\":1,\"error_message\":\"failed\"}'",
  "fire '{\"hook_event_name\":\"SubagentStop\",\"session_id\":\"s5\",\"cwd\":\"'\"$C5\"'\",\"agent_id\":\"a5\",\"agent_type\":\"worker\",\"last_assistant_message\":\"recovered\\nGARELIER_RUNTIME_STATUS: {\\\"runtime_ok\\\": true, \\\"incident_id\\\": \\\"x\\\"}\"}'",
  "[ -z \"$OUT\" ] || fail \"ok marker: expected silent pass, got: $OUT\"",
  "grep -q '\"open_by_agent_id\": {}' \"$(state_file \"$D5\")\" || fail \"ok marker: state not cleared\"",
  "",
  "# 6. Non-target event/tool exits silently.",
  "D6=\"$(case_dir silent)\"",
  "sole_pm \"$D6\"",
  "C6=\"$(hook_cwd \"$D6\")\"",
  "fire '{\"hook_event_name\":\"PostToolUseFailure\",\"session_id\":\"s6\",\"cwd\":\"'\"$C6\"'\",\"agent_id\":\"a6\",\"tool_name\":\"Write\",\"tool_input\":{\"file_path\":\"x\"},\"exit_code\":1,\"error_message\":\"failed\"}'",
  "[ \"$RC\" -eq 0 ] || fail \"silent: expected exit 0\"",
  "[ -z \"$OUT\" ] || fail \"silent: expected no output, got: $OUT\"",
  "[ ! -e \"$(incident_file \"$D6\")\" ] || fail \"silent: should not write incident\"",
  "",
  "# 7. Broken state is swallowed/reset, not fatal.",
  "D7=\"$(case_dir broken)\"",
  "sole_pm \"$D7\"",
  "mkdir -p \"$D7/__garelier/pm/runtime/hooks\"",
  "printf '{ broken json' > \"$(state_file \"$D7\")\"",
  "C7=\"$(hook_cwd \"$D7\")\"",
  "fire '{\"hook_event_name\":\"PostToolUseFailure\",\"session_id\":\"s7\",\"cwd\":\"'\"$C7\"'\",\"agent_id\":\"a7\",\"agent_type\":\"worker\",\"tool_name\":\"Bash\",\"tool_input\":{\"command\":\"make test\"},\"exit_code\":1,\"error_message\":\"failed\"}'",
  "[ \"$RC\" -eq 0 ] || fail \"broken: expected exit 0\"",
  "printf '%s' \"$OUT\" | grep -q 'GARELIER_RUNTIME_INCIDENT' || fail \"broken: missing context\"",
  "grep -q '\"a7\"' \"$(state_file \"$D7\")\" || fail \"broken: state was not reset/recreated\"",
  "",
  "# 8. SubagentStop with no open incident still blocks when the",
  "#    GARELIER_RUNTIME_STATUS marker is missing (W-038), then escalates on the 3rd call.",
  "D8=\"$(case_dir marker_missing)\"",
  "sole_pm \"$D8\"",
  "C8=\"$(hook_cwd \"$D8\")\"",
  "fire '{\"hook_event_name\":\"SubagentStop\",\"session_id\":\"s8\",\"cwd\":\"'\"$C8\"'\",\"agent_id\":\"a8\",\"agent_type\":\"worker\",\"last_assistant_message\":\"all done, no status line\"}'",
  "printf '%s' \"$OUT\" | grep -q '\"decision\":\"block\"' || fail \"marker missing #1: expected block: $OUT\"",
  "printf '%s' \"$OUT\" | grep -q 'GARELIER_RUNTIME_STATUS' || fail \"marker missing #1: missing marker instruction\"",
  "fire '{\"hook_event_name\":\"SubagentStop\",\"session_id\":\"s8\",\"cwd\":\"'\"$C8\"'\",\"agent_id\":\"a8\",\"agent_type\":\"worker\",\"last_assistant_message\":\"still no status line\"}'",
  "printf '%s' \"$OUT\" | grep -q '\"decision\":\"block\"' || fail \"marker missing #2: expected block: $OUT\"",
  "fire '{\"hook_event_name\":\"SubagentStop\",\"session_id\":\"s8\",\"cwd\":\"'\"$C8\"'\",\"agent_id\":\"a8\",\"agent_type\":\"worker\",\"last_assistant_message\":\"still no status line\"}'",
  "printf '%s' \"$OUT\" | grep -q 'GARELIER_PM_ESCALATION' || fail \"marker missing #3: missing PM escalation: $OUT\"",
  "printf '%s' \"$OUT\" | grep -vq '\"decision\":\"block\"' || fail \"marker missing #3: must not block: $OUT\"",
  "",
  "# 9. SubagentStop with no open incident and a present marker passes silently,",
  "#    regardless of the runtime_ok boolean value (presence-only check).",
  "D9=\"$(case_dir marker_present)\"",
  "sole_pm \"$D9\"",
  "C9=\"$(hook_cwd \"$D9\")\"",
  "fire '{\"hook_event_name\":\"SubagentStop\",\"session_id\":\"s9\",\"cwd\":\"'\"$C9\"'\",\"agent_id\":\"a9\",\"agent_type\":\"worker\",\"last_assistant_message\":\"finished\\nGARELIER_RUNTIME_STATUS: {\\\"runtime_ok\\\": false}\"}'",
  "[ -z \"$OUT\" ] || fail \"marker present: expected silent pass, got: $OUT\"",
  "[ ! -e \"$(state_file \"$D9\")\" ] || fail \"marker present: should not create a state entry\"",
  "",
  "# 10. W-047: a cwd nested under __garelier/<pm_id>/... redirects the incident",
  "#     write to the already-gitignored __garelier/<pm_id>/runtime/hooks/ tree",
  "#     instead of dropping an untracked .claude/runtime/garelier/ under the",
  "#     dispatch checkout itself.",
  "D10=\"$(case_dir proj10)\"",
  "DISPATCH_CWD=\"$D10/__garelier/acme/_dispatch7/checkout\"",
  "mkdir -p \"$D10/__garelier/acme\" \"$DISPATCH_CWD\"",
  "C10=\"$(hook_cwd \"$DISPATCH_CWD\")\"",
  "fire '{\"hook_event_name\":\"PostToolUseFailure\",\"session_id\":\"s10\",\"cwd\":\"'\"$C10\"'\",\"agent_id\":\"a10\",\"agent_type\":\"worker\",\"tool_name\":\"Bash\",\"tool_input\":{\"command\":\"bun test\"},\"exit_code\":1,\"error_message\":\"failed\"}'",
  "[ \"$RC\" -eq 0 ] || fail \"redirect: expected exit 0, got $RC\"",
  "[ -f \"$D10/__garelier/acme/runtime/hooks/incidents.jsonl\" ] || fail \"redirect: incidents.jsonl not written under __garelier/<pm_id>/runtime/hooks/\"",
  "[ ! -e \"$DISPATCH_CWD/.claude/runtime/garelier/incidents.jsonl\" ] || fail \"redirect: legacy .claude/runtime/garelier/ still written under the dispatch checkout\"",
  "printf '%s' \"$OUT\" | grep -q \"hooks\" || fail \"redirect: recovery context does not mention the redirected runtime/hooks dir: $OUT\"",
  "printf '%s' \"$OUT\" | grep -q \"incidents.jsonl\" || fail \"redirect: recovery context does not point at incidents.jsonl: $OUT\"",
  "",
  "# ── W-063: compaction / resume stall sweep ────────────────────────────────────",
  "# Helper: scaffold a project with an in-flight dispatch container.",
  "snap_file() { printf '%s/__garelier/%s/runtime/hooks/compact_snapshot.json' \"$1\" \"${2:-pm}\"; }",
  "write_state() { # <container-dir> <id> <role> <slug> <status> <branch>",
  "  mkdir -p \"$1\"",
  "  printf '# Dispatch #%s - %s %s\\n\\n## Status\\n\\n%s\\n\\n## Current task\\n\\n#%s %s (%s)\\n' \\",
  "    \"$2\" \"$3\" \"$4\" \"$5\" \"$2\" \"$4\" \"$6\" > \"$1/STATE.md\"",
  "}",
  "",
  "# 11. SessionStart(compact) with an in-flight lane injects the sweep context",
  "#     naming the lane, its status, and the restart instruction.",
  "D11=\"$(case_dir ss_inflight)\"",
  "write_state \"$D11/__garelier/acme/_dispatch7\" 7 worker login WORKING \"garelier/main/acme/workbench/#7/login\"",
  "C11=\"$(hook_cwd \"$D11\")\"",
  "fire '{\"hook_event_name\":\"SessionStart\",\"session_id\":\"s11\",\"cwd\":\"'\"$C11\"'\",\"source\":\"compact\"}'",
  "[ \"$RC\" -eq 0 ] || fail \"ss inflight: expected exit 0, got $RC\"",
  "printf '%s' \"$OUT\" | grep -q 'GARELIER_COMPACTION_SWEEP' || fail \"ss inflight: missing sweep marker: $OUT\"",
  "printf '%s' \"$OUT\" | grep -q 'acme/_dispatch7' || fail \"ss inflight: lane not listed: $OUT\"",
  "printf '%s' \"$OUT\" | grep -q 'WORKING' || fail \"ss inflight: status not listed: $OUT\"",
  "printf '%s' \"$OUT\" | grep -q 'RESTART the producer' || fail \"ss inflight: missing restart instruction: $OUT\"",
  "printf '%s' \"$OUT\" | grep -q '\"hookEventName\":\"SessionStart\"' || fail \"ss inflight: not SessionStart additionalContext form: $OUT\"",
  "printf '%s' \"$OUT\" | grep -q 'fleet_watch stall net is NOT running for: acme' || fail \"ss inflight: missing fleet_watch note: $OUT\"",
  "",
  "# 12. SessionStart with no in-flight lane (only a terminal-status container)",
  "#     stays silent — zero noise.",
  "D12=\"$(case_dir ss_terminal)\"",
  "write_state \"$D12/__garelier/acme/_dispatch3\" 3 worker done DONE \"garelier/main/acme/workbench/#3/done\"",
  "C12=\"$(hook_cwd \"$D12\")\"",
  "fire '{\"hook_event_name\":\"SessionStart\",\"session_id\":\"s12\",\"cwd\":\"'\"$C12\"'\",\"source\":\"compact\"}'",
  "[ \"$RC\" -eq 0 ] || fail \"ss terminal: expected exit 0\"",
  "[ -z \"$OUT\" ] || fail \"ss terminal: expected silent pass (terminal lane), got: $OUT\"",
  "",
  "# 13. SessionStart source=startup never sweeps (matcher + source double-defence),",
  "#     even with a live in-flight lane present.",
  "D13=\"$(case_dir ss_startup)\"",
  "write_state \"$D13/__garelier/acme/_dispatch1\" 1 worker x WORKING \"garelier/main/acme/workbench/#1/x\"",
  "C13=\"$(hook_cwd \"$D13\")\"",
  "fire '{\"hook_event_name\":\"SessionStart\",\"session_id\":\"s13\",\"cwd\":\"'\"$C13\"'\",\"source\":\"startup\"}'",
  "[ \"$RC\" -eq 0 ] || fail \"ss startup: expected exit 0\"",
  "[ -z \"$OUT\" ] || fail \"ss startup: expected silent pass on startup source, got: $OUT\"",
  "",
  "# 14. PreCompact writes the in-flight snapshot and emits NO output (cannot inject",
  "#     context / must not block per official spec).",
  "D14=\"$(case_dir precompact)\"",
  "write_state \"$D14/__garelier/acme/_dispatch9\" 9 smith harden REPORTING \"garelier/main/acme/anvil/#9/harden\"",
  "C14=\"$(hook_cwd \"$D14\")\"",
  "fire '{\"hook_event_name\":\"PreCompact\",\"session_id\":\"s14\",\"cwd\":\"'\"$C14\"'\",\"trigger\":\"manual\"}'",
  "[ \"$RC\" -eq 0 ] || fail \"precompact: expected exit 0\"",
  "[ -z \"$OUT\" ] || fail \"precompact: expected no output, got: $OUT\"",
  "[ -f \"$(snap_file \"$D14\" acme)\" ] || fail \"precompact: compact_snapshot.json not written\"",
  "grep -q '\"acme/_dispatch9\"' \"$(snap_file \"$D14\" acme)\" || fail \"precompact: lane id not in snapshot\"",
  "grep -q '\"state\": \"REPORTING\"' \"$(snap_file \"$D14\" acme)\" || fail \"precompact: lane state not in snapshot\"",
  "grep -q '\"trigger\": \"manual\"' \"$(snap_file \"$D14\" acme)\" || fail \"precompact: trigger not recorded\"",
  "",
  "# 15. E2E: PreCompact snapshot then SessionStart(resume) annotates each lane with",
  "#     its pre-compaction status.",
  "D15=\"$(case_dir e2e)\"",
  "write_state \"$D15/__garelier/acme/_dispatch4\" 4 worker feat WORKING \"garelier/main/acme/workbench/#4/feat\"",
  "C15=\"$(hook_cwd \"$D15\")\"",
  "fire '{\"hook_event_name\":\"PreCompact\",\"session_id\":\"s15\",\"cwd\":\"'\"$C15\"'\",\"trigger\":\"auto\"}'",
  "[ -f \"$(snap_file \"$D15\" acme)\" ] || fail \"e2e: snapshot not written\"",
  "fire '{\"hook_event_name\":\"SessionStart\",\"session_id\":\"s15\",\"cwd\":\"'\"$C15\"'\",\"source\":\"resume\"}'",
  "printf '%s' \"$OUT\" | grep -q 'GARELIER_COMPACTION_SWEEP' || fail \"e2e: missing sweep marker: $OUT\"",
  "printf '%s' \"$OUT\" | grep -q 'resumed via resume' || fail \"e2e: source not echoed: $OUT\"",
  "printf '%s' \"$OUT\" | grep -q 'pre-compaction:' || fail \"e2e: snapshot annotation missing: $OUT\"",
  "",
  "# 16. A broken/garbage STATE.md is swallowed (fail-shut) — the sweep skips it and",
  "#     still lists the sibling healthy lane, exit 0.",
  "D16=\"$(case_dir ss_broken)\"",
  "mkdir -p \"$D16/__garelier/acme/_dispatch2\"",
  "printf '\\x00 not a valid state file' > \"$D16/__garelier/acme/_dispatch2/STATE.md\"",
  "write_state \"$D16/__garelier/acme/_dispatch5\" 5 worker ok WORKING \"garelier/main/acme/workbench/#5/ok\"",
  "C16=\"$(hook_cwd \"$D16\")\"",
  "fire '{\"hook_event_name\":\"SessionStart\",\"session_id\":\"s16\",\"cwd\":\"'\"$C16\"'\",\"source\":\"compact\"}'",
  "[ \"$RC\" -eq 0 ] || fail \"ss broken: expected exit 0, got $RC\"",
  "printf '%s' \"$OUT\" | grep -q 'acme/_dispatch5' || fail \"ss broken: healthy sibling lane not listed: $OUT\"",
  "",
  "# 17. fleet_watch.lock present -> no fleet_watch note for that PM.",
  "D17=\"$(case_dir ss_fleet)\"",
  "write_state \"$D17/__garelier/acme/_dispatch1\" 1 worker x WORKING \"garelier/main/acme/workbench/#1/x\"",
  "mkdir -p \"$D17/__garelier/acme/runtime/driver\"",
  "printf '{\"pid\":12345}\\n' > \"$D17/__garelier/acme/runtime/driver/fleet_watch.lock\"",
  "C17=\"$(hook_cwd \"$D17\")\"",
  "fire '{\"hook_event_name\":\"SessionStart\",\"session_id\":\"s17\",\"cwd\":\"'\"$C17\"'\",\"source\":\"compact\"}'",
  "printf '%s' \"$OUT\" | grep -q 'GARELIER_COMPACTION_SWEEP' || fail \"ss fleet: missing sweep marker: $OUT\"",
  "printf '%s' \"$OUT\" | grep -vq 'fleet_watch stall net is NOT running' || fail \"ss fleet: fleet note present despite live lock: $OUT\"",
  "",
  "# 18. W-188 containment pin: a hook firing in a git repo with NO __garelier",
  "#     ancestor writes NOTHING and creates NO .claude at the consuming project's",
  "#     root (Garelier is a guest — it never litters its host). The recovery",
  "#     machinery degrades statelessly; the incident CONTEXT is still emitted, and",
  "#     the hook exits 0. (Skipped if git is absent.)",
  "if command -v git >/dev/null 2>&1; then",
  "  D18=\"$(case_dir gitsub)\"",
  "  git -C \"$D18\" init -q >/dev/null 2>&1",
  "  mkdir -p \"$D18/core/engine\"",
  "  SUB18=\"$D18/core/engine\"",
  "  C18=\"$(hook_cwd \"$SUB18\")\"",
  "  fire '{\"hook_event_name\":\"PostToolUseFailure\",\"session_id\":\"s18\",\"cwd\":\"'\"$C18\"'\",\"agent_id\":\"a18\",\"agent_type\":\"worker\",\"tool_name\":\"Bash\",\"tool_input\":{\"command\":\"bun test\"},\"exit_code\":1,\"error_message\":\"failed\"}'",
  "  [ \"$RC\" -eq 0 ] || fail \"gitsub: expected exit 0, got $RC\"",
  "  printf '%s' \"$OUT\" | grep -q 'GARELIER_RUNTIME_INCIDENT' || fail \"gitsub: incident context should still be emitted (stateless degrade): $OUT\"",
  "  [ ! -e \"$D18/.claude\" ] || fail \"gitsub: created .claude at the git toplevel — must not litter the host root\"",
  "  [ ! -e \"$SUB18/.claude\" ] || fail \"gitsub: created a cwd-relative .claude under the subdir\"",
  "  [ ! -e \"$D18/__garelier\" ] || fail \"gitsub: fabricated a __garelier tree in a project that had none\"",
  "fi",
  "",
  "# 19. Defence-in-depth: the nested __garelier/.gitignore template keeps hook",
  "#     runtime OUT of git — the guard/recovery pm-less fallback (__atmos/guard/)",
  "#     and any mis-anchored .claude/runtime/ landing under __garelier/.",
  "TPL=\"$SELF_DIR/../templates/runtime_gitignore\"",
  "[ -f \"$TPL\" ] || fail \"template: runtime_gitignore not found at $TPL\"",
  "grep -q '\\*\\*/\\.claude/runtime/' \"$TPL\" || fail \"template: runtime_gitignore missing the **/.claude/runtime/ ignore entry\"",
  "grep -q '__atmos/guard/' \"$TPL\" || fail \"template: runtime_gitignore missing the __atmos/guard/ ignore entry (W-188 pm-less fallback)\"",
  "",
  "echo \"runtime_recovery_hook.test: OK (failure incident / spill / stop blocks / escalation / ok marker / silent / broken state / marker-missing block / marker-present pass / __garelier redirect / compaction sweep inflight / terminal-silent / startup-silent / precompact snapshot / e2e annotation / broken-state skip / fleet-lock note / no-garelier containment / ignore-template entry)\"",
].join("\n") + "\n";

test("runtime_recovery_hook shell parity oracle", () => {
  const result = runShellOracle(shellScript, import.meta.path);
  const stdout = result.stdout?.toString() ?? "";
  const stderr = result.stderr?.toString() ?? "";
  expect(result.exitCode, stdout + stderr).toBe(0);
}, 240_000);
