import { expect, test } from "bun:test";
import { runShellOracle } from "../driver/src/scripts/shell_oracle_test_runner.ts";

// W-111: Bun registers this parity oracle. Its existing shell assertions remain
// verbatim while every Garelier CLI under test is invoked directly with Bun.
const shellScript = [
  "#!/usr/bin/env bash",
  "#",
  "# runtime_recovery_hook.test.ts — pins the W-035 runtime recovery hook.",
  "set -uo pipefail",
  "",
  "SELF_DIR=\"$(cd \"$(dirname \"$0\")\" && pwd)\"",
  "HOOK=\"$SELF_DIR/runtime_recovery_hook.ts\"",
  "[ -f \"$HOOK\" ] || { echo \"runtime_recovery_hook.test: hook missing\" >&2; exit 1; }",
  "command -v bun >/dev/null 2>&1 || { echo \"runtime_recovery_hook.test: bun not on PATH\" >&2; exit 1; }",
  "",
  "TMP=\"$(mktemp -d)\"",
  "trap 'rm -rf \"$TMP\"' EXIT",
  "fail() { echo \"  FAIL: $*\" >&2; exit 1; }",
  "",
  "OUT=\"\" RC=0",
  "fire() {",
  "  set +e",
  "  OUT=\"$(printf '%s' \"$1\" | bun \"$HOOK\" 2>&1)\"",
  "  RC=$?",
  "  set -e",
  "}",
  "",
  "# W-188: hook state is contained under __garelier/<pm>/runtime/hooks/ (guardRuntimeDir),",
  "# never the consuming project's root .claude/. pm defaults to the sole pm 'pm'.",
  "incident_file() { printf '%s/__garelier/%s/runtime/hooks/incidents.jsonl' \"$1\" \"${2:-pm}\"; }",
  "state_file() { printf '%s/__garelier/%s/runtime/hooks/state.json' \"$1\" \"${2:-pm}\"; }",
  "# sole_pm: scaffold a single pm under __garelier so a cwd at the project root",
  "# resolves to that pm's runtime/hooks/ (guardRuntimeDir sole-pm branch).",
  "sole_pm() { mkdir -p \"$1/__garelier/${2:-pm}\"; }",
  "hook_cwd() {",
  "  if command -v cygpath >/dev/null 2>&1; then",
  "    cygpath -m \"$1\"",
  "  else",
  "    printf '%s' \"$1\"",
  "  fi",
  "}",
  "",
  "case_dir() { mkdir -p \"$TMP/$1\"; printf '%s/%s' \"$TMP\" \"$1\"; }",
  "",
  "# 1. PostToolUseFailure on a RECOVERABLE class creates an incident and injects",
  "#    recovery context. The command is a control/dispatch mutation: W-330's rule",
  "#    for a failed one is to read canonical state before any replay, which is an",
  "#    action, which is what makes it a record (W-758 形 2).",
  "#",
  "#    THE EVENT IS IN THE SHAPE THE STREAM ACTUALLY CONTAINS: `exit_code` null and",
  "#    `error_message` \"\". Measured over both live stores (388 failure-kind records,",
  "#    2026-07-20 to 2026-09-11): tool_input non-empty 388/388, exit_code non-empty",
  "#    0/388, error_message non-empty 0/388. A fixture that hands the hook an error",
  "#    string proves only that a branch works on input the harness never sends.",
  "D1=\"$(case_dir failure)\"",
  "sole_pm \"$D1\"",
  "C1=\"$(hook_cwd \"$D1\")\"",
  "fire '{\"hook_event_name\":\"PostToolUseFailure\",\"session_id\":\"s1\",\"cwd\":\"'\"$C1\"'\",\"agent_id\":\"a1\",\"agent_type\":\"worker\",\"tool_name\":\"Bash\",\"tool_input\":{\"command\":\"bun skills/garelier-core/driver/src/scripts/merge_land.ts --submit\",\"description\":\"submit the merge\"},\"exit_code\":null,\"error_message\":\"\"}'",
  "[ \"$RC\" -eq 0 ] || fail \"failure: expected exit 0, got $RC\"",
  "printf '%s' \"$OUT\" | grep -q 'GARELIER_RUNTIME_INCIDENT' || fail \"failure: missing recovery context: $OUT\"",
  "[ -f \"$(incident_file \"$D1\")\" ] || fail \"failure: incidents.jsonl not written\"",
  "grep -q '\"kind\":\"bash_command_failed\"' \"$(incident_file \"$D1\")\" || fail \"failure: kind not recorded\"",
  "grep -q '\"recoverable_class\":\"control_transaction_failed\"' \"$(incident_file \"$D1\")\" || fail \"failure: recoverable class not recorded\"",
  "grep -q 'merge_land.ts --submit' \"$(incident_file \"$D1\")\" || fail \"failure: command not recorded\"",
  "grep -q '\"a1\"' \"$(state_file \"$D1\")\" || fail \"failure: state missing agent_id key\"",
  "# W-758 形 1: the message names the command that CLOSES the record. Before this",
  "# existed the hook asked every agent to 'recover' with no operation behind the",
  "# word, so a record stayed open however well it was handled (163 open records,",
  "# oldest 2026-08-17).",
  "printf '%s' \"$OUT\" | grep -q 'garelier incident resolve' || fail \"failure: recovery context names no resolve command: $OUT\"",
  "",
  "# 2. PostToolUse output spill is reported to the agent and NOT recorded: a",
  "#    truncated output is a fact about the transport, not a fault to recover",
  "#    from, and recording one put a PM-readable record in the stream for every",
  "#    large command output (W-758 形 2).",
  "D2=\"$(case_dir spill)\"",
  "sole_pm \"$D2\"",
  "C2=\"$(hook_cwd \"$D2\")\"",
  "fire '{\"hook_event_name\":\"PostToolUse\",\"session_id\":\"s2\",\"cwd\":\"'\"$C2\"'\",\"agent_id\":\"a2\",\"agent_type\":\"worker\",\"tool_name\":\"Bash\",\"tool_input\":{\"command\":\"cargo test\"},\"tool_response\":{\"text\":\"Output was truncated because it exceeded maximum output; full log saved to /tmp/build.log\"}}'",
  "[ \"$RC\" -eq 0 ] || fail \"spill: expected exit 0, got $RC\"",
  "printf '%s' \"$OUT\" | grep -q 'not a command failure' || fail \"spill: missing non-failure context: $OUT\"",
  "[ ! -e \"$(incident_file \"$D2\")\" ] || fail \"spill: truncated output must not be recorded as an incident\"",
  "",
  "# 3. SubagentStop blocks first and second time for an open incident without ok marker.",
  "D3=\"$(case_dir stop)\"",
  "sole_pm \"$D3\"",
  "C3=\"$(hook_cwd \"$D3\")\"",
  "fire '{\"hook_event_name\":\"PostToolUseFailure\",\"session_id\":\"s3\",\"cwd\":\"'\"$C3\"'\",\"agent_id\":\"a3\",\"agent_type\":\"worker\",\"tool_name\":\"PowerShell\",\"tool_input\":{\"command\":\"garelier merge-request --dispatch-id 3\"},\"exit_code\":null,\"error_message\":\"\"}'",
  "fire '{\"hook_event_name\":\"SubagentStop\",\"session_id\":\"s3\",\"cwd\":\"'\"$C3\"'\",\"agent_id\":\"a3\",\"agent_type\":\"worker\",\"last_assistant_message\":\"done but no marker\"}'",
  "printf '%s' \"$OUT\" | grep -q '\"decision\":\"block\"' || fail \"stop #1: expected block: $OUT\"",
  "printf '%s' \"$OUT\" | grep -q 'GARELIER_RUNTIME_STATUS' || fail \"stop #1: missing marker instruction\"",
  "fire '{\"hook_event_name\":\"SubagentStop\",\"session_id\":\"s3\",\"cwd\":\"'\"$C3\"'\",\"agent_id\":\"a3\",\"agent_type\":\"worker\",\"last_assistant_message\":\"still no marker\"}'",
  "printf '%s' \"$OUT\" | grep -q '\"decision\":\"block\"' || fail \"stop #2: expected block: $OUT\"",
  "",
  "# 4. Third SubagentStop escalates to PM instead of blocking again.",
  "fire '{\"hook_event_name\":\"SubagentStop\",\"session_id\":\"s3\",\"cwd\":\"'\"$C3\"'\",\"agent_id\":\"a3\",\"agent_type\":\"worker\",\"last_assistant_message\":\"still no marker\"}'",
  "printf '%s' \"$OUT\" | grep -q 'GARELIER_PM_ESCALATION' || fail \"stop #3: missing PM escalation: $OUT\"",
  "printf '%s' \"$OUT\" | grep -vq '\"decision\":\"block\"' || fail \"stop #3: must not block: $OUT\"",
  "",
  "# 5. ok marker clears the open incident and passes silently.",
  "D5=\"$(case_dir okmarker)\"",
  "sole_pm \"$D5\"",
  "C5=\"$(hook_cwd \"$D5\")\"",
  "fire '{\"hook_event_name\":\"PostToolUseFailure\",\"session_id\":\"s5\",\"cwd\":\"'\"$C5\"'\",\"agent_id\":\"a5\",\"agent_type\":\"worker\",\"tool_name\":\"Bash\",\"tool_input\":{\"command\":\"garelier control claim W-1 --project .\"},\"exit_code\":null,\"error_message\":\"\"}'",
  "fire '{\"hook_event_name\":\"SubagentStop\",\"session_id\":\"s5\",\"cwd\":\"'\"$C5\"'\",\"agent_id\":\"a5\",\"agent_type\":\"worker\",\"last_assistant_message\":\"recovered\\nGARELIER_RUNTIME_STATUS: {\\\"runtime_ok\\\": true, \\\"incident_id\\\": \\\"x\\\"}\"}'",
  "[ -z \"$OUT\" ] || fail \"ok marker: expected silent pass, got: $OUT\"",
  "grep -q '\"open_by_agent_id\": {}' \"$(state_file \"$D5\")\" || fail \"ok marker: state not cleared\"",
  "",
  "# 6. Non-target event/tool exits silently.",
  "D6=\"$(case_dir silent)\"",
  "sole_pm \"$D6\"",
  "C6=\"$(hook_cwd \"$D6\")\"",
  "fire '{\"hook_event_name\":\"PostToolUseFailure\",\"session_id\":\"s6\",\"cwd\":\"'\"$C6\"'\",\"agent_id\":\"a6\",\"tool_name\":\"Write\",\"tool_input\":{\"file_path\":\"x\"},\"exit_code\":1,\"error_message\":\"failed\"}'",
  "[ \"$RC\" -eq 0 ] || fail \"silent: expected exit 0\"",
  "[ -z \"$OUT\" ] || fail \"silent: expected no output, got: $OUT\"",
  "[ ! -e \"$(incident_file \"$D6\")\" ] || fail \"silent: should not write incident\"",
  "",
  "# 7. Broken state is swallowed/reset, not fatal.",
  "D7=\"$(case_dir broken)\"",
  "sole_pm \"$D7\"",
  "mkdir -p \"$D7/__garelier/pm/runtime/hooks\"",
  "printf '{ broken json' > \"$(state_file \"$D7\")\"",
  "C7=\"$(hook_cwd \"$D7\")\"",
  "fire '{\"hook_event_name\":\"PostToolUseFailure\",\"session_id\":\"s7\",\"cwd\":\"'\"$C7\"'\",\"agent_id\":\"a7\",\"agent_type\":\"worker\",\"tool_name\":\"Bash\",\"tool_input\":{\"command\":\"garelier control transition W-1 --to active\"},\"exit_code\":null,\"error_message\":\"\"}'",
  "[ \"$RC\" -eq 0 ] || fail \"broken: expected exit 0\"",
  "printf '%s' \"$OUT\" | grep -q 'GARELIER_RUNTIME_INCIDENT' || fail \"broken: missing context\"",
  "grep -q '\"a7\"' \"$(state_file \"$D7\")\" || fail \"broken: state was not reset/recreated\"",
  "",
  "# 8. SubagentStop with no open incident still blocks when the",
  "#    GARELIER_RUNTIME_STATUS marker is missing (W-038), then escalates on the 3rd call.",
  "D8=\"$(case_dir marker_missing)\"",
  "sole_pm \"$D8\"",
  "C8=\"$(hook_cwd \"$D8\")\"",
  "fire '{\"hook_event_name\":\"SubagentStop\",\"session_id\":\"s8\",\"cwd\":\"'\"$C8\"'\",\"agent_id\":\"a8\",\"agent_type\":\"worker\",\"last_assistant_message\":\"all done, no status line\"}'",
  "printf '%s' \"$OUT\" | grep -q '\"decision\":\"block\"' || fail \"marker missing #1: expected block: $OUT\"",
  "printf '%s' \"$OUT\" | grep -q 'GARELIER_RUNTIME_STATUS' || fail \"marker missing #1: missing marker instruction\"",
  "fire '{\"hook_event_name\":\"SubagentStop\",\"session_id\":\"s8\",\"cwd\":\"'\"$C8\"'\",\"agent_id\":\"a8\",\"agent_type\":\"worker\",\"last_assistant_message\":\"still no status line\"}'",
  "printf '%s' \"$OUT\" | grep -q '\"decision\":\"block\"' || fail \"marker missing #2: expected block: $OUT\"",
  "fire '{\"hook_event_name\":\"SubagentStop\",\"session_id\":\"s8\",\"cwd\":\"'\"$C8\"'\",\"agent_id\":\"a8\",\"agent_type\":\"worker\",\"last_assistant_message\":\"still no status line\"}'",
  "printf '%s' \"$OUT\" | grep -q 'GARELIER_PM_ESCALATION' || fail \"marker missing #3: missing PM escalation: $OUT\"",
  "printf '%s' \"$OUT\" | grep -vq '\"decision\":\"block\"' || fail \"marker missing #3: must not block: $OUT\"",
  "",
  "# 9. SubagentStop with no open incident and a present marker passes silently,",
  "#    regardless of the runtime_ok boolean value (presence-only check).",
  "D9=\"$(case_dir marker_present)\"",
  "sole_pm \"$D9\"",
  "C9=\"$(hook_cwd \"$D9\")\"",
  "fire '{\"hook_event_name\":\"SubagentStop\",\"session_id\":\"s9\",\"cwd\":\"'\"$C9\"'\",\"agent_id\":\"a9\",\"agent_type\":\"worker\",\"last_assistant_message\":\"finished\\nGARELIER_RUNTIME_STATUS: {\\\"runtime_ok\\\": false}\"}'",
  "[ -z \"$OUT\" ] || fail \"marker present: expected silent pass, got: $OUT\"",
  "[ ! -e \"$(state_file \"$D9\")\" ] || fail \"marker present: should not create a state entry\"",
  "",
  "# 10. W-047: a cwd nested under __garelier/<pm_id>/... redirects the incident",
  "#     write to the already-gitignored __garelier/<pm_id>/runtime/hooks/ tree",
  "#     instead of dropping an untracked .claude/runtime/garelier/ under the",
  "#     dispatch checkout itself.",
  "D10=\"$(case_dir proj10)\"",
  "DISPATCH_CWD=\"$D10/__garelier/acme/_crew/dispatch7/checkout\"",
  "mkdir -p \"$D10/__garelier/acme\" \"$DISPATCH_CWD\"",
  "C10=\"$(hook_cwd \"$DISPATCH_CWD\")\"",
  "fire '{\"hook_event_name\":\"PostToolUseFailure\",\"session_id\":\"s10\",\"cwd\":\"'\"$C10\"'\",\"agent_id\":\"a10\",\"agent_type\":\"worker\",\"tool_name\":\"Bash\",\"tool_input\":{\"command\":\"bun skills/garelier-core/driver/src/scripts/dispatch_prepare.ts --recover-role\"},\"exit_code\":null,\"error_message\":\"\"}'",
  "[ \"$RC\" -eq 0 ] || fail \"redirect: expected exit 0, got $RC\"",
  "[ -f \"$D10/__garelier/acme/runtime/hooks/incidents.jsonl\" ] || fail \"redirect: incidents.jsonl not written under __garelier/<pm_id>/runtime/hooks/\"",
  "[ ! -e \"$DISPATCH_CWD/.claude/runtime/garelier/incidents.jsonl\" ] || fail \"redirect: legacy .claude/runtime/garelier/ still written under the dispatch checkout\"",
  "printf '%s' \"$OUT\" | grep -q \"hooks\" || fail \"redirect: recovery context does not mention the redirected runtime/hooks dir: $OUT\"",
  "printf '%s' \"$OUT\" | grep -q \"incidents.jsonl\" || fail \"redirect: recovery context does not point at incidents.jsonl: $OUT\"",
  "",
  "# ── W-063: compaction / resume stall sweep ────────────────────────────────────",
  "# Helper: scaffold a project with an in-flight dispatch container.",
  "snap_file() { printf '%s/__garelier/%s/runtime/hooks/compact_snapshot.json' \"$1\" \"${2:-pm}\"; }",
  "write_state() { # <container-dir> <id> <role> <slug> <status> <branch>",
  "  mkdir -p \"$1\"",
  "  printf '# Dispatch #%s - %s %s\\n\\n## Status\\n\\n%s\\n\\n## Current task\\n\\n#%s %s (%s)\\n' \\",
  "    \"$2\" \"$3\" \"$4\" \"$5\" \"$2\" \"$4\" \"$6\" > \"$1/STATE.md\"",
  "}",
  "",
  "# 11. SessionStart(compact) with an in-flight lane injects the sweep context",
  "#     naming the lane, its status, and the restart instruction.",
  "D11=\"$(case_dir ss_inflight)\"",
  "write_state \"$D11/__garelier/acme/_crew/dispatch7\" 7 worker login WORKING \"garelier/main/acme/workbench/#7/login\"",
  "C11=\"$(hook_cwd \"$D11\")\"",
  "fire '{\"hook_event_name\":\"SessionStart\",\"session_id\":\"s11\",\"cwd\":\"'\"$C11\"'\",\"source\":\"compact\"}'",
  "[ \"$RC\" -eq 0 ] || fail \"ss inflight: expected exit 0, got $RC\"",
  "printf '%s' \"$OUT\" | grep -q 'GARELIER_COMPACTION_SWEEP' || fail \"ss inflight: missing sweep marker: $OUT\"",
  "printf '%s' \"$OUT\" | grep -q 'acme/_crew/dispatch7' || fail \"ss inflight: lane not listed: $OUT\"",
  "printf '%s' \"$OUT\" | grep -q 'WORKING' || fail \"ss inflight: status not listed: $OUT\"",
  "printf '%s' \"$OUT\" | grep -q 'RESTART the role' || fail \"ss inflight: missing restart instruction: $OUT\"",
  "printf '%s' \"$OUT\" | grep -q '\"hookEventName\":\"SessionStart\"' || fail \"ss inflight: not SessionStart additionalContext form: $OUT\"",
  "printf '%s' \"$OUT\" | grep -q 'fleet_watch stall net is NOT running for: acme' || fail \"ss inflight: missing fleet_watch note: $OUT\"",
  "",
  "# 12. SessionStart with no in-flight lane (only a terminal-status container)",
  "#     stays silent — zero noise.",
  "D12=\"$(case_dir ss_terminal)\"",
  "write_state \"$D12/__garelier/acme/_crew/dispatch3\" 3 worker done DONE \"garelier/main/acme/workbench/#3/done\"",
  "C12=\"$(hook_cwd \"$D12\")\"",
  "fire '{\"hook_event_name\":\"SessionStart\",\"session_id\":\"s12\",\"cwd\":\"'\"$C12\"'\",\"source\":\"compact\"}'",
  "[ \"$RC\" -eq 0 ] || fail \"ss terminal: expected exit 0\"",
  "[ -z \"$OUT\" ] || fail \"ss terminal: expected silent pass (terminal lane), got: $OUT\"",
  "",
  "# 13. SessionStart source=startup never sweeps (matcher + source double-defence),",
  "#     even with a live in-flight lane present.",
  "D13=\"$(case_dir ss_startup)\"",
  "write_state \"$D13/__garelier/acme/_crew/dispatch1\" 1 worker x WORKING \"garelier/main/acme/workbench/#1/x\"",
  "C13=\"$(hook_cwd \"$D13\")\"",
  "fire '{\"hook_event_name\":\"SessionStart\",\"session_id\":\"s13\",\"cwd\":\"'\"$C13\"'\",\"source\":\"startup\"}'",
  "[ \"$RC\" -eq 0 ] || fail \"ss startup: expected exit 0\"",
  "[ -z \"$OUT\" ] || fail \"ss startup: expected silent pass on startup source, got: $OUT\"",
  "",
  "# 14. PreCompact writes the in-flight snapshot and emits NO output (cannot inject",
  "#     context / must not block per official spec).",
  "D14=\"$(case_dir precompact)\"",
  "write_state \"$D14/__garelier/acme/_crew/dispatch9\" 9 smith harden REPORTING \"garelier/main/acme/anvil/#9/harden\"",
  "C14=\"$(hook_cwd \"$D14\")\"",
  "fire '{\"hook_event_name\":\"PreCompact\",\"session_id\":\"s14\",\"cwd\":\"'\"$C14\"'\",\"trigger\":\"manual\"}'",
  "[ \"$RC\" -eq 0 ] || fail \"precompact: expected exit 0\"",
  "[ -z \"$OUT\" ] || fail \"precompact: expected no output, got: $OUT\"",
  "[ -f \"$(snap_file \"$D14\" acme)\" ] || fail \"precompact: compact_snapshot.json not written\"",
  "grep -q '\"acme/_crew/dispatch9\"' \"$(snap_file \"$D14\" acme)\" || fail \"precompact: lane id not in snapshot\"",
  "grep -q '\"state\": \"REPORTING\"' \"$(snap_file \"$D14\" acme)\" || fail \"precompact: lane state not in snapshot\"",
  "grep -q '\"trigger\": \"manual\"' \"$(snap_file \"$D14\" acme)\" || fail \"precompact: trigger not recorded\"",
  "",
  "# 15. E2E: PreCompact snapshot then SessionStart(resume) annotates each lane with",
  "#     its pre-compaction status.",
  "D15=\"$(case_dir e2e)\"",
  "write_state \"$D15/__garelier/acme/_crew/dispatch4\" 4 worker feat WORKING \"garelier/main/acme/workbench/#4/feat\"",
  "C15=\"$(hook_cwd \"$D15\")\"",
  "fire '{\"hook_event_name\":\"PreCompact\",\"session_id\":\"s15\",\"cwd\":\"'\"$C15\"'\",\"trigger\":\"auto\"}'",
  "[ -f \"$(snap_file \"$D15\" acme)\" ] || fail \"e2e: snapshot not written\"",
  "fire '{\"hook_event_name\":\"SessionStart\",\"session_id\":\"s15\",\"cwd\":\"'\"$C15\"'\",\"source\":\"resume\"}'",
  "printf '%s' \"$OUT\" | grep -q 'GARELIER_COMPACTION_SWEEP' || fail \"e2e: missing sweep marker: $OUT\"",
  "printf '%s' \"$OUT\" | grep -q 'resumed via resume' || fail \"e2e: source not echoed: $OUT\"",
  "printf '%s' \"$OUT\" | grep -q 'pre-compaction:' || fail \"e2e: snapshot annotation missing: $OUT\"",
  "",
  "# 16. A broken/garbage STATE.md is swallowed (fail-shut) — the sweep skips it and",
  "#     still lists the sibling healthy lane, exit 0.",
  "D16=\"$(case_dir ss_broken)\"",
  "mkdir -p \"$D16/__garelier/acme/_crew/dispatch2\"",
  "printf '\\x00 not a valid state file' > \"$D16/__garelier/acme/_crew/dispatch2/STATE.md\"",
  "write_state \"$D16/__garelier/acme/_crew/dispatch5\" 5 worker ok WORKING \"garelier/main/acme/workbench/#5/ok\"",
  "C16=\"$(hook_cwd \"$D16\")\"",
  "fire '{\"hook_event_name\":\"SessionStart\",\"session_id\":\"s16\",\"cwd\":\"'\"$C16\"'\",\"source\":\"compact\"}'",
  "[ \"$RC\" -eq 0 ] || fail \"ss broken: expected exit 0, got $RC\"",
  "printf '%s' \"$OUT\" | grep -q 'acme/_crew/dispatch5' || fail \"ss broken: healthy sibling lane not listed: $OUT\"",
  "",
  "# 17. fleet_watch.lock present -> no fleet_watch note for that PM.",
  "D17=\"$(case_dir ss_fleet)\"",
  "write_state \"$D17/__garelier/acme/_crew/dispatch1\" 1 worker x WORKING \"garelier/main/acme/workbench/#1/x\"",
  "mkdir -p \"$D17/__garelier/acme/runtime/driver\"",
  "printf '{\"pid\":12345}\\n' > \"$D17/__garelier/acme/runtime/driver/fleet_watch.lock\"",
  "C17=\"$(hook_cwd \"$D17\")\"",
  "fire '{\"hook_event_name\":\"SessionStart\",\"session_id\":\"s17\",\"cwd\":\"'\"$C17\"'\",\"source\":\"compact\"}'",
  "printf '%s' \"$OUT\" | grep -q 'GARELIER_COMPACTION_SWEEP' || fail \"ss fleet: missing sweep marker: $OUT\"",
  "printf '%s' \"$OUT\" | grep -vq 'fleet_watch stall net is NOT running' || fail \"ss fleet: fleet note present despite live lock: $OUT\"",
  "",
  "# 18. W-188 containment pin: a hook firing in a git repo with NO __garelier",
  "#     ancestor writes NOTHING and creates NO .claude at the consuming project's",
  "#     root (Garelier is a guest — it never litters its host). The recovery",
  "#     machinery degrades statelessly; the incident CONTEXT is still emitted, and",
  "#     the hook exits 0. (Skipped if git is absent.)",
  "if command -v git >/dev/null 2>&1; then",
  "  D18=\"$(case_dir gitsub)\"",
  "  git -C \"$D18\" init -q >/dev/null 2>&1",
  "  mkdir -p \"$D18/core/engine\"",
  "  SUB18=\"$D18/core/engine\"",
  "  C18=\"$(hook_cwd \"$SUB18\")\"",
  "  fire '{\"hook_event_name\":\"PostToolUseFailure\",\"session_id\":\"s18\",\"cwd\":\"'\"$C18\"'\",\"agent_id\":\"a18\",\"agent_type\":\"worker\",\"tool_name\":\"Bash\",\"tool_input\":{\"command\":\"bun skills/garelier-core/driver/src/scripts/dispatch_cleanup.ts --id 7\"},\"exit_code\":null,\"error_message\":\"\"}'",
  "  [ \"$RC\" -eq 0 ] || fail \"gitsub: expected exit 0, got $RC\"",
  "  printf '%s' \"$OUT\" | grep -q 'GARELIER_RUNTIME_INCIDENT' || fail \"gitsub: incident context should still be emitted (stateless degrade): $OUT\"",
  "  [ ! -e \"$D18/.claude\" ] || fail \"gitsub: created .claude at the git toplevel — must not litter the host root\"",
  "  [ ! -e \"$SUB18/.claude\" ] || fail \"gitsub: created a cwd-relative .claude under the subdir\"",
  "  [ ! -e \"$D18/__garelier\" ] || fail \"gitsub: fabricated a __garelier tree in a project that had none\"",
  "fi",
  "",
  "# 19. Defence-in-depth: the nested __garelier/.gitignore template keeps hook",
  "#     runtime OUT of git — the guard/recovery pm-less fallback (__atmos/guard/)",
  "#     and any mis-anchored .claude/runtime/ landing under __garelier/.",
  "TPL=\"$SELF_DIR/../templates/runtime_gitignore\"",
  "[ -f \"$TPL\" ] || fail \"template: runtime_gitignore not found at $TPL\"",
  "grep -q '\\*\\*/\\.claude/runtime/' \"$TPL\" || fail \"template: runtime_gitignore missing the **/.claude/runtime/ ignore entry\"",
  "grep -q '__atmos/guard/' \"$TPL\" || fail \"template: runtime_gitignore missing the __atmos/guard/ ignore entry (W-188 pm-less fallback)\"",
  "",
  "# 20. W-434: Agent PreToolUse with no dispatch_prepare record warns before spawn,",
  "#     records the advisory for dock_status, and always exits 0 (never blocks).",
  "D20=\"$(case_dir attended_missing)\"",
  "sole_pm \"$D20\" acme",
  "C20=\"$(hook_cwd \"$D20\")\"",
  "fire '{\"hook_event_name\":\"PreToolUse\",\"session_id\":\"s20\",\"cwd\":\"'\"$C20\"'\",\"tool_name\":\"Agent\",\"tool_input\":{\"name\":\"ga-scout-missing-record\"}}'",
  "[ \"$RC\" -eq 0 ] || fail \"attended missing: expected warning-only exit 0, got $RC\"",
  "printf '%s' \"$OUT\" | grep -q 'dispatch_prepare.ts --attended-seat --role <role> --slug <slug> --worktree <path>' || fail \"attended missing: command absent: $OUT\"",
  "printf '%s' \"$OUT\" | grep -q 'profile_unknown' || fail \"attended missing: failure token absent: $OUT\"",
  "printf '%s' \"$OUT\" | grep -q 'no-output idle' || fail \"attended missing: idle failure absent: $OUT\"",
  "printf '%s' \"$OUT\" | grep -q 'Do not decide from a role enumeration' || fail \"attended missing: predicate warning absent: $OUT\"",
  "printf '%s' \"$OUT\" | grep -q '\"systemMessage\"' || fail \"attended missing: warning is not on the documented systemMessage channel: $OUT\"",
  "printf '%s' \"$OUT\" | grep -vq '\"hookSpecificOutput\"' || fail \"attended missing: PreToolUse must not rely on unproven additionalContext delivery: $OUT\"",
  "printf '%s' \"$OUT\" | grep -vq '\"decision\"' || fail \"attended missing: warning must not carry a block decision: $OUT\"",
  "grep -q '\"kind\":\"guard_missing_attended_record\"' \"$(incident_file \"$D20\" acme)\" || fail \"attended missing: dock_status guard incident absent\"",
  "grep -q '\"resolved_agent\":\"ga-scout-missing-record\"' \"$(incident_file \"$D20\" acme)\" || fail \"attended missing: incident agent absent\"",
  "",
  "# 21. W-434/F1: a canonical dispatch context suppresses the warning even",
  "#     though no same-name .meta file exists (command_guard resolver parity).",
  "D21=\"$(case_dir attended_present)\"",
  "sole_pm \"$D21\" acme",
  "mkdir -p \"$D21/__garelier/acme/_crew/dispatch98/checkout\"",
  "W21=\"$(hook_cwd \"$D21/__garelier/acme/_crew/dispatch98/checkout\")\"",
  "printf '%s\\n' '{\"guard\":{\"permission_profile\":\"role\",\"fence_roots\":[\"'\"$W21\"'\"],\"role\":\"worker\",\"agent_name\":\"ga-worker-w434-spawn-guard-hook\",\"worktree\":\"'\"$W21\"'\"}}' > \"$D21/__garelier/acme/_crew/dispatch98/context.json\"",
  "C21=\"$(hook_cwd \"$D21\")\"",
  "fire '{\"hook_event_name\":\"PreToolUse\",\"session_id\":\"s21\",\"cwd\":\"'\"$C21\"'\",\"tool_name\":\"Agent\",\"tool_input\":{\"name\":\"ga-worker-w434-spawn-guard-hook\"}}'",
  "[ \"$RC\" -eq 0 ] || fail \"attended present: expected exit 0, got $RC\"",
  "[ -z \"$OUT\" ] || fail \"attended present: expected silent pass, got: $OUT\"",
  "[ ! -e \"$(incident_file \"$D21\" acme)\" ] || fail \"attended present: should not write an incident\"",
  "",
  "# 22. W-758 AC-758-3, the NEGATIVE direction: a diagnostic exit is not an",
  "#     incident. These are the exact shapes the row measured — a `sed` against a",
  "#     path that does not exist, and a `grep` that matched nothing — and they are",
  "#     fired in the shape the harness really sends (exit_code null, error_message",
  "#     \"\"), so the refutation measures the classifier rather than a field the",
  "#     event never carries. Both are the RESULT of an investigation; neither names",
  "#     anything to recover from, and recording them is what filled the stream (278",
  "#     coalesced occurrences of one class on 2026-09-11) and spent a turn per",
  "#     occurrence on an instruction that could not be followed.",
  "D22=\"$(case_dir diagnostic_noise)\"",
  "sole_pm \"$D22\"",
  "C22=\"$(hook_cwd \"$D22\")\"",
  "fire '{\"hook_event_name\":\"PostToolUseFailure\",\"session_id\":\"s22\",\"cwd\":\"'\"$C22\"'\",\"agent_id\":\"a22\",\"agent_type\":\"worker\",\"tool_name\":\"Bash\",\"tool_input\":{\"command\":\"sed -n 1,5p lane/result.md\",\"description\":\"read the register\"},\"exit_code\":null,\"error_message\":\"\"}'",
  "[ \"$RC\" -eq 0 ] || fail \"diagnostic sed: expected exit 0, got $RC\"",
  "[ -z \"$OUT\" ] || fail \"diagnostic sed: expected no recovery context, got: $OUT\"",
  "[ ! -e \"$(incident_file \"$D22\")\" ] || fail \"diagnostic sed: must not be recorded\"",
  "fire '{\"hook_event_name\":\"PostToolUseFailure\",\"session_id\":\"s22\",\"cwd\":\"'\"$C22\"'\",\"agent_id\":\"a22\",\"agent_type\":\"worker\",\"tool_name\":\"Bash\",\"tool_input\":{\"command\":\"grep -n TODO src/lib.ts\"},\"exit_code\":null,\"error_message\":\"\"}'",
  "[ ! -e \"$(incident_file \"$D22\")\" ] || fail \"diagnostic grep: a 0-hit grep must not be recorded\"",
  "# The same command text INSIDE a heredoc body is still not an invocation: only",
  "# the first line is classified (two of the four post-coalescing live records were",
  "# exactly this — a register being written, read as a failed control transaction).",
  "fire '{\"hook_event_name\":\"PostToolUseFailure\",\"session_id\":\"s22\",\"cwd\":\"'\"$C22\"'\",\"agent_id\":\"a22\",\"agent_type\":\"worker\",\"tool_name\":\"Bash\",\"tool_input\":{\"command\":\"cat > note.md <<EOF\\nrun gate_runner.ts --from-register\\nEOF\"},\"exit_code\":null,\"error_message\":\"\"}'",
  "[ ! -e \"$(incident_file \"$D22\")\" ] || fail \"diagnostic heredoc: a driver script named in a heredoc body must not be recorded\"",
  "[ ! -e \"$(state_file \"$D22\")\" ] || fail \"diagnostic noise: must not open recovery state (a stopping subagent was blocked by these)\"",
  "",
  "# 23. W-758 AC-758-3, the POSITIVE direction: a failure this hook CAN see is",
  "#     recorded, and `garelier incident resolve` closes it. The two halves are one",
  "#     case on purpose — a class that can be recorded but not closed is the state",
  "#     the row was opened about.",
  "#",
  "#     The class is the control/dispatch mutation, keyed on the command, because",
  "#     that is the only thing the real event carries. The guard-refusal half of",
  "#     AC-758-3 is proven where a guard refusal is actually observable — at the",
  "#     guard itself, in `command_guard.test.ts` (a real `maybeWriteGuardReport`",
  "#     record, then the same resolve) — rather than by handing this hook an",
  "#     `error_message` the harness has never once sent.",
  "D23=\"$(case_dir recoverable_resolve)\"",
  "sole_pm \"$D23\"",
  "C23=\"$(hook_cwd \"$D23\")\"",
  "fire '{\"hook_event_name\":\"PostToolUseFailure\",\"session_id\":\"s23\",\"cwd\":\"'\"$C23\"'\",\"agent_id\":\"a23\",\"agent_type\":\"worker\",\"tool_name\":\"Bash\",\"tool_input\":{\"command\":\"bun skills/garelier-core/driver/src/scripts/land_pipeline.ts --dispatch-id 23\"},\"exit_code\":null,\"error_message\":\"\"}'",
  "[ -f \"$(incident_file \"$D23\")\" ] || fail \"recoverable: control mutation failure not recorded\"",
  "grep -q '\"recoverable_class\":\"control_transaction_failed\"' \"$(incident_file \"$D23\")\" || fail \"recoverable: class not recorded\"",
  "ID23=\"$(sed -n 's/.*\"incident_id\":\"\\([^\"]*\\)\".*/\\1/p' \"$(incident_file \"$D23\")\" | head -1)\"",
  "[ -n \"$ID23\" ] || fail \"recoverable: could not read the incident id back\"",
  "RESOLVE_OUT=\"$(cd \"$D23\" && bun \"$SELF_DIR/../driver/src/guard/incident_log.ts\" resolve \"$ID23\" --reason 'transaction re-read; nothing half-applied' 2>&1)\" || fail \"resolve: exit non-zero: $RESOLVE_OUT\"",
  "printf '%s' \"$RESOLVE_OUT\" | grep -q '\"resolved\":1' || fail \"resolve: did not report one resolved record: $RESOLVE_OUT\"",
  "# A tally that outlives its closed record keeps counting, so its removal is",
  "# reported rather than swallowed: on the clean path the field is empty.",
  "printf '%s' \"$RESOLVE_OUT\" | grep -q '\"orphaned_tallies\":\\[\\]' || fail \"resolve: orphaned_tallies not surfaced: $RESOLVE_OUT\"",
  "grep -q \"$ID23\" \"$(incident_file \"$D23\")\" && fail \"resolve: record is still in the unresolved stream\"",
  "[ -f \"$D23/__garelier/pm/runtime/hooks/resolved/incidents.jsonl\" ] || fail \"resolve: resolved/ stream not written\"",
  "grep -q '\"status\":\"resolved\"' \"$D23/__garelier/pm/runtime/hooks/resolved/incidents.jsonl\" || fail \"resolve: status not rewritten\"",
  "grep -q 'transaction re-read; nothing half-applied' \"$D23/__garelier/pm/runtime/hooks/resolved/incidents.jsonl\" || fail \"resolve: reason not carried\"",
  "# The rewrite is atomic: the temp file it renames from is never left behind.",
  "[ -z \"$(ls \"$D23/__garelier/pm/runtime/hooks\"/*.tmp 2>/dev/null)\" ] || fail \"resolve: a temp stream file was left behind\"",
  "# A reason is not optional: a resolution with no reason is not one.",
  "(cd \"$D23\" && bun \"$SELF_DIR/../driver/src/guard/incident_log.ts\" resolve gri-nothing --reason '' >/dev/null 2>&1) && fail \"resolve: an empty --reason must be refused\"",
  "# An id that names nothing HERE is reported, never counted as closed.",
  "(cd \"$D23\" && bun \"$SELF_DIR/../driver/src/guard/incident_log.ts\" resolve gri-nothing --reason 'x' >/dev/null 2>&1) && fail \"resolve: an unmatched id must not exit 0\"",
  "",
  "echo \"runtime_recovery_hook.test: OK (failure incident / spill not recorded / stop blocks / escalation / ok marker / silent / broken state / marker-missing block / marker-present pass / __garelier redirect / compaction sweep inflight / terminal-silent / startup-silent / precompact snapshot / e2e annotation / broken-state skip / fleet-lock note / no-garelier containment / ignore-template entry / Agent missing-record warn / Agent recorded silent / diagnostic noise unrecorded / recoverable recorded+resolved)\"",
].join("\n") + "\n";

test("runtime_recovery_hook shell parity oracle", () => {
  const result = runShellOracle(shellScript, import.meta.path);
  const stdout = result.stdout?.toString() ?? "";
  const stderr = result.stderr?.toString() ?? "";
  expect(result.exitCode, stdout + stderr).toBe(0);
}, 240_000);
