import { expect, test } from "bun:test";
import { runShellOracle } from "../driver/src/scripts/shell_oracle_test_runner.ts";
import { readFileSync } from "node:fs";

// W-111: Bun registers this parity oracle. Its existing shell assertions remain
// verbatim while every Garelier CLI under test is invoked directly with Bun.
const shellScript = [
  "#!/usr/bin/env bash",
  "#",
  "# task_mirror_hook.test.ts — pins task_mirror_hook.sh, the framework-owned",
  "# PostToolUse Task-mirror delta hook (workshop W-030).",
  "#",
  "# Builds a throwaway __garelier control tree with a real backlog, feeds the hook",
  "# PostToolUse JSON on stdin (the exact shape Claude Code emits), and asserts the",
  "# four contract branches:",
  "#   a. OUT-OF-SCOPE  -> a command that is not a land/dispatch script: no output,",
  "#      exit 0, no state file (pure-bash reject, no subprocess).",
  "#   b. PARSE + BASELINE -> a land/dispatch command carrying --project/--pm-id:",
  "#      parsed correctly, first run is SILENT (records the baseline, no dump), and",
  "#      the state file appears at the derived runtime/driver path.",
  "#   c. NO-DELTA -> an identical second run prints nothing (zero tokens injected).",
  "#   d. DELTA -> a backlog row added between runs -> one compact `TASK-MIRROR diff:`",
  "#      line naming the new key.",
  "# Plus the 誤爆ゼロ guard: a matching script name but NO --pm-id/--project is",
  "# silent (never guesses).",
  "#",
  "# Self-contained: run directly (`bun test task_mirror_hook.test.ts`) or from ci.ts.",
  "# Needs `bun` (the hook runs task_mirror.ts + parses JSON with bun). Exits 0 only",
  "# if every branch holds.",
  "set -uo pipefail",
  "",
  "SELF_DIR=\"$(cd \"$(dirname \"$0\")\" && pwd)\"",
  "HOOK=\"$SELF_DIR/task_mirror_hook.sh\"",
  "[ -f \"$HOOK\" ] || { echo \"task_mirror_hook.test: cannot find task_mirror_hook.sh next to me\" >&2; exit 1; }",
  "command -v bun >/dev/null 2>&1 || { echo \"task_mirror_hook.test: 'bun' not on PATH — cannot run the mirror\" >&2; exit 1; }",
  "V3_FIXTURE=\"$(cygpath -m \"$SELF_DIR/../driver/src/control/fixtures/v3_control.ts\" 2>/dev/null || printf '%s' \"$SELF_DIR/../driver/src/control/fixtures/v3_control.ts\")\"",
  "",
  "# Git-Bash `/tmp` and native Bun's `/tmp` can name different Windows trees.",
  "# Keep the fixture beside this test in an ignored `*.tmp` scratch directory;",
  "# both runtimes then resolve the same physical worktree path on every platform.",
  "TMP_ROOT=\"$(mktemp -d --suffix=.tmp \"$SELF_DIR/task_mirror_hook.XXXXXX\")\"",
  "TMP=\"$TMP_ROOT/case\"",
  "mkdir -p \"$TMP\"",
  "trap 'rm -rf \"$TMP_ROOT\"' EXIT",
  "fail() { echo \"  FAIL: $*\" >&2; exit 1; }",
  "",
  "PM=\"demo\"",
  "CONTROL=\"$TMP/__garelier/$PM/control\"",
  "STATE=\"$TMP/__garelier/$PM/runtime/driver/task_mirror_hook_state.json\"",
  "bun -e 'import { pathToFileURL } from \"node:url\"; const [root, pmId, fixturePath] = process.argv.slice(1); const { writeV3Fixture } = await import(pathToFileURL(fixturePath).href); writeV3Fixture(root, 2, pmId);' \"$TMP\" \"$PM\" \"$V3_FIXTURE\"",
  "",
  "# fire <command-string> -> sets OUT/RC by feeding PostToolUse JSON to the hook.",
  "fire() {",
  "  set +e",
  "  OUT=\"$(printf '{\"tool_input\":{\"command\":\"%s\"}}' \"$1\" | bash \"$HOOK\" 2>&1)\"",
  "  RC=$?",
  "  set -e",
  "}",
  "",
  "DISPATCH_CMD=\"bun dispatch_prepare.ts --project $TMP --pm-id $PM --role worker\"",
  "",
  "# a. OUT-OF-SCOPE: a plain command is rejected with no output and no state file.",
  "fire \"ls -la\"",
  "[ \"$RC\" -eq 0 ] || fail \"out-of-scope: expected exit 0, got $RC\"",
  "[ -z \"$OUT\" ]   || fail \"out-of-scope: expected no output, got: $OUT\"",
  "[ ! -f \"$STATE\" ] || fail \"out-of-scope: no state file should be written\"",
  "",
  "# 誤爆ゼロ: a matching script name but missing --pm-id/--project is silent.",
  "fire \"bun merge_land.ts --id 7\"",
  "[ \"$RC\" -eq 0 ] || fail \"no-flags: expected exit 0, got $RC\"",
  "[ -z \"$OUT\" ]   || fail \"no-flags: expected no output, got: $OUT\"",
  "[ ! -f \"$STATE\" ] || fail \"no-flags: no state file without parsed pm-id/project\"",
  "",
  "# b. PARSE + BASELINE: first real run is silent and records the baseline.",
  "fire \"$DISPATCH_CMD\"",
  "[ \"$RC\" -eq 0 ] || fail \"baseline: expected exit 0, got $RC\"",
  "[ -z \"$OUT\" ]   || fail \"baseline: first run must be silent (no dump), got: $OUT\"",
  "[ -f \"$STATE\" ] || fail \"baseline: state file not written at $STATE\"",
  "grep -q 'W-001' \"$STATE\" || fail \"baseline: state missing W-001 ($(cat \"$STATE\"))\"",
  "grep -q 'W-002' \"$STATE\" || fail \"baseline: state missing W-002 ($(cat \"$STATE\"))\"",
  "",
  "# c. NO-DELTA: an identical second run injects nothing.",
  "fire \"$DISPATCH_CMD\"",
  "[ \"$RC\" -eq 0 ] || fail \"no-delta: expected exit 0, got $RC\"",
  "[ -z \"$OUT\" ]   || fail \"no-delta: unchanged mirror must be silent, got: $OUT\"",
  "",
  "# d. DELTA: a new backlog row surfaces as one compact diff line naming the key.",
  "cat > \"$CONTROL/backlog/open/W-003-third-task.md\" <<'EOF'",
  "+++",
  "schema_version = 3",
  "kind = \"garelier_backlog\"",
  "id = \"W-003\"",
  "status = \"ready\"",
  "created = \"2026-07-22T10:00:00.000Z\"",
  "updated = \"2026-07-22T11:00:00.000Z\"",
  "status_changed = \"2026-07-22T11:00:00.000Z\"",
  "transition_reason = \"fixture delta\"",
  "+++",
  "# W-003: Third task",
  "",
  "## Acceptance criteria",
  "",
  "- [ ] Surface the new task.",
  "",
  "## Current position",
  "",
  "Active.",
  "",
  "## Exact next action",
  "",
  "Mirror W-003.",
  "",
  "## Evidence",
  "",
  "- None recorded.",
  "EOF",
  "bun -e 'import { readFileSync, writeFileSync } from \"node:fs\"; const path = process.argv[1]; const source = readFileSync(path, \"utf8\"); const next = source.replace(`backlog = [\"W-001\", \"W-002\"]`, `backlog = [\"W-001\", \"W-002\", \"W-003\"]`); if (next === source) throw new Error(\"fixture checkpoint membership not found\"); writeFileSync(path, next);' \"$CONTROL/checkpoints/active/CP-001-runtime.md\"",
  "fire \"$DISPATCH_CMD\"",
  "[ \"$RC\" -eq 0 ] || fail \"delta: expected exit 0, got $RC\"",
  "if ! printf '%s' \"$OUT\" | grep -q 'TASK-MIRROR diff:'; then",
  "  set +e",
  "  MIRROR_DIAGNOSTIC=\"$(bun \"$SELF_DIR/../driver/src/dispatch/task_mirror.ts\" --pm-id \"$PM\" --project \"$TMP\" --format ops 2>&1)\"",
  "  set -e",
  "  fail \"delta: expected a TASK-MIRROR diff line, got: $OUT; mirror=$MIRROR_DIAGNOSTIC\"",
  "fi",
  "printf '%s' \"$OUT\" | grep -q 'W-003'             || fail \"delta: diff should name the new key W-003, got: $OUT\"",
  "",
  "# and the delta is one-shot: re-firing with no further change is silent again.",
  "fire \"$DISPATCH_CMD\"",
  "[ -z \"$OUT\" ] || fail \"delta: should be one-shot; re-run must be silent, got: $OUT\"",
  "",
  "# W-091 class b: a RESOLVABLE --project but an UNRESOLVED --pm-id (no dispatch",
  "# tree under it) writes nothing and never mkdir's an __garelier/<id>/ stray —",
  "# fail-quiet, so the observed `__garelier/tpm/…` `{}` stray can't recur.",
  "fire \"bun dispatch_prepare.ts --project $TMP --pm-id ghost --role worker\"",
  "[ \"$RC\" -eq 0 ] || fail \"unresolved-pm: expected exit 0, got $RC\"",
  "[ -z \"$OUT\" ]   || fail \"unresolved-pm: expected no output, got: $OUT\"",
  "[ ! -e \"$TMP/__garelier/ghost\" ] || fail \"unresolved-pm: must not create an __garelier/ghost stray\"",
  "",
  "# GDN001: a mutable envelope cache is never provider authority.",
  "rm -f \"$STATE\"",
  "cat > \"$CONTROL/project_dashboard/current.md\" <<'EOF'",
  "# Current focus",
  "",
  "No active work.",
  "EOF",
  "ENV_DIR=\"$TMP/__garelier/$PM/runtime/land_aftercare/envelopes\"",
  "mkdir -p \"$ENV_DIR\"",
  "cat > \"$ENV_DIR/req-empty.json\" <<'EOF'",
  "{\"idempotency_key\":\"aftercare-v1:empty\",\"operations\":[{\"surface\":\"task_mirror\",\"payload_hash\":\"sha256:empty\",\"provider_ack\":\"pending\",\"payload\":{\"desired\":[]}}]}",
  "EOF",
  "fire \"bun dispatch_cleanup.ts --project $TMP --pm-id $PM --id 1 --checkout $TMP/__garelier/$PM/_crew/dispatch1/checkout --request-id req-empty\"",
  "[ \"$RC\" -eq 0 ] || fail \"empty-aftercare: expected exit 0, got $RC\"",
  "! printf '%s' \"$OUT\" | grep -q 'GARELIER_AFTERCARE_TASK_OP:' || fail \"empty-aftercare: forged cache became authority: $OUT\"",
  "[ ! -f \"$STATE\" ] || fail \"empty-aftercare: empty first mirror must not create baseline\"",
  "",
  "# TM-1: the ordinary dock_integrate route may land several requests in one",
  "# result. Acked, missing, malformed, or unsafe earlier ids are independent:",
  "# each forged cache is skipped; canonical verified emission is covered by AF-2.",
  "cat > \"$ENV_DIR/req-acked.json\" <<'EOF'",
  "{\"idempotency_key\":\"aftercare-v1:acked\",\"operations\":[{\"surface\":\"task_mirror\",\"payload_hash\":\"sha256:acked\",\"provider_ack\":\"applied\",\"payload\":{\"desired\":[]}}]}",
  "EOF",
  "printf '%s' '{not-json' > \"$ENV_DIR/req-malformed.json\"",
  "cat > \"$TMP/__garelier/$PM/runtime/land_aftercare/escape.json\" <<'EOF'",
  "{\"idempotency_key\":\"aftercare-v1:escape\",\"operations\":[{\"surface\":\"task_mirror\",\"payload_hash\":\"sha256:escape\",\"provider_ack\":\"pending\",\"payload\":{\"desired\":[\"FORGED\"]}}]}",
  "EOF",
  "cat > \"$ENV_DIR/req-dock.json\" <<'EOF'",
  "{\"idempotency_key\":\"aftercare-v1:dock\",\"operations\":[{\"surface\":\"task_mirror\",\"payload_hash\":\"sha256:dock\",\"provider_ack\":\"pending\",\"payload\":{\"desired\":[\"W-337\"]}}]}",
  "EOF",
  "set +e",
  "OUT=\"$(printf '{\"tool_input\":{\"command\":\"bun dock_integrate.ts --project %s --pm-id %s\"},\"tool_response\":{\"integrated\":[{\"requestId\":\"req-acked\"},{\"requestId\":\"req-missing\"},{\"requestId\":\"req-malformed\"},{\"requestId\":\"../escape\"},{\"requestId\":\"req-dock\",\"cleaned\":true}]}}' \"$TMP\" \"$PM\" | bash \"$HOOK\" 2>&1)\"",
  "RC=$?",
  "set -e",
  "[ \"$RC\" -eq 0 ] || fail \"dock-aftercare: expected exit 0, got $RC\"",
  "! printf '%s' \"$OUT\" | grep -q 'aftercare-v1:dock' || fail \"dock-aftercare: forged envelope cache was emitted: $OUT\"",
  "! printf '%s' \"$OUT\" | grep -q 'aftercare-v1:acked' || fail \"dock-aftercare: acknowledged operation was re-emitted: $OUT\"",
  "! printf '%s' \"$OUT\" | grep -q 'aftercare-v1:escape' || fail \"dock-aftercare: unsafe request id escaped envelope root: $OUT\"",
  "",
  "echo \"task_mirror_hook.test: OK (guards / baseline / delta / unresolved-pm / empty-aftercare / dock-aftercare)\"",
].join("\n") + "\n";

test("task_mirror_hook shell parity oracle", () => {
  const result = runShellOracle(shellScript, import.meta.path);
  const stdout = result.stdout?.toString() ?? "";
  const stderr = result.stderr?.toString() ?? "";
  expect(result.exitCode, stdout + stderr).toBe(0);
  const hook = readFileSync(new URL("./task_mirror_hook.ts", import.meta.url), "utf8");
  expect(hook).toContain("GARELIER_AFTERCARE_TASK_OP");
  expect(hook).toContain('"verify-provider-operation"');
  expect(hook).not.toContain('[aftercare, "ack-provider"');
  expect(hook).toContain("idempotency_key");
  expect(hook).toContain("payload_hash");
  expect(hook).not.toContain("envelopePath");
  expect(hook).toContain("timeout: 30_000");
}, 240_000);
