import { expect, test } from "bun:test";
import { runShellOracle } from "../driver/src/scripts/shell_oracle_test_runner.ts";

// W-111: Bun registers this parity oracle. Its existing shell assertions remain
// verbatim while every Garelier CLI under test is invoked directly with Bun.
const shellScript = [
  "#!/usr/bin/env bash",
  "#",
  "# dispatch_codex_provider.test.ts — pins the Codex subprocess sandbox contract:",
  "#",
  "#   1. Garelier never launches Codex with danger-full-access.",
  "#   2. workspace-write launches grant only writable dispatch roots, the result",
  "#      directory, executable necessity, and explicit --add-dir entries — never",
  "#      broad project/target/skills/CODEX_HOME context roots.",
  "#",
  "# Self-contained: run directly (`bun test dispatch_codex_provider.test.ts`) or from",
  "# ci.ts. Uses a fake `codex` on PATH; does not require the real Codex CLI.",
  "set -uo pipefail",
  "",
  "SELF_DIR=\"$(cd \"$(dirname \"$0\")\" && pwd -P)\"",
  "PROVIDER=\"$SELF_DIR/../driver/src/scripts/dispatch_provider.ts\"",
  "SESSION=\"$SELF_DIR/../driver/src/scripts/provider_session.ts\"",
  "[ -f \"$PROVIDER\" ] || { echo \"dispatch_codex_provider.test: cannot find helper next to me\" >&2; exit 1; }",
  "",
  "fail() { echo \"  FAIL: $*\" >&2; exit 1; }",
  "native_path() {",
  "  local p=\"$1\" abs=\"\"",
  "  abs=\"$(cd \"$p\" 2>/dev/null && pwd -P)\" || return 1",
  "  if command -v cygpath >/dev/null 2>&1; then",
  "    cygpath -m \"$abs\"",
  "  else",
  "    printf '%s\\n' \"$abs\"",
  "  fi",
  "}",
  "child_env_path() {",
  "  local p=\"$1\" abs=\"\"",
  "  abs=\"$(cd \"$p\" 2>/dev/null && pwd -P)\" || return 1",
  "  if command -v cygpath >/dev/null 2>&1; then",
  "    cygpath -w \"$abs\"",
  "  else",
  "    printf '%s\\n' \"$abs\"",
  "  fi",
  "}",
  "contains_line() {",
  "  local file=\"$1\" want=\"$2\"",
  "  grep -Fx -- \"$want\" \"$file\" >/dev/null 2>&1",
  "}",
  "",
  "# W-166: write a context.json whose routing MATCHES the launcher (model/effort/",
  "# source), so the role's assertRoutingMatches (the cf4df38+0a563a4",
  "# explicit-model contract) accepts the launch instead of a silent inheritance.",
  "write_context() {",
  "  printf '{\"project\":{\"project_root\":\"%s\",\"control_root\":\"%s\",\"target_root\":\"%s\"},\"routing\":{\"model\":\"%s\",\"effort\":\"%s\",\"source\":\"%s\"}}\\n' \\",
  "    \"$CONTEXT_TARGET\" \"$PROJECT\" \"$CONTEXT_TARGET\" \"$1\" \"$2\" \"$ROUTING_SOURCE\" > \"$CONTAINER/context.json\"",
  "}",
  "",
  "TMP=\"$(mktemp -d)\"",
  "export CODEX_HOME=\"$TMP/codex-home\"",
  "mkdir -p \"$CODEX_HOME\"",
  "RECOVERY_FIXTURE=\"\"",
  "cleanup() { rm -rf \"$TMP\" 2>/dev/null || true; [ -z \"$RECOVERY_FIXTURE\" ] || rm -rf \"$RECOVERY_FIXTURE\" 2>/dev/null || true; }",
  "trap cleanup EXIT",
  "",
  "FAKEBIN=\"$TMP/fakebin\"",
  "mkdir -p \"$FAKEBIN\"",
  "cat > \"$TMP/wait-for-owner.ts\" <<'TS'",
  "import { existsSync, readdirSync, watch } from \"node:fs\";",
  "import { dirname } from \"node:path\";",
  "const root = process.argv[2] ?? \"\";",
  "const hasOwner = (dir: string): boolean => {",
  "  if (!existsSync(dir)) return false;",
  "  for (const entry of readdirSync(dir, { withFileTypes: true })) {",
  "    if (entry.isFile() && entry.name === \"owner.json\") return true;",
  "    if (entry.isDirectory() && hasOwner(`${dir}/${entry.name}`)) return true;",
  "  }",
  "  return false;",
  "};",
  "if (!hasOwner(root)) await new Promise<void>((resolve, reject) => {",
  "  let watcher: ReturnType<typeof watch> | undefined;",
  "  const timer = setTimeout(() => { watcher?.close(); reject(new Error(\"owner deadline\")); }, 2_000);",
  "  const finish = () => {",
  "    if (!hasOwner(root)) return;",
  "    clearTimeout(timer);",
  "    watcher?.close();",
  "    resolve();",
  "  };",
  "  watcher = watch(dirname(root), { recursive: true }, finish);",
  "  finish();",
  "});",
  "TS",
  "export CODEX_WAIT_OWNER=\"$TMP/wait-for-owner.ts\"",
  "cat > \"$FAKEBIN/codex\" <<'SH'",
  "#!/usr/bin/env bash",
  "set -u",
  "[ \"${GARELIER_ROLE_SEAT:-}\" = \"1\" ] || { echo \"role seat marker missing\" >&2; exit 89; }",
  "if [ \"${CODEX_EXPECT_DECLARED:-present}\" = \"exact\" ]; then",
  "  [ \"${PROJECT_CHECKOUT:-}\" = \"${CODEX_EXPECT_PROJECT_CHECKOUT:?}\" ] || { echo \"dispatch.env checkout mismatch\" >&2; exit 88; }",
  "  [ \"${PROJECT_ROOT:-}\" = \"${CODEX_EXPECT_PROJECT_ROOT:?}\" ] || { echo \"dispatch.env project mismatch\" >&2; exit 88; }",
  "  [ \"${DISPATCH_CONTAINER:-}\" = \"${CODEX_EXPECT_DISPATCH_CONTAINER:?}\" ] || { echo \"dispatch.env container mismatch\" >&2; exit 88; }",
  "  [ \"${PROJECT_DISPATCH_CONTEXT:-}\" = \"${CODEX_EXPECT_DISPATCH_CONTEXT:?}\" ] || { echo \"dispatch.env dispatch context mismatch\" >&2; exit 88; }",
  "elif [ \"${CODEX_EXPECT_DECLARED:-present}\" = \"absent\" ]; then",
  "  [ -z \"${PROJECT_CHECKOUT+x}${PROJECT_ROOT+x}${DISPATCH_CONTAINER+x}${PROJECT_DISPATCH_CONTEXT+x}\" ] || { echo \"removed dispatch.env declaration survived in child\" >&2; exit 88; }",
  "else",
  "  [ -n \"${PROJECT_CHECKOUT:-}\" ] && [ -n \"${PROJECT_ROOT:-}\" ] && [ -n \"${DISPATCH_CONTAINER:-}\" ] || { echo \"dispatch.env was not observed by provider child\" >&2; exit 88; }",
  "fi",
  "if [ \"${CODEX_EXPECT_CORE_OVERRIDE:-}\" = \"exact\" ]; then",
  "  grep -q 'name = \"RUSTC_WRAPPER\"' \"${CODEX_DECLARATION_CONFIG:?}\" || { echo \"exact core collision declaration missing\" >&2; exit 90; }",
  "  grep -q 'name = \"rustc_workspace_wrapper\"' \"$CODEX_DECLARATION_CONFIG\" || { echo \"case-variant core collision declaration missing\" >&2; exit 90; }",
  "  [ \"$(env | grep -c '^RUSTC_WRAPPER=$')\" -eq 1 ] && [ \"$(env | grep -c '^RUSTC_WORKSPACE_WRAPPER=$')\" -eq 1 ] || { echo \"core wrapper keys were not canonical and unique\" >&2; exit 90; }",
  "fi",
  "[ -z \"${RUSTC_WRAPPER:-}\" ] || : > \"${CODEX_SCCACHE_START_MARKER:?}\"",
  "[ -z \"${RUSTC_WRAPPER:-}\" ] && [ -z \"${RUSTC_WORKSPACE_WRAPPER:-}\" ] || { echo \"role inherited a shared rustc wrapper\" >&2; exit 90; }",
  "for probe in \"${CODEX_EXPECT_ABSENT_1:-}\" \"${CODEX_EXPECT_ABSENT_2:-}\" \"${CODEX_EXPECT_ABSENT_3:-}\"; do",
  "  [ -z \"$probe\" ] || [ ! -e \"$probe\" ] || { echo \"pre-launch probe survived: $probe\" >&2; exit 91; }",
  "done",
  "for probe in \"${CODEX_CREATE_PROBE_1:-}\" \"${CODEX_CREATE_PROBE_2:-}\" \"${CODEX_CREATE_PROBE_3:-}\"; do",
  "  [ -z \"$probe\" ] || mkdir -p \"$probe\"",
  "done",
  "[ -z \"${CODEX_CONTEXT_FILE:-}\" ] || grep -q 'context-target-root' \"$CODEX_CONTEXT_FILE\" || exit 92",
  "printf '%s\\n' \"$@\" > \"$CODEX_ARGS_FILE\"",
  "cat > \"$CODEX_STDIN_FILE\"",
  "out=\"\"",
  "prev=\"\"",
  "for arg in \"$@\"; do",
  "  if [ \"$prev\" = \"--output-last-message\" ]; then out=\"$arg\"; break; fi",
  "  prev=\"$arg\"",
  "done",
  "[ -n \"$out\" ] && { mkdir -p \"$(dirname \"$out\")\"; printf 'fake final message\\n' > \"$out\"; }",
  "[ \"${CODEX_NO_RESULT:-0}\" = \"1\" ] && rm -f \"$out\"",
  "[ -n \"${CODEX_STREAM:-}\" ] && printf '%s\\n' \"$CODEX_STREAM\"",
  "if [ -n \"${CODEX_EXPECT_SESSION_LOCK_DIR:-}\" ]; then",
  "  bun \"$CODEX_WAIT_OWNER\" \"$CODEX_EXPECT_SESSION_LOCK_DIR\" || exit 93",
  "fi",
  "exit \"${CODEX_EXIT:-0}\"",
  "SH",
  "chmod +x \"$FAKEBIN/codex\"",
  "",
  "PROJECT=\"$TMP/project\"",
  "CONTAINER=\"$PROJECT/__garelier/tpm/_crew/dispatch1\"",
  "WORKTREE=\"$CONTAINER/checkout\"",
  "TARGET=\"$TMP/target-root\"",
  "CONTEXT_TARGET=\"$TMP/context-target-root\"",
  "EXTRA=\"$TMP/extra-grant\"",
  "RESULT_DIR=\"$TMP/result-dir\"",
  "mkdir -p \"$PROJECT\" \"$CONTAINER\" \"$TARGET\" \"$CONTEXT_TARGET\" \"$EXTRA\" \"$RESULT_DIR\"",
  "git -C \"$PROJECT\" init -q",
  "git -C \"$PROJECT\" config user.email ci@example.invalid",
  "git -C \"$PROJECT\" config user.name CI",
  "git -C \"$PROJECT\" commit -q --allow-empty -m fixture",
  "git -C \"$PROJECT\" worktree add -q -b 'garelier/main/tpm/workbench/#1/shell' \"$WORKTREE\"",
  "mkdir -p \"$PROJECT/__garelier/tpm/_crew/pm\"",
  "cat > \"$PROJECT/__garelier/tpm/_crew/pm/setup_config.toml\" <<'TOML'",
  "[project]",
  "name = \"fixture\"",
  "[branches]",
  "target = \"main\"",
  "integration = \"garelier/main/tpm/studio\"",
  "[[dispatch.env]]",
  "name = \"PROJECT_CHECKOUT\"",
  "value = \"{checkout}\"",
  "why = \"fixture verifies exact producer checkout delivery\"",
  "",
  "[[dispatch.env]]",
  "name = \"PROJECT_ROOT\"",
  "value = \"{project}\"",
  "why = \"fixture verifies exact producer project delivery\"",
  "",
  "[[dispatch.env]]",
  "name = \"DISPATCH_CONTAINER\"",
  "value = \"{container}\"",
  "why = \"fixture verifies exact producer container delivery\"",
  "",
  "[[dispatch.env]]",
  "name = \"PROJECT_DISPATCH_CONTEXT\"",
  "value = \"{dispatch_id}|{checkout}\"",
  "why = \"fixture verifies dispatch-specific expansion\"",
  "",
  "[[dispatch.env]]",
  "name = \"GARELIER_ROLE_SEAT\"",
  "value = \"project-must-not-win\"",
  "why = \"fixture verifies the core-owned provider invariant\"",
  "",
  "[[dispatch.env]]",
  "name = \"RUSTC_WRAPPER\"",
  "value = \"project-must-not-win\"",
  "why = \"fixture verifies the exact-name core-owned provider invariant\"",
  "",
  "[[dispatch.env]]",
  "name = \"rustc_workspace_wrapper\"",
  "value = \"project-case-must-not-win\"",
  "why = \"fixture verifies the case-insensitive core-owned provider invariant\"",
  "TOML",
  "SETUP_CONFIG=\"$PROJECT/__garelier/tpm/_crew/pm/setup_config.toml\"",
  "cp \"$SETUP_CONFIG\" \"$TMP/setup-with-dispatch-env.toml\"",
  "sed '/^\\[\\[dispatch.env\\]\\]/,$d' \"$SETUP_CONFIG\" > \"$TMP/setup-without-dispatch-env.toml\"",
  "PROMPT=\"$CONTAINER/codex_prompt.md\"",
  "RESULT=\"$RESULT_DIR/codex_result.md\"",
  "printf 'Codex-dispatched role sandbox contract:\\ndo the assigned work\\n' > \"$PROMPT\"",
  "ASSIGNMENT=\"$PROJECT/assignment.md\"",
  "printf '# Bound shell role assignment\\n\\n## Acceptance criteria\\n\\n- AC-shell\\n' > \"$ASSIGNMENT\"",
  "printf '+++\\n[ledger]\\n+++\\n\\n# Instruction ledger\\n' > \"$CONTAINER/instructions.md\"",
  "SOURCE_ROOT=\"$(cd \"$SELF_DIR/../../..\" && pwd -P)\"",
  "FOREIGN_ROOT=\"$TMP/foreign-repo\"",
  "mkdir -p \"$FOREIGN_ROOT/skills/garelier-core/driver/src/dispatch\"",
  "printf 'foreign fixture\\n' > \"$FOREIGN_ROOT/skills/garelier-core/driver/src/dispatch/role_binding.ts\"",
  "PROVIDER_NATIVE=\"$PROVIDER\"",
  "command -v cygpath >/dev/null 2>&1 && PROVIDER_NATIVE=\"$(cygpath -m \"$PROVIDER\")\"",
  "bun -e '",
  "  import { resolve } from \"node:path\";",
  "  import { pathToFileURL } from \"node:url\";",
  "  const contract = await import(pathToFileURL(process.argv[1]).href);",
  "  const root = process.argv[2];",
  "  const foreign = process.argv[3];",
  "  const real = \"skills/garelier-core/driver/src/dispatch/role_binding.ts\";",
  "  const prompt = (body) => `${contract.PROMPT_CONTRACT_MARKER}\\n${body}`;",
  "  const expectOk = (body) => { const result = contract.checkPromptContract(prompt(body), root); if (!result.ok) throw new Error(`expected canonical header acceptance: ${body}: ${result.reason}`); };",
  "  const expectRefused = (body) => { const result = contract.checkPromptContract(prompt(body), root); if (result.ok) throw new Error(`expected path refusal: ${body}`); };",
  "  expectOk(`--- a/${real}\\n+++ b/${real}`);",
  "  expectOk(`diff --git a/${real} b/${real}\\n--- a/${real}\\n+++ b/${real}`);",
  "  expectRefused(`a/${real}`);",
  "  expectRefused(`--- a/b/${real}`);",
  "  expectRefused(`--- a/../../${real}`);",
  "  expectRefused(`+++ b//${real}`);",
  "  expectRefused(`--- a/skills/garelier-core/driver/src/dispatch/missing.ts`);",
  "  expectRefused(resolve(foreign, real).replace(/\\\\/g, \"/\"));",
  "  expectRefused(`--- a/skills/garelier-core/scripts/heavy_compile_lock.ts`);",
  "' \"$PROVIDER_NATIVE\" \"$(native_path \"$SOURCE_ROOT\")\" \"$(native_path \"$FOREIGN_ROOT\")\" || fail \"canonical Git diff-header contract fixture failed\"",
  "cat > \"$TMP/issue-binding.ts\" <<'TS'",
  "import { join } from \"node:path\";",
  "const { issueRoleAuthorization, dispatchExecutionIdentity, readCurrentRoleAuthorization, hashRoleFile } = await import(process.argv[2]);",
  "const { resolveRoleKnowledgeBinding } = await import(process.argv[3]);",
  "const project = process.argv[4], assignment = process.argv[5], prompt = process.argv[6], base = process.argv[7];",
  "const routeModel = process.argv[8] ?? '', routeEffort = process.argv[9] ?? '', routeSource = process.argv[10] ?? '';",
  "const dispatchId = Number(process.argv[11] ?? '1');",
  "const identity = dispatchExecutionIdentity(dispatchId);",
  "const ledger = join(project, '__garelier', 'tpm', '_crew', `dispatch${dispatchId}`, 'instructions.md');",
  "let previous = null; try { previous = readCurrentRoleAuthorization({ project_root: project, pm_id: 'tpm', identity }); } catch {}",
  "const authorization = issueRoleAuthorization({",
  "  project_root: project, pm_id: 'tpm', identity, role: 'worker', carabiner: previous ? 'role_recovery' : 'implementation',",
  "  item: { work_id: 'W-shell', revision: '1', session_id: 'cs-shell', authority_path: assignment },",
  "  assignment_path: assignment, prompt_path: prompt, initial_instructions_path: ledger, routing: { provider: 'codex-cli', model: routeModel, effort: routeEffort, source: routeSource },",
  "  lens: { ref: null, source: 'none', registry_path: null, pack_path: null },",
  "  knowledge: resolveRoleKnowledgeBinding({ projectRoot: project, pmId: 'tpm', role: 'worker', required: [] }),",
  "  integration: { ref: 'main', base_sha: base }, issuer: { role: 'dock', id: 'shell-oracle' },",
  "  ...(previous ? { recovery: { reason: 'provider_replacement', supersedes_digest: previous.core_digest, wip: [{ path: assignment, content_hash: hashRoleFile(assignment) }], dependencies_reaudited: true, acceptance_reaudited: ['AC-shell'] } } : {}),",
  "});",
  "process.stdout.write(`${authorization.core.generation}:${authorization.core_digest}`);",
  "TS",
  "ROUTING_MODEL=gpt-test",
  "ROUTING_EFFORT=high",
  "ROUTING_SOURCE=shell-oracle",
  "refresh_binding() {",
  "  local dispatch_id=\"${1:-1}\" binding_prompt=\"${2:-$PROMPT}\" issued",
  "  issued=\"$(bun \"$TMP/issue-binding.ts\" \"$SELF_DIR/../driver/src/dispatch/role_binding.ts\" \"$SELF_DIR/../driver/src/dispatch/knowledge_binding.ts\" \"$PROJECT\" \"$ASSIGNMENT\" \"$binding_prompt\" \"$(git -C \"$PROJECT\" rev-parse HEAD)\" \"$ROUTING_MODEL\" \"$ROUTING_EFFORT\" \"$ROUTING_SOURCE\" \"$dispatch_id\")\"",
  "  BINDING_GENERATION=\"${issued%%:*}\"; BINDING_DIGEST=\"${issued#*:}\"",
  "  [ \"${#BINDING_DIGEST}\" -eq 64 ] || fail \"binding issuer did not return a digest\"",
  "  BINDING_FLAGS=(--provider codex --pm-id tpm --binding-generation \"$BINDING_GENERATION\" --binding-digest \"$BINDING_DIGEST\" --model \"$ROUTING_MODEL\" --effort \"$ROUTING_EFFORT\" --model-source \"$ROUTING_SOURCE\")",
  "}",
  "refresh_binding",
  "write_context gpt-test high",
  "",
  "export CODEX_ARGS_FILE=\"$TMP/codex_args.txt\"",
  "export CODEX_STDIN_FILE=\"$TMP/codex_stdin.txt\"",
  "export CODEX_SCCACHE_START_MARKER=\"$TMP/sccache-server-started\"",
  "OUT=\"$TMP/out.txt\"",
  "ERR=\"$TMP/err.txt\"",
  "if ! CODEX_EXPECT_DECLARED=exact CODEX_EXPECT_CORE_OVERRIDE=exact CODEX_DECLARATION_CONFIG=\"$SETUP_CONFIG\" RUSTC_WRAPPER=ambient rustc_workspace_wrapper=ambient-case PROJECT_CHECKOUT=ambient PROJECT_ROOT=ambient DISPATCH_CONTAINER=ambient PROJECT_DISPATCH_CONTEXT=ambient \\",
  "    CODEX_EXPECT_PROJECT_CHECKOUT=\"$(child_env_path \"$WORKTREE\")\" CODEX_EXPECT_PROJECT_ROOT=\"$(child_env_path \"$PROJECT\")\" \\",
  "    CODEX_EXPECT_DISPATCH_CONTAINER=\"$(child_env_path \"$CONTAINER\")\" CODEX_EXPECT_DISPATCH_CONTEXT=\"1|$(child_env_path \"$WORKTREE\")\" \\",
  "    CODEX_CONTEXT_FILE=\"$CONTAINER/context.json\" CODEX_EXPECT_SESSION_LOCK_DIR=\"$RESULT_DIR/locks\" CODEX_STREAM='{\"type\":\"thread.started\",\"thread_id\":\"thread-shell-1\"}' PATH=\"$FAKEBIN:$PATH\" bun \"$PROVIDER\" \\",
  "    --worktree \"$WORKTREE\" \\",
  "    --project \"$PROJECT\" \\",
  "    \"${BINDING_FLAGS[@]}\" \\",
  "    --prompt \"$PROMPT\" \\",
  "    --result \"$RESULT\" \\",
  "    --target-root \"$TARGET\" \\",
  "    --add-dir \"$EXTRA\" \\",
  "    --role worker --slug shell-one \\",
  "    --model gpt-test \\",
  "    --effort high \\",
  "    >\"$OUT\" 2>\"$ERR\"; then",
  "  fail \"workspace-write launch failed. stderr=$(cat \"$ERR\")\"",
  "fi",
  "",
  "contains_line \"$CODEX_ARGS_FILE\" \"exec\" || fail \"codex args missing exec\"",
  "contains_line \"$CODEX_ARGS_FILE\" \"--cd\" || fail \"codex args missing --cd\"",
  "contains_line \"$CODEX_ARGS_FILE\" \"$(native_path \"$WORKTREE\")\" || fail \"codex args missing worktree path\"",
  "contains_line \"$CODEX_ARGS_FILE\" \"--sandbox\" || fail \"codex args missing --sandbox\"",
  "contains_line \"$CODEX_ARGS_FILE\" \"workspace-write\" || fail \"codex args missing workspace-write\"",
  "contains_line \"$CODEX_ARGS_FILE\" \"approval_policy=never\" || fail \"codex args missing approval_policy=never\"",
  "contains_line \"$CODEX_ARGS_FILE\" \"--json\" || fail \"codex args missing --json\"",
  "contains_line \"$CODEX_ARGS_FILE\" \"gpt-test\" || fail \"codex args missing model\"",
  "contains_line \"$CODEX_ARGS_FILE\" 'model_reasoning_effort=\"high\"' || fail \"codex args missing reasoning effort\"",
  "",
  "for granted in \"$WORKTREE\" \"$CONTAINER\" \"$RESULT_DIR\" \"$EXTRA\"; do",
  "  contains_line \"$CODEX_ARGS_FILE\" \"$(native_path \"$granted\")\" || fail \"missing --add-dir grant for $granted\"",
  "done",
  "for readonly_root in \"$PROJECT\" \"$TARGET\" \"$CONTEXT_TARGET\" \"$(cd \"$SELF_DIR/../..\" && pwd -P)\"; do",
  "  ! contains_line \"$CODEX_ARGS_FILE\" \"$(native_path \"$readonly_root\")\" || fail \"broad read-only root became writable: $readonly_root\"",
  "done",
  "! grep -q 'danger-full-access' \"$CODEX_ARGS_FILE\" || fail \"danger-full-access leaked into codex args\"",
  "grep -q 'fake final message' \"$OUT\" || fail \"helper did not echo captured final message\"",
  "grep -q 'do the assigned work' \"$CODEX_STDIN_FILE\" || fail \"prompt was not sent on stdin\"",
  "grep -q '\"session_id\": \"thread-shell-1\"' \"$RESULT_DIR/session.json\" || fail \"exact thread id was not persisted\"",
  "grep -q '\"status\": \"ready\"' \"$RESULT_DIR/session.json\" || fail \"successful session record was not marked ready\"",
  "[ -d \"$RESULT_DIR/locks\" ] && [ -z \"$(find \"$RESULT_DIR/locks\" -mindepth 1 -print -quit)\" ] || fail \"initial session lock was not released\"",
  "[ ! -e \"$CODEX_SCCACHE_START_MARKER\" ] || fail \"role fixture lazily started shared sccache\"",
  "",
  "# --- W-563/GDN-002: exact-session resume uses the same producer env contract ---",
  "FOLLOWUP=\"$CONTAINER/followup.md\"; FOLLOWUP_RESULT=\"$RESULT_DIR/followup.result.md\"",
  "printf 'Continue the exact recorded session.\\n' > \"$FOLLOWUP\"",
  "if ! CODEX_EXPECT_DECLARED=exact CODEX_EXPECT_CORE_OVERRIDE=exact CODEX_DECLARATION_CONFIG=\"$SETUP_CONFIG\" RUSTC_WRAPPER=ambient rustc_workspace_wrapper=ambient-case PROJECT_CHECKOUT=ambient PROJECT_ROOT=ambient DISPATCH_CONTAINER=ambient PROJECT_DISPATCH_CONTEXT=ambient \\",
  "    CODEX_EXPECT_PROJECT_CHECKOUT=\"$(child_env_path \"$WORKTREE\")\" CODEX_EXPECT_PROJECT_ROOT=\"$(child_env_path \"$PROJECT\")\" \\",
  "    CODEX_EXPECT_DISPATCH_CONTAINER=\"$(child_env_path \"$CONTAINER\")\" CODEX_EXPECT_DISPATCH_CONTEXT=\"1|$(child_env_path \"$WORKTREE\")\" \\",
  "    CODEX_STREAM='resume exact result' PATH=\"$FAKEBIN:$PATH\" bun \"$SESSION\" resume --record \"$RESULT_DIR/session.json\" \\",
  "    --instruction \"$FOLLOWUP\" --result \"$FOLLOWUP_RESULT\" --worktree \"$WORKTREE\" \\",
  "    --expected-model \"$ROUTING_MODEL\" --expected-effort \"$ROUTING_EFFORT\" --expected-source \"$ROUTING_SOURCE\" \\",
  "    --project \"$PROJECT\" --pm-id tpm --dispatch-id 1 --role worker --slug shell-one \\",
  "    --binding-generation \"$BINDING_GENERATION\" --binding-digest \"$BINDING_DIGEST\" >\"$OUT\" 2>\"$ERR\"; then",
  "  fail \"exact-session dispatch env resume failed. stderr=$(cat \"$ERR\")\"",
  "fi",
  "grep -q 'resume exact result' \"$FOLLOWUP_RESULT\" || fail \"resume result was not captured\"",
  "cp \"$TMP/setup-without-dispatch-env.toml\" \"$SETUP_CONFIG\"",
  "printf 'Continue after declaration removal.\\n' > \"$FOLLOWUP\"",
  "if ! CODEX_EXPECT_DECLARED=absent CODEX_STREAM='resume declaration removed' PATH=\"$FAKEBIN:$PATH\" bun \"$SESSION\" resume \\",
  "    --record \"$RESULT_DIR/session.json\" --instruction \"$FOLLOWUP\" --result \"$FOLLOWUP_RESULT\" --worktree \"$WORKTREE\" \\",
  "    --expected-model \"$ROUTING_MODEL\" --expected-effort \"$ROUTING_EFFORT\" --expected-source \"$ROUTING_SOURCE\" \\",
  "    --project \"$PROJECT\" --pm-id tpm --dispatch-id 1 --role worker --slug shell-one \\",
  "    --binding-generation \"$BINDING_GENERATION\" --binding-digest \"$BINDING_DIGEST\" >\"$OUT\" 2>\"$ERR\"; then",
  "  fail \"exact-session declaration-removal counterfactual failed. stderr=$(cat \"$ERR\")\"",
  "fi",
  "grep -q 'resume declaration removed' \"$FOLLOWUP_RESULT\" || fail \"declaration-removal resume result was not captured\"",
  "cp \"$TMP/setup-with-dispatch-env.toml\" \"$SETUP_CONFIG\"",
  "",
  "# --- W-563: a second real dispatch expands its own checkout; removal disappears from the child ---",
  "CONTAINER2=\"$PROJECT/__garelier/tpm/_crew/dispatch2\"",
  "WORKTREE2=\"$CONTAINER2/checkout\"",
  "PROMPT2=\"$CONTAINER2/codex_prompt.md\"",
  "RESULT_DIR2=\"$TMP/result-dir-2\"",
  "RESULT2=\"$RESULT_DIR2/codex_result.md\"",
  "mkdir -p \"$CONTAINER2\" \"$RESULT_DIR2\"",
  "printf '+++\\n[ledger]\\n+++\\n\\n# Instruction ledger\\n' > \"$CONTAINER2/instructions.md\"",
  "git -C \"$PROJECT\" worktree add -q -b 'garelier/main/tpm/workbench/#2/shell' \"$WORKTREE2\"",
  "cp \"$PROMPT\" \"$PROMPT2\"",
  "cp \"$CONTAINER/context.json\" \"$CONTAINER2/context.json\"",
  "refresh_binding 2 \"$PROMPT2\"",
  "if ! CODEX_EXPECT_DECLARED=exact PROJECT_CHECKOUT=ambient PROJECT_ROOT=ambient DISPATCH_CONTAINER=ambient PROJECT_DISPATCH_CONTEXT=ambient \\",
  "    CODEX_EXPECT_PROJECT_CHECKOUT=\"$(child_env_path \"$WORKTREE2\")\" CODEX_EXPECT_PROJECT_ROOT=\"$(child_env_path \"$PROJECT\")\" \\",
  "    CODEX_EXPECT_DISPATCH_CONTAINER=\"$(child_env_path \"$CONTAINER2\")\" CODEX_EXPECT_DISPATCH_CONTEXT=\"2|$(child_env_path \"$WORKTREE2\")\" \\",
  "    CODEX_STREAM='{\"type\":\"thread.started\",\"thread_id\":\"thread-shell-2\"}' PATH=\"$FAKEBIN:$PATH\" bun \"$PROVIDER\" \\",
  "    --worktree \"$WORKTREE2\" --project \"$PROJECT\" \"${BINDING_FLAGS[@]}\" --prompt \"$PROMPT2\" --result \"$RESULT2\" \\",
  "    --role worker --slug shell-two >\"$OUT\" 2>\"$ERR\"; then",
  "  fail \"second dispatch env launch failed. stderr=$(cat \"$ERR\")\"",
  "fi",
  "sed '/^\\[\\[dispatch.env\\]\\]/,$d' \"$SETUP_CONFIG\" > \"$TMP/setup-without-dispatch-env.toml\"",
  "cp \"$TMP/setup-without-dispatch-env.toml\" \"$SETUP_CONFIG\"",
  "RESULT_DIR3=\"$TMP/result-dir-3\"; RESULT3=\"$RESULT_DIR3/codex_result.md\"; mkdir -p \"$RESULT_DIR3\"",
  "refresh_binding 2 \"$PROMPT2\"",
  "if ! CODEX_EXPECT_DECLARED=absent CODEX_STREAM='{\"type\":\"thread.started\",\"thread_id\":\"thread-shell-2-none\"}' PATH=\"$FAKEBIN:$PATH\" bun \"$PROVIDER\" \\",
  "    --worktree \"$WORKTREE2\" --project \"$PROJECT\" \"${BINDING_FLAGS[@]}\" --prompt \"$PROMPT2\" --result \"$RESULT3\" \\",
  "    --role worker --slug shell-two-none >\"$OUT\" 2>\"$ERR\"; then",
  "  fail \"dispatch env removal counterfactual failed. stderr=$(cat \"$ERR\")\"",
  "fi",
  "cp \"$TMP/setup-with-dispatch-env.toml\" \"$SETUP_CONFIG\"",
  "echo \"W563_PROVIDER_ENV dispatch1=$(native_path \"$WORKTREE\") dispatch2=$(native_path \"$WORKTREE2\") removed=absent ambient=overridden core=1\"",
  "",
  "# --- W-387 I25: recovery context materializes from candidate cwd into its dispatch container ---",
  "RECOVERY_FIXTURE=\"$TMP/recovery-fixture\"",
  "REC_PROJECT=\"$RECOVERY_FIXTURE/project\"",
  "REC_CONTAINER=\"$REC_PROJECT/__garelier/tpm/_crew/dispatch1\"",
  "REC_WORKTREE=\"$REC_CONTAINER/checkout\"",
  "REC_RESULT_DIR=\"$REC_WORKTREE/result\"",
  "REC_PROMPT=\"$REC_CONTAINER/codex_prompt.md\"",
  "REC_ASSIGNMENT=\"$REC_PROJECT/assignment.md\"",
  "mkdir -p \"$REC_PROJECT\" \"$REC_CONTAINER\"",
  "git -C \"$REC_PROJECT\" init -q",
  "git -C \"$REC_PROJECT\" config user.email ci@example.invalid",
  "git -C \"$REC_PROJECT\" config user.name CI",
  "git -C \"$REC_PROJECT\" commit -q --allow-empty -m fixture",
  "git -C \"$REC_PROJECT\" worktree add -q -b 'garelier/main/tpm/workbench/#1/recovery-context' \"$REC_WORKTREE\"",
  "mkdir -p \"$REC_PROJECT/__garelier/tpm/_crew/pm\"",
  "cp \"$PROJECT/__garelier/tpm/_crew/pm/setup_config.toml\" \"$REC_PROJECT/__garelier/tpm/_crew/pm/setup_config.toml\"",
  "mkdir -p \"$REC_RESULT_DIR\"",
  "printf 'Codex-dispatched role sandbox contract:\\ndo the assigned work\\n' > \"$REC_PROMPT\"",
  "printf '# Recovery context assignment\\n\\n## Acceptance criteria\\n\\n- AC-shell\\n' > \"$REC_ASSIGNMENT\"",
  "printf '+++\\n[ledger]\\n+++\\n\\n# Instruction ledger\\n' > \"$REC_CONTAINER/instructions.md\"",
  "issue_recovery_binding() {",
  "  GARELIER_PROJECT_ROOT=\"$REC_PROJECT\" bun \"$TMP/issue-binding.ts\" \"$SELF_DIR/../driver/src/dispatch/role_binding.ts\" \"$SELF_DIR/../driver/src/dispatch/knowledge_binding.ts\" \"$REC_PROJECT\" \"$REC_ASSIGNMENT\" \"$REC_PROMPT\" \"$(git -C \"$REC_PROJECT\" rev-parse HEAD)\" gpt-test high shell-oracle",
  "}",
  "issue_recovery_binding >/dev/null",
  "REC_ISSUED=\"$(issue_recovery_binding)\"",
  "REC_GENERATION=\"${REC_ISSUED%%:*}\"; REC_DIGEST=\"${REC_ISSUED#*:}\"",
  "[ \"$REC_GENERATION\" -eq 2 ] && [ \"${#REC_DIGEST}\" -eq 64 ] || fail \"recovery context binding setup failed\"",
  "REC_BINDING_ROOT=\"$(native_path \"$REC_PROJECT/__garelier/tpm/runtime/dispatch/bindings\")\"",
  "REC_GUARD_ROOTS=\"$(bun -e 'process.stdout.write(JSON.stringify([process.argv[1]]))' \"$REC_BINDING_ROOT\")\"",
  "rm -f \"$CODEX_ARGS_FILE\" \"$CODEX_STDIN_FILE\" \"$OUT\" \"$ERR\"",
  "if ! ( cd \"$REC_WORKTREE\" && env -u GARELIER_PROJECT_ROOT -u GARELIER_TARGET_ROOT -u GARELIER_CONTAINER -u GARELIER_SCRATCHPAD \\",
  "    GARELIER_PATH_GUARD_ROOTS=\"$REC_GUARD_ROOTS\" \\",
  "    CODEX_EXPECT_SESSION_LOCK_DIR=\"$REC_RESULT_DIR/locks\" CODEX_STREAM='{\"type\":\"thread.started\",\"thread_id\":\"thread-shell-recovery-context\"}' \\",
  "    PATH=\"$FAKEBIN:$PATH\" bun \"$PROVIDER\" --provider codex --worktree \"$REC_WORKTREE\" --project \"$REC_PROJECT\" \\",
  "    --pm-id tpm --binding-generation \"$REC_GENERATION\" --binding-digest \"$REC_DIGEST\" \\",
  "    --prompt \"$REC_PROMPT\" --result \"$REC_RESULT_DIR/result.md\" --model gpt-test --effort high --model-source shell-oracle \\",
  "    >\"$OUT\" 2>\"$ERR\" ); then",
  "  fail \"candidate-cwd recovery context launch failed. stderr=$(cat \"$ERR\")\"",
  "fi",
  "grep -q '\"producer_binding\"' \"$REC_CONTAINER/context.json\" || fail \"recovery context was not canonically materialized\"",
  "grep -q '\"skipped\"' \"$REC_CONTAINER/context.json\" || fail \"recovery context did not report skipped dispatch.env declarations\"",
  "grep -q '\"PROJECT_CHECKOUT\"' \"$REC_CONTAINER/context.json\" || fail \"recovery context skipped declaration name missing\"",
  "grep -q '\"fixture verifies exact producer checkout delivery\"' \"$REC_CONTAINER/context.json\" || fail \"recovery context skipped declaration why missing\"",
  "grep -q '\"unavailable_placeholders\"' \"$REC_CONTAINER/context.json\" || fail \"recovery context skipped declaration reason missing\"",
  "[ -z \"$(find \"$REC_CONTAINER\" -maxdepth 1 -name '.context.json.*.tmp' -print -quit)\" ] || fail \"recovery context temporary file survived\"",
  "",
  "# --- W-101: model aliases resolve before launch; unknown bare aliases fail fast --",
  "rm -f \"$CODEX_ARGS_FILE\" \"$CODEX_STDIN_FILE\" \"$OUT\" \"$ERR\" \"$RESULT\"",
  "ROUTING_MODEL=gpt-5.6-sol",
  "write_context gpt-5.6-sol \"\"", // W-166: sol resolves to gpt-5.6-sol before the routing assert
  "refresh_binding",
  "if ! PATH=\"$FAKEBIN:$PATH\" bun \"$PROVIDER\" \\",
  "    --worktree \"$WORKTREE\" --project \"$PROJECT\" \"${BINDING_FLAGS[@]}\" --prompt \"$PROMPT\" --result \"$RESULT\" --add-dir \"$EXTRA\" \\",
  "    --model sol >\"$OUT\" 2>\"$ERR\"; then",
  "  fail \"sol alias launch failed. stderr=$(cat \"$ERR\")\"",
  "fi",
  "contains_line \"$CODEX_ARGS_FILE\" \"gpt-5.6-sol\" || fail \"sol alias did not resolve to gpt-5.6-sol\"",
  "! contains_line \"$CODEX_ARGS_FILE\" \"sol\" || fail \"raw sol alias leaked into codex args\"",
  "",
  "rm -f \"$CODEX_ARGS_FILE\" \"$CODEX_STDIN_FILE\" \"$OUT\" \"$ERR\" \"$RESULT\"",
  "ROUTING_MODEL=gpt-5.6-terra",
  "write_context gpt-5.6-terra \"\"", // W-166: terra resolves to gpt-5.6-terra
  "refresh_binding",
  "if ! PATH=\"$FAKEBIN:$PATH\" bun \"$PROVIDER\" \\",
  "    --worktree \"$WORKTREE\" --project \"$PROJECT\" \"${BINDING_FLAGS[@]}\" --prompt \"$PROMPT\" --result \"$RESULT\" \\",
  "    --model terra >\"$OUT\" 2>\"$ERR\"; then",
  "  fail \"terra alias launch failed. stderr=$(cat \"$ERR\")\"",
  "fi",
  "contains_line \"$CODEX_ARGS_FILE\" \"gpt-5.6-terra\" || fail \"terra alias did not resolve to gpt-5.6-terra\"",
  "! contains_line \"$CODEX_ARGS_FILE\" \"terra\" || fail \"raw terra alias leaked into codex args\"",
  "",
  "rm -f \"$CODEX_ARGS_FILE\" \"$CODEX_STDIN_FILE\" \"$OUT\" \"$ERR\" \"$RESULT\"",
  "ROUTING_MODEL=gpt-test",
  "refresh_binding",
  "if PATH=\"$FAKEBIN:$PATH\" bun \"$PROVIDER\" \\",
  "    --worktree \"$WORKTREE\" --project \"$PROJECT\" \"${BINDING_FLAGS[@]}\" --prompt \"$PROMPT\" --result \"$RESULT\" \\",
  "    --model aurora >\"$OUT\" 2>\"$ERR\"; then",
  "  fail \"unknown aurora alias unexpectedly launched\"",
  "fi",
  "grep -q \"unknown model alias 'aurora'\" \"$ERR\" || fail \"unknown alias diagnostic missing\"",
  "grep -q 'use a full model name or omit --model' \"$ERR\" || fail \"unknown alias remediation missing\"",
  "[ ! -f \"$CODEX_ARGS_FILE\" ] || fail \"fake codex was invoked after unknown alias rejection\"",
  "",
  "# W-166: remaining launches retain the canonical bound gpt-test/high route.",
  "write_context gpt-test high",
  "# --- W-101: turn.failed beats a misleading process exit 0 and missing result --",
  "rm -f \"$CODEX_ARGS_FILE\" \"$CODEX_STDIN_FILE\" \"$OUT\" \"$ERR\" \"$RESULT\"",
  "refresh_binding",
  "if CODEX_NO_RESULT=1 CODEX_STREAM='{\"type\":\"turn.failed\",\"error\":{\"message\":\"model unavailable\"}}' \\",
  "    CODEX_CREATE_PROBE_1=\"$WORKTREE/.agents\" CODEX_CREATE_PROBE_2=\"$EXTRA/.codex\" CODEX_CREATE_PROBE_3=\"$EXTRA/.git\" \\",
  "    PATH=\"$FAKEBIN:$PATH\" bun \"$PROVIDER\" \\",
  "    --worktree \"$WORKTREE\" --project \"$PROJECT\" \"${BINDING_FLAGS[@]}\" --prompt \"$PROMPT\" --result \"$RESULT\" --add-dir \"$EXTRA\" \\",
  "    >\"$OUT\" 2>\"$ERR\"; then",
  "  fail \"turn.failed stream unexpectedly returned success\"",
  "fi",
  "grep -q '^ROLE_LAUNCH_FAILED: model unavailable$' \"$ERR\" || fail \"turn.failed marker missing\"",
  "grep -q '^provider result unavailable$' \"$OUT\" || fail \"failed-result sentinel missing\"",
  "[ ! -e \"$WORKTREE/.agents\" ] || fail \"failed child worktree probe was not swept in finally\"",
  "[ ! -e \"$EXTRA/.codex\" ] || fail \"failed child add-dir probe was not swept in finally\"",
  "[ ! -e \"$EXTRA/.git\" ] || fail \"failed child empty .git probe was not swept in finally\"",
  "",
  "# --- pre/final sweep: empty probes removed; real/non-empty git metadata kept --",
  "mkdir -p \"$WORKTREE/.agents\" \"$PROJECT/.agents\" \"$TMP/.agents\" \"$WORKTREE/.codex\" \"$PROJECT/.codex\" \\",
  "  \"$EXTRA/.agents\" \"$EXTRA/.codex\" \"$EXTRA/.git\"",
  "printf 'keep\\n' > \"$PROJECT/.codex/keep.txt\"",
  "printf 'gitdir: elsewhere\\n' > \"$TARGET/.git\"",
  "rm -f \"$CODEX_ARGS_FILE\" \"$CODEX_STDIN_FILE\" \"$OUT\" \"$ERR\" \"$RESULT\"",
  "refresh_binding",
  "if ! CODEX_EXPECT_ABSENT_1=\"$WORKTREE/.agents\" CODEX_EXPECT_ABSENT_2=\"$EXTRA/.codex\" CODEX_EXPECT_ABSENT_3=\"$EXTRA/.git\" \\",
  "    PATH=\"$FAKEBIN:$PATH\" bun \"$PROVIDER\" \\",
  "    --worktree \"$WORKTREE\" --project \"$PROJECT\" \"${BINDING_FLAGS[@]}\" --prompt \"$PROMPT\" --result \"$RESULT\" --add-dir \"$EXTRA\" \\",
  "    >\"$OUT\" 2>\"$ERR\"; then",
  "  fail \"probe sweep launch failed. stderr=$(cat \"$ERR\")\"",
  "fi",
  "[ ! -e \"$WORKTREE/.agents\" ] || fail \"worktree .agents was not swept\"",
  "[ ! -e \"$PROJECT/.agents\" ] || fail \"project .agents was not swept\"",
  "[ ! -e \"$TMP/.agents\" ] || fail \"project-parent .agents was not swept\"",
  "[ ! -e \"$WORKTREE/.codex\" ] || fail \"worktree .codex was not swept\"",
  "[ ! -e \"$EXTRA/.agents\" ] || fail \"add-dir sibling .agents was not swept\"",
  "[ ! -e \"$EXTRA/.codex\" ] || fail \"add-dir sibling .codex was not swept\"",
  "[ ! -e \"$EXTRA/.git\" ] || fail \"empty add-dir .git probe was not removed\"",
  "[ -f \"$PROJECT/.git/HEAD\" ] || fail \"non-empty project .git was modified\"",
  "[ -f \"$TARGET/.git\" ] || fail \"worktree-style .git file was modified\"",
  "[ -f \"$PROJECT/.codex/keep.txt\" ] || fail \"non-empty project .codex was modified\"",
  "grep -q 'probe sweep kept non-empty directory:' \"$ERR\" || fail \"non-empty probe warning missing\"",
  "grep -q 'protected project/worktree git metadata' \"$ERR\" || fail \"protected .git retention warning missing\"",
  "",
  "if command -v cygpath >/dev/null 2>&1; then",
  "  rm -f \"$CODEX_ARGS_FILE\" \"$CODEX_STDIN_FILE\" \"$OUT\" \"$ERR\" \"$RESULT\"",
  "  WIN_WORKTREE=\"$(cygpath -m \"$WORKTREE\")\"",
  "  WIN_PROJECT=\"$(cygpath -m \"$PROJECT\")\"",
  "  WIN_PROMPT=\"$(cygpath -m \"$PROMPT\")\"",
  "  WIN_RESULT=\"$(cygpath -m \"$RESULT\")\"",
  "  refresh_binding",
  "  if ! PATH=\"$FAKEBIN:$PATH\" bun \"$PROVIDER\" \\",
  "      --worktree \"$WIN_WORKTREE\" \\",
  "      --project \"$WIN_PROJECT\" \\",
  "      \"${BINDING_FLAGS[@]}\" \\",
  "      --prompt \"$WIN_PROMPT\" \\",
  "      --result \"$WIN_RESULT\" \\",
  "      --sandbox read-only \\",
  "      >\"$OUT\" 2>\"$ERR\"; then",
  "    fail \"Windows-style path launch failed. stderr=$(cat \"$ERR\")\"",
  "  fi",
  "  contains_line \"$CODEX_ARGS_FILE\" \"read-only\" || fail \"Windows-style path launch missing read-only sandbox\"",
  "  contains_line \"$CODEX_ARGS_FILE\" \"$(native_path \"$WORKTREE\")\" || fail \"Windows-style path launch did not normalize worktree\"",
  "  grep -q 'fake final message' \"$OUT\" || fail \"Windows-style path launch did not echo final message\"",
  "  grep -q 'do the assigned work' \"$CODEX_STDIN_FILE\" || fail \"Windows-style prompt was not sent on stdin\"",
  "fi",
  "",
  "rm -f \"$CODEX_ARGS_FILE\" \"$CODEX_STDIN_FILE\" \"$OUT\" \"$ERR\"",
  "refresh_binding",
  "if PATH=\"$FAKEBIN:$PATH\" bun \"$PROVIDER\" \\",
  "    --worktree \"$WORKTREE\" --project \"$PROJECT\" \"${BINDING_FLAGS[@]}\" --prompt \"$PROMPT\" --result \"$RESULT\" \\",
  "    --sandbox danger-full-access >\"$OUT\" 2>\"$ERR\"; then",
  "  fail \"danger-full-access launch unexpectedly succeeded\"",
  "fi",
  "grep -q 'danger-full-access is not allowed' \"$ERR\" || fail \"danger-full-access rejection message missing\"",
  "[ ! -f \"$CODEX_ARGS_FILE\" ] || fail \"fake codex was invoked after danger-full-access rejection\"",
  "",
  "# --- broad CODEX_HOME/skills context stays readable but never writable --",
  "CODEX_HOME_EXISTS=\"$TMP/codex-home-exists\"",
  "mkdir -p \"$CODEX_HOME_EXISTS/skills\"",
  "rm -f \"$CODEX_ARGS_FILE\" \"$CODEX_STDIN_FILE\" \"$OUT\" \"$ERR\"",
  "refresh_binding",
  "if ! CODEX_HOME=\"$CODEX_HOME_EXISTS\" PATH=\"$FAKEBIN:$PATH\" bun \"$PROVIDER\" \\",
  "    --worktree \"$WORKTREE\" --project \"$PROJECT\" \"${BINDING_FLAGS[@]}\" --prompt \"$PROMPT\" --result \"$RESULT\" \\",
  "    >\"$OUT\" 2>\"$ERR\"; then",
  "  fail \"CODEX_HOME skills no-grant launch failed. stderr=$(cat \"$ERR\")\"",
  "fi",
  "! contains_line \"$CODEX_ARGS_FILE\" \"$(native_path \"$CODEX_HOME_EXISTS/skills\")\" \\",
  "  || fail \"existing \\$CODEX_HOME/skills became writable\"",
  "",
  "CODEX_HOME_MISSING=\"$TMP/codex-home-missing\"",
  "rm -f \"$CODEX_ARGS_FILE\" \"$CODEX_STDIN_FILE\" \"$OUT\" \"$ERR\"",
  "refresh_binding",
  "if ! CODEX_HOME=\"$CODEX_HOME_MISSING\" PATH=\"$FAKEBIN:$PATH\" bun \"$PROVIDER\" \\",
  "    --worktree \"$WORKTREE\" --project \"$PROJECT\" \"${BINDING_FLAGS[@]}\" --prompt \"$PROMPT\" --result \"$RESULT\" \\",
  "    >\"$OUT\" 2>\"$ERR\"; then",
  "  fail \"CODEX_HOME missing-skills launch failed. stderr=$(cat \"$ERR\")\"",
  "fi",
  "! grep -qF \"codex-home-missing\" \"$CODEX_ARGS_FILE\" \\",
  "  || fail \"unexpected --add-dir grant for nonexistent \\$CODEX_HOME/skills\"",
  "",
  "# --- W-308: read-only resident health keeps environment failures distinct --",
  "HEALTH_DIR_NATIVE=\"$(native_path \"$SELF_DIR/../driver/src/scripts\")\"",
  "bun -e '",
  "  import { mkdirSync, readFileSync, writeFileSync } from \"node:fs\";",
  "  import { join, resolve } from \"node:path\";",
  "  import { pathToFileURL } from \"node:url\";",
  "  const health = await import(pathToFileURL(join(process.argv[1], \"resident_process_health.ts\")).href);",
  "  const healthSource = readFileSync(join(process.argv[1], \"resident_process_health.ts\"), \"utf8\");",
  "  if (/Bun\\.spawnSync|resolveCommand\\(|runProbe\\(/.test(healthSource)) throw new Error(\"read-only classifier retained an active executable probe\");",
  "  const sessions = await import(pathToFileURL(join(process.argv[1], \"provider_session.ts\")).href);",
  "  const project = resolve(process.argv[2]);",
  "  const runtime = join(project, \"__garelier\", \"tpm\", \"runtime\");",
  "  mkdirSync(join(runtime, \"status_web\"), { recursive: true });",
  "  mkdirSync(join(runtime, \"driver\"), { recursive: true });",
  "  mkdirSync(join(runtime, \"merge_gate\", \"locks\"), { recursive: true });",
  "  writeFileSync(join(runtime, \"status_web\", \"status_web.json\"), JSON.stringify({ pid: 41, owner: \"operator\", provenance: \"operator-owned\" }));",
  "  writeFileSync(join(runtime, \"driver\", \"fleet_watch.lock\"), JSON.stringify({ pid: 77, owner: \"operator\", provenance: \"operator-owned\" }));",
  "  writeFileSync(join(runtime, \"merge_gate\", \"locks\", \"active.lock\"), JSON.stringify({ pid: 88, owner: \"operator\", provenance: \"operator-owned\" }));",
  "  const markers = health.inspectResidentMarkers({ projectRoot: project, pmId: \"tpm\", isPidAlive: (pid) => pid === 77 });",
  "  if (markers.map((row) => row.component).join(\",\") !== \"status_web,fleet_watch,long_job_broker,merge_gate\") throw new Error(\"resident denominator drift: \" + JSON.stringify(markers));",
  "  const staleStatus = markers.find((row) => row.component === \"status_web\");",
  "  const liveFleet = markers.find((row) => row.component === \"fleet_watch\");",
  "  if (staleStatus?.health !== \"unhealthy\" || staleStatus.contamination !== \"not_proven\" || !staleStatus.reason.includes(\"stale pidfile\")) throw new Error(\"stale Status Web was misclassified\");",
  "  if (liveFleet?.health !== \"healthy\" || liveFleet.owner !== \"operator\") throw new Error(\"live correct owner was not healthy\");",
  "  const ok = (stdout = \"\") => ({ available: true, exitCode: 0, stdout, stderr: \"\" });",
  "  const failed = (stderr) => ({ available: true, exitCode: 1, stdout: \"\", stderr });",
  "  const blocked = health.evaluateResidentPreflight({ direct: ok(\"rustc\"), mediated: failed(\"daemon denied\"), markers: [] });",
  "  if (blocked.status !== \"ENVIRONMENT_BLOCKED\" || blocked.exitCode === 1) throw new Error(\"mediated failure collapsed into RED\");",
  "  const red = health.evaluateResidentPreflight({ direct: failed(\"compile error\"), mediated: failed(\"compile error\"), markers: [] });",
  "  if (red.status !== \"RED\" || red.exitCode !== 1) throw new Error(\"same code failure was not RED\");",
  "  const responsiveUnknown = health.evaluateResidentPreflight({ direct: ok(\"rustc\"), mediated: ok(\"stats\"), markers: [] });",
  "  if (responsiveUnknown.status === \"PASS\" || responsiveUnknown.components[0]?.health !== \"unverifiable\") throw new Error(\"responsive sccache with unproven launcher provenance became healthy\");",
  "  const unavailable = health.evaluateResidentPreflight({ direct: { available: false, exitCode: null, stdout: \"\", stderr: \"missing\" }, mediated: ok(), markers: [] });",
  "  if (unavailable.status === \"PASS\") throw new Error(\"unverifiable preflight became PASS\");",
  "  const observedMediatorFailure = `sccache: error: failed to execute compile\\nsccache: caused by: Compiler not supported: \"C:\\\\llvm-mingw\\\\bin\\\\clang-21.exe: Permission denied\"`;",
  "  if (health.residentComponentForFailure(\"cargo test --workspace\", observedMediatorFailure) !== \"sccache\") throw new Error(\"machine-config Cargo mediator evidence was not bound\");",
  "  if (health.residentComponentForFailure(\"RUSTC_WRAPPER=sccache cargo test --workspace\", \"error[E0308]: mismatched types\") !== null) throw new Error(\"explicit wrapper bypassed the evidence requirement\");",
  "  if (health.residentComponentForFailure(\"RUSTC_WRAPPER=sccache cargo test --workspace\", observedMediatorFailure) !== \"sccache\") throw new Error(\"explicit wrapper evidence was not bound\");",
  "  if (health.residentComponentForFailure(\"cargo test --workspace\", \"sccache: error: failed to execute compile\\nerror[E0308]: mismatched types\") !== null) throw new Error(\"Cargo code failure without environment discriminator was bound\");",
  "  if (health.residentComponentForFailure(\"cargo test --workspace\", \"Permission denied\") !== null) throw new Error(\"Cargo environment text without sccache mediator evidence was bound\");",
  "  if (health.residentComponentForFailure(\"bun test\", observedMediatorFailure) !== null) throw new Error(\"non-Rust failure inherited unrelated sccache evidence\");",
  "  if (health.residentComponentForFailure(\"cargo test --workspace\", \"sccache: error: failed to execute compile\\nsccache: caused by: Compiler not supported: clang-21.exe: Permission denied\") !== null) throw new Error(\"compiler denial without absolute compiler path was bound\");",
  "  if (health.residentComponentForFailure(\"cargo test --workspace\", \"sccache: error: failed to execute compile\\nsccache: caused by: failed to connect to server: Connection refused\") !== null) throw new Error(\"broad connection failure became a compiler-path exemption\");",
  "  if (health.residentComponentForFailure(\"cargo test --workspace; false\", observedMediatorFailure) !== null) throw new Error(\"compound failure was attributed to an unproven Rust segment\");",
  "  if (health.residentComponentForFailure(\"sccache --show-stats; false\", observedMediatorFailure) !== null) throw new Error(\"compound control command was unconditionally bound\");",
  "  if (health.residentComponentForFailure(\"sccache --show-stats\", \"\") !== \"sccache\") throw new Error(\"direct sccache control command lost unconditional binding\");",
  "  const capturedBlocked = health.runResidentProcessPreflight({ projectRoot: project, pmId: \"tpm\", command: \"cargo test --workspace\", failureOutput: observedMediatorFailure, directObservation: ok(\"rustc -Vv\") });",
  "  if (capturedBlocked.status !== \"ENVIRONMENT_BLOCKED\" || capturedBlocked.relevantComponent !== \"sccache\") throw new Error(\"exact captured compiler boundary was not environment-blocked: \" + JSON.stringify(capturedBlocked));",
  "  const ordinaryRustRed = health.runResidentProcessPreflight({ projectRoot: project, pmId: \"tpm\", command: \"cargo test --workspace\", failureOutput: \"error[E0308]: mismatched types\", directObservation: ok(\"rustc -Vv\") });",
  "  if (ordinaryRustRed.status !== \"RED\" || ordinaryRustRed.relevantComponent !== null) throw new Error(\"ordinary Rust code failure was not RED: \" + JSON.stringify(ordinaryRustRed));",
  "  writeFileSync(join(runtime, \"status_web\", \"status_web.json\"), JSON.stringify({ pid: 77 }));",
  "  const missingOwner = health.inspectResidentMarkers({ projectRoot: project, pmId: \"tpm\", isPidAlive: () => true }).find((row) => row.component === \"status_web\");",
  "  if (missingOwner?.health !== \"unverifiable\" || missingOwner.owner !== \"unknown\") throw new Error(\"missing daemon owner/provenance became healthy\");",
  "  const unknownPid = health.inspectResidentMarkers({ projectRoot: project, pmId: \"tpm\", isPidAlive: () => ({ alive: true, via: \"unknown\" }) });",
  "  if (unknownPid.some((row) => row.pid !== null && row.health !== \"unverifiable\")) throw new Error(\"unknown PID liveness became healthy\");",
  "  const roleRoots = [",
  "    join(project, \"__garelier\", \"tpm\", \"_crew\", \"dispatch16\", \"checkout\"),",
  "    join(project, \"__garelier\", \"tpm\", \"_crew\", \"dispatch16\"),",
  "    join(project, \"__garelier\", \"tpm\", \"_crew\", \"workers\", \"12\"),",
  "    join(project, \"__garelier\", \"tpm\", \"_crew\", \"smiths\", \"3\"),",
  "    join(project, \"__garelier\", \"tpm\", \"_crew\", \"librarians\", \"4\"),",
  "    join(project, \"__garelier\", \"tpm\", \"_crew\", \"artisan\"),",
  "  ];",
  "  for (const cwd of roleRoots) if (!health.isRoleSeat({}, cwd)) throw new Error(\"role root was not recognized: \" + cwd);",
  "  const operatorRoots = [",
  "    join(project, \"__garelier\", \"tpm\", \"_crew\", \"scouts\", \"5\"),",
  "    join(project, \"__garelier\", \"tpm\", \"_crew\", \"pm\"),",
  "    join(project, \"workers\", \"12\"),",
  "  ];",
  "  for (const cwd of operatorRoots) if (health.isRoleSeat({}, cwd)) throw new Error(\"operator/non-role path was misclassified: \" + cwd);",
  "  const providerEnv = sessions.providerChildEnv(\"claude-code\", \"/bin/bash\", { ANTHROPIC_API_KEY: \"fixture-auth\", rustc_wrapper: \"sccache\", Rustc_Workspace_Wrapper: \"sccache\" });",
  "  if (providerEnv.ANTHROPIC_API_KEY !== \"fixture-auth\") throw new Error(\"provider auth env was dropped\");",
  "  if (providerEnv.GARELIER_ROLE_SEAT !== \"1\" || providerEnv.RUSTC_WRAPPER !== \"\" || providerEnv.RUSTC_WORKSPACE_WRAPPER !== \"\") throw new Error(\"Claude-dispatched role no-daemon env drift\");",
  "  if (Object.keys(providerEnv).some((key) => key.toUpperCase() === \"RUSTC_WRAPPER\" && key !== \"RUSTC_WRAPPER\" || key.toUpperCase() === \"RUSTC_WORKSPACE_WRAPPER\" && key !== \"RUSTC_WORKSPACE_WRAPPER\")) throw new Error(\"non-canonical Rust wrapper key survived\");",
  "  if (/taskkill \\/IM|pkill|Stop-Process/i.test(JSON.stringify({ markers, blocked }))) throw new Error(\"preflight generated an indiscriminate kill\");",
  "' \"$HEALTH_DIR_NATIVE\" \"$TMP/health-fixture\" || fail \"resident process health fixture failed\"",
  "",
  "for resident_cmd in \\",
  "  \"status_web_cli.ts start --project $PROJECT --pm-id tpm\" \\",
  "  \"../status_web.ts --project $PROJECT --pm-id tpm\" \\",
  "  \"fleet_watch.ts --project $PROJECT --pm-id tpm --max-sec 1\" \\",
  "  \"long_job_runner.ts broker --root $TMP/role-ledger\"; do",
  "  resident_script=\"${resident_cmd%% *}\"",
  "  resident_args=\"${resident_cmd#* }\"",
  "  set +e",
  "  GARELIER_ROLE_SEAT=1 bun \"$SELF_DIR/../driver/src/scripts/$resident_script\" $resident_args >\"$TMP/resident.out\" 2>\"$TMP/resident.err\"",
  "  RESIDENT_RC=$?",
  "  set -e",
  "  [ \"$RESIDENT_RC\" -eq 3 ] || fail \"role resident start did not fail closed (rc=$RESIDENT_RC cmd=$resident_cmd)\"",
  "  grep -q 'ENVIRONMENT BLOCKED' \"$TMP/resident.err\" || fail \"role resident refusal lacked environment verdict: $resident_cmd\"",
  "done",
  "[ ! -e \"$TMP/role-ledger/.broker.lock\" ] || fail \"refused role broker created a lock\"",
  "set +e",
  "( cd \"$CONTAINER\" && env -u GARELIER_ROLE_SEAT bun \"$SELF_DIR/../driver/src/scripts/status_web_cli.ts\" start --project \"$PROJECT\" --pm-id tpm ) >\"$TMP/parent.out\" 2>\"$TMP/parent.err\"",
  "PARENT_RC=$?",
  "set -e",
  "[ \"$PARENT_RC\" -eq 3 ] || fail \"dispatch-container parent bypassed role resident refusal (rc=$PARENT_RC)\"",
  "grep -q 'ENVIRONMENT BLOCKED' \"$TMP/parent.err\" || fail \"dispatch-container parent refusal lacked environment verdict\"",
  "",
  "echo \"dispatch_codex_provider.test: OK\"",
].join("\n") + "\n";

test("dispatch_codex_provider shell parity oracle", () => {
  const result = runShellOracle(shellScript, import.meta.path);
  const stdout = result.stdout?.toString() ?? "";
  const stderr = result.stderr?.toString() ?? "";
  expect(result.exitCode, stdout + stderr).toBe(0);
}, 240_000);
