import { expect, test } from "bun:test";
import { runShellOracle } from "../driver/src/scripts/shell_oracle_test_runner.ts";

// W-111: Bun registers this parity oracle. Its existing shell assertions remain
// verbatim while every Garelier CLI under test is invoked directly with Bun.
const shellScript = [
  "#!/usr/bin/env bash",
  "#",
  "# merge_gate_robustness.test.ts — pins the W-076 / W-077 merge-gate hardening.",
  "#",
  "# Drives the REAL merge-gate.ts SYNCHRONOUSLY against a hand-built request JSON",
  "# (the gate runs to completion in-process and writes its result JSON), so each",
  "# case exercises the exact production code path with a trivial quality gate.",
  "#",
  "# Cases (task contract):",
  "#   (i)   mid-gate third-party commit that ALREADY landed the merge intact",
  "#         (2-parent merge including the branch tip) -> completed_externally",
  "#         success + absorbed_by recorded (W-076.2).",
  "#   (ii)  mid-gate commit whose content does NOT match the branch -> the",
  "#         fail-closed W-066 abort is preserved (W-076.2 negative control).",
  "#   (iii) the primary checkout carries branch-IDENTICAL dirt that blocks",
  "#         `git checkout studio` -> lossless self-heal, gate continues to success",
  "#         (W-077.2).",
  "#   (iv)  the primary checkout carries NON-identical dirt -> no heal, fail-closed",
  "#         (W-077.2 negative control).",
  "#   (v)   a SECOND runner of the same request (active.lock already held by a",
  "#         different pid) exits immediately without staging (W-076.3).",
  "#   (vi)  a failing mediated sccache command with a passing direct rustc",
  "#         baseline terminates as environment_blocked with resident evidence;",
  "#         Status Web preserves that terminal state.",
  "#   (vii) an unrelated stale resident marker cannot mask an ordinary project",
  "#         command RED; responsive-unproven sccache stays unverifiable.",
  "#   (viii) missing policy config is a machine-readable required/BLOCKED refusal",
  "#         from the real merge-gate caller, never a skipped backstop (W-297).",
  "#",
  "# Self-contained: `bun test merge_gate_robustness.test.ts` or via ci.ts. Needs bun +",
  "# git + a POSIX shell. Exits 0 only if every case holds.",
  "set -uo pipefail",
  "",
  "SELF_DIR=\"$(cd \"$(dirname \"$0\")\" && pwd)\"",
  "MG=\"$SELF_DIR/../driver/src/scripts/merge-gate.ts\"",
  "ROLE_BINDING=\"$(cygpath -m \"$SELF_DIR/../driver/src/dispatch/role_binding.ts\" 2>/dev/null || printf '%s' \"$SELF_DIR/../driver/src/dispatch/role_binding.ts\")\"",
  "KNOWLEDGE_BINDING=\"$(cygpath -m \"$SELF_DIR/../driver/src/dispatch/knowledge_binding.ts\" 2>/dev/null || printf '%s' \"$SELF_DIR/../driver/src/dispatch/knowledge_binding.ts\")\"",
  "[ -f \"$MG\" ] || { echo \"merge_gate_robustness.test: cannot find merge-gate.ts next to me\" >&2; exit 1; }",
  "command -v bun >/dev/null 2>&1 || { echo \"merge_gate_robustness.test: bun required (driver runtime)\" >&2; exit 1; }",
  "",
  "fail() { echo \"  FAIL: $*\" >&2; exit 1; }",
  "",
  "ORIG_CWD=\"$(pwd -P)\"",
  "RUN_CWD=\"$(mktemp -d)\"; cd \"$RUN_CWD\"",
  "TMP=\"\"",
  "cleanup() { cd / 2>/dev/null || true; [ -n \"$TMP\" ] && rm -rf \"$TMP\" 2>/dev/null || true; rm -rf \"$RUN_CWD\" 2>/dev/null || true; }",
  "trap cleanup EXIT",
  "",
  "STUDIO=\"garelier/main/tpm/studio\"",
  "",
  "# mk <slug> <base_file_mode> — build a fixture repo. base_file_mode:",
  "#   newfile : the workbench adds <slug>.txt (studio == main, no divergence)",
  "#   basemod : studio diverges from main on base.txt, workbench then sets it to",
  "#             \"feat\" (drives the checkout-blocking dirty-file cases iii/iv)",
  "# Sets TMP (posix) + DT (native) + WB (workbench branch) + REQDIR/RESDIR/LOGDIR.",
  "mk() {",
  "  local slug=\"$1\" mode=\"$2\"",
  "  TMP=\"$(mktemp -d)\"; DT=\"$(cygpath -m \"$TMP\" 2>/dev/null || printf '%s' \"$TMP\")\"",
  "  WB=\"garelier/main/tpm/workbench/#1/$slug\"",
  "  (",
  "    cd \"$TMP\"",
  "    git init -q -b main; git config user.email ci@ci; git config user.name t",
  "    echo base > base.txt; git add -A; git commit -q -m init",
  "    git branch \"$STUDIO\" main",
  "    if [ \"$mode\" = basemod ]; then",
  "      # studio diverges from main so a dirty base.txt blocks `checkout studio`.",
  "      git checkout -q \"$STUDIO\"",
  "      echo studio-version > base.txt; git add -A; git commit -q -m \"studio diverge\"",
  "      git checkout -q main",
  "    fi",
  "    git worktree add -q -b \"$WB\" wb \"$STUDIO\"",
  "    (",
  "      cd wb",
  "      if [ \"$mode\" = basemod ]; then echo feat > base.txt; else echo feat > \"$slug.txt\"; fi",
  "      git add -A; git commit -q -m \"feat $slug\"",
  "    )",
  "    git worktree remove wb",
  "    mkdir -p \"__garelier/tpm/_crew/pm\" \"__garelier/tpm/runtime/merge_gate/requests\"",
  "    printf '[project]\\nname = \"t\"\\n\\n[branches]\\ntarget = \"main\"\\nintegration = \"%s\"\\n' \"$STUDIO\" \\",
  "      > \"__garelier/tpm/_crew/pm/setup_config.toml\"",
  "  )",
  "  bun -e 'import { mkdirSync, writeFileSync } from \"node:fs\"; import { join } from \"node:path\"; import { pathToFileURL } from \"node:url\"; import { spawnSync } from \"node:child_process\"; const [root, branch, studio, slug, rolePath, knowledgePath] = process.argv.slice(1); const [{ acknowledgeRoleLaunch, bindingReference, closeRoleBinding, issueRoleAuthorization, roleExecutionIdentityForBranch }, { resolveRoleKnowledgeBinding }] = await Promise.all([rolePath, knowledgePath].map((path) => import(pathToFileURL(path).href))); const fixture = join(root, \"__garelier\", \"tpm\", \"runtime\", \"fixtures\", slug); const assignment = join(fixture, \"assignment.md\"); const prompt = join(fixture, \"prompt.md\"); const report = join(fixture, \"report.md\"); const ledger = join(fixture, \"instructions.md\"); mkdirSync(fixture, { recursive: true }); writeFileSync(assignment, `# ${slug} fixture\\n`); writeFileSync(prompt, `Exercise ${slug}.\\n`); writeFileSync(report, `# ${slug} report\\n`); writeFileSync(ledger, `+++\\n[ledger]\\n\\n[[instruction]]\\nid = \"I1\"\\nmessage = \"${slug} fixture\"\\nchecked = true\\nconsumed = \"aggregate\"\\n+++\\n\\n# Instruction ledger\\n`); const rev = (ref) => spawnSync(\"git\", [\"-C\", root, \"rev-parse\", ref], { encoding: \"utf8\" }).stdout.trim(); const identity = roleExecutionIdentityForBranch(branch); const authorization = issueRoleAuthorization({ project_root: root, pm_id: \"tpm\", identity, role: \"worker\", carabiner: \"implementation\", item: { work_id: \"W-076\", revision: slug, session_id: `cs-${slug}`, authority_path: assignment }, assignment_path: assignment, prompt_path: prompt, initial_instructions_path: ledger, routing: { provider: \"attended-agent\", model: \"test-model\", effort: \"medium\", source: \"aggregate\" }, lens: { ref: null, source: \"none\", registry_path: null, pack_path: null }, knowledge: resolveRoleKnowledgeBinding({ projectRoot: root, pmId: \"tpm\", role: \"worker\", required: [] }), integration: { ref: studio, base_sha: rev(studio) }, issuer: { role: \"dock\", id: \"aggregate\" } }); acknowledgeRoleLaunch({ project_root: root, pm_id: \"tpm\", identity, generation: authorization.core.generation, expect_digest: authorization.core_digest, transport: \"attended-agent\", provider_session_id: `agent-${slug}`, success_evidence: \"aggregate launch\", writer: { role: \"attended-parent\", id: \"aggregate\" } }); closeRoleBinding({ project_root: root, pm_id: \"tpm\", identity, generation: authorization.core.generation, expect_digest: authorization.core_digest, candidate_sha: rev(branch), report_path: report, ledger_path: ledger, writer: { role: \"admission-controller\", id: \"aggregate\" } }); writeFileSync(join(root, \"role-evidence.json\"), `${JSON.stringify({ role_binding: bindingReference(authorization), role_report_path: report })}\\n`);' \"$DT\" \"$WB\" \"$STUDIO\" \"$slug\" \"$ROLE_BINDING\" \"$KNOWLEDGE_BINDING\"",
  "  REQDIR=\"$TMP/__garelier/tpm/runtime/merge_gate/requests\"",
  "  RESDIR=\"$TMP/__garelier/tpm/runtime/merge_gate/results\"",
  "  LOGDIR=\"$TMP/__garelier/tpm/runtime/merge_gate/logs\"",
  "  LOCKDIR=\"$TMP/__garelier/tpm/runtime/merge_gate/locks\"",
  "}",
  "",
  "# write_request <stem> <quality_gate_cmd> — emit the request JSON with the",
  "# canonical role evidence created by mk(). request_id == stem (matches the",
  "# filename, as the driver does) so clear_lock_if_mine works.",
  "write_request() {",
  "  local stem=\"$1\" cmd=\"$2\"",
  "  bun -e 'import { readFileSync, writeFileSync } from \"node:fs\"; const [evidencePath, out, stem, branch, studio, root, cmd] = process.argv.slice(1); const evidence = JSON.parse(readFileSync(evidencePath, \"utf8\")); writeFileSync(out, `${JSON.stringify({ request_id: stem, workbench_branch: branch, studio_branch: studio, merge_message: `merge ${stem}`, target_root: root, quality_gate_commands: [cmd], ...evidence }, null, 2)}\\n`);' \\",
  "    \"$TMP/role-evidence.json\" \"$REQDIR/$stem.json\" \"$stem\" \"$WB\" \"$STUDIO\" \"$DT\" \"$cmd\"",
  "}",
  "",
  "studio_head() { git -C \"$TMP\" rev-parse \"$STUDIO\" 2>/dev/null; }",
  "res_has() { grep -qF \"$2\" \"$RESDIR/$1.json\" 2>/dev/null; }",
  "",
  "# ── (i) completed_externally: a mid-gate merge commit absorbs the staged merge ──",
  "# The quality-gate command commits WHILE the gate's `git merge --no-commit` is",
  "# staged (MERGE_HEAD present) → a 2-parent merge whose parent is the branch tip.",
  "# Step 5 sees HEAD moved + MERGE_HEAD gone and must report completed_externally",
  "# success, not a false abort.",
  "mk absorb-intact newfile",
  "cat > \"$TMP/absorb-gate\" <<EOF",
  "#!/usr/bin/env bash",
  "cd \"$DT\"",
  "git commit -m \"PM docs commit that absorbs the staged merge\" >/dev/null 2>&1",
  "exit 0",
  "EOF",
  "write_request abs1 \"bash '$TMP/absorb-gate'\"",
  "set +e; bun \"$MG\" \"$REQDIR/abs1.json\" >/dev/null 2>&1; set -e",
  "[ -f \"$RESDIR/abs1.json\" ] || fail \"(i) no result JSON written\"",
  "res_has abs1 '\"status\": \"success\"' || fail \"(i) expected status=success (completed_externally). result=$(cat \"$RESDIR/abs1.json\")\"",
  "res_has abs1 '\"completed_externally\": true' || fail \"(i) result lacks completed_externally=true: $(cat \"$RESDIR/abs1.json\")\"",
  "res_has abs1 '\"absorbed_by\":' || fail \"(i) result lacks absorbed_by: $(cat \"$RESDIR/abs1.json\")\"",
  "git -C \"$TMP\" cat-file -e \"$STUDIO:absorb-intact.txt\" 2>/dev/null || fail \"(i) branch content is not on studio\"",
  "echo \"  ok (i) completed_externally success + absorbed_by recorded\"",
  "cleanup; TMP=\"\"",
  "",
  "# ── (ii) negative control: a NON-matching mid-gate commit still fail-closed aborts ─",
  "# The quality-gate aborts the staged merge and lands an UNRELATED commit, so the",
  "# branch content is NOT in studio → absorbed_intact_check fails → W-066 abort.",
  "mk absorb-nomatch newfile",
  "cat > \"$TMP/nomatch-gate\" <<EOF",
  "#!/usr/bin/env bash",
  "cd \"$DT\"",
  "git merge --abort >/dev/null 2>&1",
  "echo docs > unrelated_docs.txt",
  "git add unrelated_docs.txt",
  "git commit -m \"unrelated PM docs (does NOT contain the branch change)\" >/dev/null 2>&1",
  "exit 0",
  "EOF",
  "write_request nm1 \"bash '$TMP/nomatch-gate'\"",
  "set +e; bun \"$MG\" \"$REQDIR/nm1.json\" >/dev/null 2>&1; set -e",
  "[ -f \"$RESDIR/nm1.json\" ] || fail \"(ii) no result JSON written\"",
  "res_has nm1 '\"status\": \"aborted\"' || fail \"(ii) expected status=aborted (fail-closed). result=$(cat \"$RESDIR/nm1.json\")\"",
  "res_has nm1 '\"completed_externally\": true' && fail \"(ii) WRONGLY marked completed_externally on non-matching content: $(cat \"$RESDIR/nm1.json\")\"",
  "if git -C \"$TMP\" cat-file -e \"$STUDIO:absorb-nomatch.txt\" 2>/dev/null; then fail \"(ii) branch content WRONGLY on studio\"; fi",
  "echo \"  ok (ii) non-matching mid-gate commit stays fail-closed aborted\"",
  "cleanup; TMP=\"\"",
  "",
  "# ── (iii) primary branch-identical dirt → lossless self-heal, gate succeeds ──────",
  "mk heal-ok basemod",
  "# Leave base.txt unstaged and identical to the branch (\"feat\") in the primary checkout, on",
  "# main, so `git checkout studio` (studio's base.txt = \"studio-version\") is blocked",
  "# by \"local changes would be overwritten\".",
  "( cd \"$TMP\" && echo feat > base.txt )",
  "write_request heal1 'true'",
  "ERRF=\"$(mktemp)\"",
  "set +e; bun \"$MG\" \"$REQDIR/heal1.json\" >\"$ERRF\" 2>&1; set -e",
  "[ -f \"$RESDIR/heal1.json\" ] || fail \"(iii) no result JSON written. out=$(cat \"$ERRF\")\"",
  "res_has heal1 '\"status\": \"success\"' || fail \"(iii) expected status=success after lossless self-heal. result=$(cat \"$RESDIR/heal1.json\")\"",
  "grep -qF 'lossless-restored' \"$LOGDIR/heal1.log\" 2>/dev/null || fail \"(iii) log lacks the W-077 lossless-restore line: $(cat \"$LOGDIR/heal1.log\" 2>/dev/null)\"",
  "[ \"$(git -C \"$TMP\" show \"$STUDIO:base.txt\" 2>/dev/null)\" = feat ] || fail \"(iii) merge did not land the branch's base.txt=feat onto studio\"",
  "rm -f \"$ERRF\"",
  "echo \"  ok (iii) branch-identical primary dirt lossless-healed, gate succeeded\"",
  "cleanup; TMP=\"\"",
  "",
  "# ── (iv) primary NON-identical dirt → no heal, fail-closed ───────────────────────",
  "mk heal-bad basemod",
  "( cd \"$TMP\" && echo OTHER-DIFFERENT > base.txt )",
  "write_request heal2 'true'",
  "set +e; bun \"$MG\" \"$REQDIR/heal2.json\" >/dev/null 2>&1; set -e",
  "[ -f \"$RESDIR/heal2.json\" ] || fail \"(iv) no result JSON written\"",
  "res_has heal2 '\"status\": \"success\"' && fail \"(iv) WRONGLY succeeded on non-identical primary dirt: $(cat \"$RESDIR/heal2.json\")\"",
  "res_has heal2 '\"status\": \"failed\"' || fail \"(iv) expected status=failed (fail-closed). result=$(cat \"$RESDIR/heal2.json\")\"",
  "grep -qF 'lossless-restored' \"$LOGDIR/heal2.log\" 2>/dev/null && fail \"(iv) WRONGLY ran the lossless restore on non-identical dirt\"",
  "[ \"$(cat \"$TMP/base.txt\")\" = OTHER-DIFFERENT ] || fail \"(iv) non-identical dirty file was NOT preserved (heal must not touch it)\"",
  "echo \"  ok (iv) non-identical primary dirt left untouched, gate failed closed\"",
  "cleanup; TMP=\"\"",
  "",
  "# ── (v) second runner of the same request exits immediately without staging ──────",
  "mk second-runner newfile",
  "mkdir -p \"$LOCKDIR\"",
  "# A pre-existing active.lock for THIS request_id, owned by a different (foreign)",
  "# pid — exactly what a first, still-running runner would have written. The holder",
  "# must be GENUINELY LIVE: a same-request lock held by a DEAD pid is deliberately",
  "# reclaimed (W-175 f), so a bogus dead pid (e.g. 999999) tests the reclaim path,",
  "# not this SECOND-RUNNER path. On Linux `kill 999999 0` == ESRCH (dead), while",
  "# Windows grace-treats an unprovable pid as alive — which is why the bogus pid",
  "# passed on Git Bash but reclaimed on Linux. Use a real background process so the",
  "# holder is alive on both hosts.",
  "sleep 300 & SR_PID=$!",
  "printf '{\\n  \"pid\": %s,\\n  \"request_id\": \"sr1\",\\n  \"request_file\": \"sr1.json\",\\n  \"started_at\": \"x\",\\n  \"target_root\": \"%s\"\\n}\\n' \"$SR_PID\" \"$DT\" > \"$LOCKDIR/active.lock\"",
  "write_request sr1 'true'",
  "BEFORE=\"$(studio_head)\"",
  "set +e; bun \"$MG\" \"$REQDIR/sr1.json\" >/dev/null 2>&1; RC=$?; set -e",
  "kill \"$SR_PID\" 2>/dev/null || true",
  "[ \"$RC\" -eq 0 ] || fail \"(v) second runner exited non-zero ($RC); expected a quiet exit 0\"",
  "[ ! -f \"$RESDIR/sr1.json\" ] || fail \"(v) second runner WROTE a result (should not touch this request): $(cat \"$RESDIR/sr1.json\")\"",
  "[ \"$(studio_head)\" = \"$BEFORE\" ] || fail \"(v) second runner ADVANCED studio (should not stage/merge anything)\"",
  "[ -f \"$REQDIR/sr1.json\" ] || fail \"(v) second runner archived the request (should leave it queued)\"",
  "grep -qF 'SECOND RUNNER' \"$LOGDIR/sr1.log\" 2>/dev/null || fail \"(v) log lacks the SECOND RUNNER diagnostic: $(cat \"$LOGDIR/sr1.log\" 2>/dev/null)\"",
  "echo \"  ok (v) second runner exited immediately, no staging, request left queued\"",
  "cleanup; TMP=\"\"",
  "",
  "# ── (vi) mediated daemon failure → environment_blocked, not code failed ────────",
  "mk resident-blocked newfile",
  "mkdir -p \"$TMP/fakebin\"",
  "EXE_SUFFIX=\"\"; case \"$(uname -s)\" in MINGW*|MSYS*) EXE_SUFFIX=.exe;; esac",
  "cp \"$(type -P true)\" \"$TMP/fakebin/rustc$EXE_SUFFIX\"",
  "cp \"$(type -P false)\" \"$TMP/fakebin/sccache$EXE_SUFFIX\"",
  "chmod +x \"$TMP/fakebin/rustc$EXE_SUFFIX\" \"$TMP/fakebin/sccache$EXE_SUFFIX\"",
  "write_request env1 'sccache --show-stats'",
  "set +e; PATH=\"$TMP/fakebin:$PATH\" bun \"$MG\" \"$REQDIR/env1.json\" >/dev/null 2>&1; set -e",
  "[ -f \"$RESDIR/env1.json\" ] || fail \"(vi) no result JSON written\"",
  "res_has env1 '\"status\": \"environment_blocked\"' || fail \"(vi) mediated failure collapsed into code failed: $(cat \"$RESDIR/env1.json\")\"",
  "res_has env1 '\"resident_process_preflight\": {' || fail \"(vi) result lacks resident-process evidence: $(cat \"$RESDIR/env1.json\")\"",
  "res_has env1 '\"status\":\"ENVIRONMENT_BLOCKED\"' || fail \"(vi) resident evidence lacks classifier verdict: $(cat \"$RESDIR/env1.json\")\"",
  "res_has env1 '\"relevantComponent\":\"sccache\"' || fail \"(vi) failure was not bound to the sccache component: $(cat \"$RESDIR/env1.json\")\"",
  "res_has env1 '\"component\":\"merge_gate\",\"source\":' || fail \"(vi) active-lock component evidence missing: $(cat \"$RESDIR/env1.json\")\"",
  "res_has env1 '\"owner\":\"operator\",\"provenance\":\"operator-owned\"' || fail \"(vi) active-lock owner/provenance missing: $(cat \"$RESDIR/env1.json\")\"",
  "SNAPSHOT_SRC=\"$(cygpath -m \"$SELF_DIR/../driver/src/status_snapshot.ts\" 2>/dev/null || printf '%s' \"$SELF_DIR/../driver/src/status_snapshot.ts\")\"",
  "bun -e 'import { pathToFileURL } from \"node:url\"; const m=await import(pathToFileURL(process.argv[1]).href); const s=m.buildSnapshot(process.argv[2], \"tpm\", null); if(s.mergeGate.state!==\"environment_blocked\") throw new Error(JSON.stringify(s.mergeGate)); if(!s.warnings.some((w)=>w.kind===\"environment_blocked\")) throw new Error(\"environment warning missing\");' \"$SNAPSHOT_SRC\" \"$DT\" \\",
  "  || fail \"(vi) Status Web snapshot collapsed environment_blocked\"",
  "echo \"  ok (vi) mediated failure returned environment_blocked with evidence and Status Web preservation\"",
  "cleanup; TMP=\"\"",
  "",
  "# ── (vii) healthy mediation + project failure → ordinary code failed ───────────",
  "mk resident-code-red newfile",
  "mkdir -p \"$TMP/fakebin\"",
  "EXE_SUFFIX=\"\"; case \"$(uname -s)\" in MINGW*|MSYS*) EXE_SUFFIX=.exe;; esac",
  "cp \"$(type -P true)\" \"$TMP/fakebin/rustc$EXE_SUFFIX\"",
  "cp \"$(type -P true)\" \"$TMP/fakebin/sccache$EXE_SUFFIX\"",
  "chmod +x \"$TMP/fakebin/rustc$EXE_SUFFIX\" \"$TMP/fakebin/sccache$EXE_SUFFIX\"",
  "mkdir -p \"$TMP/__garelier/tpm/runtime/status_web\"",
  "printf '{\"pid\":999999,\"owner\":\"operator\",\"provenance\":\"operator-owned\"}\\n' > \"$TMP/__garelier/tpm/runtime/status_web/status_web.json\"",
  "write_request red1 'false'",
  "set +e; PATH=\"$TMP/fakebin:$PATH\" bun \"$MG\" \"$REQDIR/red1.json\" >/dev/null 2>&1; set -e",
  "[ -f \"$RESDIR/red1.json\" ] || fail \"(vii) no result JSON written\"",
  "res_has red1 '\"status\": \"failed\"' || fail \"(vii) code failure was not ordinary failed: $(cat \"$RESDIR/red1.json\")\"",
  "res_has red1 '\"status\":\"RED\"' || fail \"(vii) unbound resident classifier did not preserve RED: $(cat \"$RESDIR/red1.json\")\"",
  "res_has red1 '\"relevantComponent\":null' || fail \"(vii) ordinary command was spuriously bound to a resident component: $(cat \"$RESDIR/red1.json\")\"",
  "res_has red1 '\"component\":\"sccache\",\"pid\":null,\"owner\":\"unknown\",\"provenance\":\"unrecorded\",\"health\":\"unverifiable\"' || fail \"(vii) responsive-unproven sccache was not unverifiable: $(cat \"$RESDIR/red1.json\")\"",
  "res_has red1 'stale pidfile' || fail \"(vii) stale Status Web evidence missing: $(cat \"$RESDIR/red1.json\")\"",
  "echo \"  ok (vii) unrelated stale marker stayed evidence-only; project command remained failed\"",
  "cleanup; TMP=\"\"",
  "",
  "# ── (viii) missing policy config → machine-readable required/BLOCKED refusal ──",
  "mk policy-config-missing newfile",
  "rm \"$TMP/__garelier/tpm/_crew/pm/setup_config.toml\"",
  "write_request policy1 'true'",
  "BEFORE=\"$(studio_head)\"",
  "set +e; bun \"$MG\" \"$REQDIR/policy1.json\" >/dev/null 2>&1; set -e",
  "[ -f \"$RESDIR/policy1.json\" ] || fail \"(viii) no result JSON written\"",
  "res_has policy1 '\"status\": \"failed\"' || fail \"(viii) expected status=failed. result=$(cat \"$RESDIR/policy1.json\")\"",
  "grep -qF '\"status\":\"BLOCKED\"' \"$LOGDIR/policy1.log\" 2>/dev/null || fail \"(viii) log lacks machine-readable BLOCKED refusal: $(cat \"$LOGDIR/policy1.log\" 2>/dev/null)\"",
  "grep -qF '\"required\":true' \"$LOGDIR/policy1.log\" 2>/dev/null || fail \"(viii) log lacks required=true: $(cat \"$LOGDIR/policy1.log\" 2>/dev/null)\"",
  "grep -qF '\"failure_kind\":\"config\"' \"$LOGDIR/policy1.log\" 2>/dev/null || fail \"(viii) log lacks config failure_kind: $(cat \"$LOGDIR/policy1.log\" 2>/dev/null)\"",
  "grep -qF '\"check\":\"guardian_policy\"' \"$LOGDIR/policy1.log\" 2>/dev/null || fail \"(viii) merge-gate did not surface the Guardian policy backstop: $(cat \"$LOGDIR/policy1.log\" 2>/dev/null)\"",
  "[ \"$(studio_head)\" = \"$BEFORE\" ] || fail \"(viii) studio advanced despite missing policy config\"",
  "echo \"  ok (viii) missing policy config blocked by production caller with machine-readable output\"",
  "cleanup; TMP=\"\"",
  "",
  "echo \"merge_gate_robustness.test: all cases pass (W-076/W-077 hardening + W-297 policy backstop + W-308 resident failure boundary)\"",
].join("\n") + "\n";

test("merge_gate_robustness shell parity oracle", () => {
  const result = runShellOracle(shellScript, import.meta.path);
  const stdout = result.stdout?.toString() ?? "";
  const stderr = result.stderr?.toString() ?? "";
  expect(result.exitCode, stdout + stderr).toBe(0);
}, 240_000);
