import { expect, test } from "bun:test";
import { runShellOracle } from "../driver/src/scripts/shell_oracle_test_runner.ts";

// W-111: Bun registers this parity oracle. Its existing shell assertions remain
// verbatim while every Garelier CLI under test is invoked directly with Bun.
const shellScript = [
  "#!/usr/bin/env bash",
  "#",
  "# merge_land.test.ts — pins the merge_land.ts macro (W-088).",
  "#",
  "# Uses the W-087 dummy-gate rig: a REAL merge gate run, but with a trivial",
  "# quality-gate command (`true` / `false`) standing in for a multi-minute build, so",
  "# the whole submit → wait → cleanup → pull chain is exercised end to end in seconds.",
  "#",
  "#   1. SUCCESS  — gate passes → merge lands, dispatch cleaned up (worktree removed,",
  "#                 branch deleted, report archived), summary status=success, exit 0.",
  "#   2. FAILURE  — gate fails → NOTHING is cleaned up (dispatch + branch survive),",
  "#                 summary status=failed, exit non-zero.",
  "#   3. W-055 guard non-interference — a merged dispatch is cleaned even while a",
  "#      FOREIGN gate (a different slug) holds active.lock; the same cleanup is still",
  "#      REFUSED when the lock names THIS slug (the guard is slug-specific, so",
  "#      merge_land's post-success cleanup is not blocked by a concurrent gate).",
  "#",
  "# Self-contained: run directly (`bun test merge_land.test.ts`) or from ci.ts. Needs",
  "# bun + git + a POSIX shell. Exits 0 only if every case holds.",
  "set -uo pipefail",
  "",
  "ORIG_CWD=\"$(pwd -P)\"",
  "SELF_DIR=\"$(cd \"$(dirname \"$0\")\" && pwd)\"",
  "ML=\"$SELF_DIR/../driver/src/scripts/merge_land.ts\"",
  "CLEANUP=\"$SELF_DIR/../driver/src/scripts/dispatch_cleanup.ts\"",
  "[ -f \"$ML\" ] || { echo \"merge_land.test: cannot find merge_land.ts next to me\" >&2; exit 1; }",
  "",
  "fail() { echo \"  FAIL: $*\" >&2; exit 1; }",
  "GREL=\"__garelier\"",
  "",
  "# W-053: run this whole file from a throwaway scratch cwd, never from the",
  "# invoker's real cwd (target project 実戦 2026-07-12: a literal `$DT/…` dir",
  "# was found sitting in a real project root — every case below already scopes",
  "# its OWN fixture under `mktemp -d` ($TMP/$DT), but the top-level process cwd",
  "# itself was still whatever the invoker launched this script from; any future",
  "# latent bug in $ML/$CLEANUP that resolves a path against cwd instead of its",
  "# --project/--target-root argument would land there). This is pure isolation,",
  "# not a fix for a reproduced leak in the fixtures below (none found on",
  "# inspection — see references/stray-var-dir-leak.md); assert_no_cwd_residue",
  "# below is the self-detecting backstop in case that analysis is ever wrong.",
  "RUN_CWD=\"$(mktemp -d)\"",
  "cd \"$RUN_CWD\"",
  "",
  "# W-053 (c): self-detect a recurrence — fail loudly if anything landed in the",
  "# ORIGINAL invoker cwd (not $RUN_CWD, not a fixture's own $TMP) by the time",
  "# this script exits, success or failure. A literal `$`-prefixed name is the",
  "# specific signature of an unexpanded-variable leak; report it, don't clean it",
  "# silently, so the run stays evidence for triage.",
  "assert_no_cwd_residue() {",
  "  local stray",
  "  stray=\"$(find \"$ORIG_CWD\" -maxdepth 1 -name '$*' 2>/dev/null)\"",
  "  if [ -n \"$stray\" ]; then",
  "    echo \"  FAIL: stray literal \\$VAR dir(s) leaked into invoker cwd $ORIG_CWD:\" >&2",
  "    printf '%s\\n' \"$stray\" >&2",
  "    return 1",
  "  fi",
  "  return 0",
  "}",
  "trap 'rc=$?; rm -rf \"$RUN_CWD\" 2>/dev/null || true; assert_no_cwd_residue || rc=1; exit $rc' EXIT",
  "",
  "# mk_fixture <slug> <id> -> sets TMP (posix) + DT (windows-usable path). A git repo",
  "# with studio + a workbench branch (one commit) + setup_config + a _dispatch<id>",
  "# worktree, ready for a merge gate run.",
  "mk_fixture() {",
  "  local slug=\"$1\" id=\"$2\"",
  "  TMP=\"$(mktemp -d)\"; DT=\"$(cygpath -m \"$TMP\" 2>/dev/null || printf '%s' \"$TMP\")\"",
  "  (",
  "    cd \"$TMP\"",
  "    git init -q -b main; git config user.email ci@ci; git config user.name t",
  "    echo base > base.txt; git add -A; git commit -q -m init",
  "    git branch \"garelier/main/tpm/studio\" main",
  "    git worktree add -q -b \"garelier/main/tpm/workbench/#$id/$slug\" \"wb\" \"garelier/main/tpm/studio\"",
  "    ( cd wb && echo feat > \"$slug.txt\" && git add -A && git commit -q -m \"feat $slug\" )",
  "    git worktree remove wb",
  "    mkdir -p \"__garelier/tpm/_pm\"",
  "    printf '[project]\\nname = \"test\"\\n\\n[branches]\\ntarget = \"main\"\\nintegration = \"garelier/main/tpm/studio\"\\n' \\",
  "      > \"__garelier/tpm/_pm/setup_config.toml\"",
  "    git worktree add -q \"__garelier/tpm/_dispatch$id/checkout\" \"garelier/main/tpm/workbench/#$id/$slug\"",
  "    printf '# Report - #%s %s\\n' \"$id\" \"$slug\" > \"__garelier/tpm/_dispatch$id/report.md\"",
  "    # commit_mode=self (guardian round-3 N1): a real dispatch_prepare-created",
  "    # container always carries context.json; these fixtures simulate a plain",
  "    # (non-proxy) worker dispatch, so the seat-trailer preflight must see self,",
  "    # not treat the container as unresolvable and fail closed.",
  "    printf '{\"routing\":{\"commit_mode\":\"self\"}}\\n' > \"__garelier/tpm/_dispatch$id/context.json\"",
  "  )",
  "}",
  "cleanup_fixture() { cd /; rm -rf \"$TMP\" 2>/dev/null || true; }",
  "",
  "# add_dispatch <slug> <id> — add ANOTHER workbench branch + _dispatch<id> to the",
  "# CURRENT $TMP repo (created by mk_fixture), so one fixture can host several",
  "# dispatches for a batch-land test.",
  "add_dispatch() {",
  "  local slug=\"$1\" id=\"$2\"",
  "  (",
  "    cd \"$TMP\"",
  "    git worktree add -q -b \"garelier/main/tpm/workbench/#$id/$slug\" \"wb$id\" \"garelier/main/tpm/studio\"",
  "    ( cd \"wb$id\" && echo feat > \"$slug.txt\" && git add -A && git commit -q -m \"feat $slug\" )",
  "    git worktree remove \"wb$id\"",
  "    git worktree add -q \"__garelier/tpm/_dispatch$id/checkout\" \"garelier/main/tpm/workbench/#$id/$slug\"",
  "    printf '# Report - #%s %s\\n' \"$id\" \"$slug\" > \"__garelier/tpm/_dispatch$id/report.md\"",
  "    printf '{\"routing\":{\"commit_mode\":\"self\"}}\\n' > \"__garelier/tpm/_dispatch$id/context.json\"",
  "  )",
  "}",
  "",
  "# mk_fixture_lock <slug> <id> <relpath> — like mk_fixture, but the workbench adds",
  "# <relpath> (to drive the merge gate's data-only classification) and the config",
  "# declares the W-031 data-only fast path + the heavy_compile lock, so the W-024",
  "# gate_mode→lock-skip behavior can be observed end to end.",
  "mk_fixture_lock() {",
  "  local slug=\"$1\" id=\"$2\" rel=\"$3\"",
  "  TMP=\"$(mktemp -d)\"; DT=\"$(cygpath -m \"$TMP\" 2>/dev/null || printf '%s' \"$TMP\")\"",
  "  (",
  "    cd \"$TMP\"",
  "    git init -q -b main; git config user.email ci@ci; git config user.name t",
  "    echo base > base.txt; git add -A; git commit -q -m init",
  "    git branch \"garelier/main/tpm/studio\" main",
  "    git worktree add -q -b \"garelier/main/tpm/workbench/#$id/$slug\" \"wb\" \"garelier/main/tpm/studio\"",
  "    ( cd wb && mkdir -p \"$(dirname \"$rel\")\" && echo feat > \"$rel\" && git add -A && git commit -q -m \"feat $slug\" )",
  "    git worktree remove wb",
  "    mkdir -p \"__garelier/tpm/_pm\"",
  "    printf '[project]\\nname = \"test\"\\n\\n[branches]\\ntarget = \"main\"\\nintegration = \"garelier/main/tpm/studio\"\\n\\n[heavy_compile]\\nenabled = true\\nmax_concurrent = 1\\n\\n[merge_gate]\\ndata_only_paths = [\"docs/**\"]\\ndata_only_commands = [\"true\"]\\n' \\",
  "      > \"__garelier/tpm/_pm/setup_config.toml\"",
  "    git worktree add -q \"__garelier/tpm/_dispatch$id/checkout\" \"garelier/main/tpm/workbench/#$id/$slug\"",
  "    printf '# Report - #%s %s\\n' \"$id\" \"$slug\" > \"__garelier/tpm/_dispatch$id/report.md\"",
  "    printf '{\"routing\":{\"commit_mode\":\"self\"}}\\n' > \"__garelier/tpm/_dispatch$id/context.json\"",
  "  )",
  "}",
  "HEAVY_LOCK_REL=\"__garelier/tpm/runtime/locks/heavy_compile\"",
  "",
  "# ── 1. SUCCESS ────────────────────────────────────────────────────────────────",
  "mk_fixture land-ok 1",
  "set +e",
  "OUT=\"$(bun \"$ML\" --project \"$DT\" --target-root \"$DT\" --pm-id tpm \\",
  "  --branch \"garelier/main/tpm/workbench/#1/land-ok\" --guardian PASS \\",
  "  --quality-gate 'true' --no-pull --max-wait 90 --poll-interval 2 2>/dev/null)\"",
  "RC=$?",
  "set -e",
  "[ \"$RC\" -eq 0 ] || fail \"success case exit was $RC (expected 0). summary=$OUT\"",
  "echo \"$OUT\" | grep -q '\"status\":\"success\"' || fail \"success summary lacks status=success: $OUT\"",
  "echo \"$OUT\" | grep -q '\"cleanup_status\":\"success\"' || fail \"success summary lacks cleanup_status=success: $OUT\"",
  "echo \"$OUT\" | grep -q '\"branch_deleted\":true' || fail \"success summary lacks branch_deleted=true: $OUT\"",
  "[ ! -e \"$TMP/__garelier/tpm/_dispatch1\" ] || fail \"success case did not remove the dispatch container\"",
  "[ -z \"$(git -C \"$TMP\" branch --list '*workbench*')\" ] || fail \"success case did not delete the workbench branch\"",
  "git -C \"$TMP\" cat-file -e garelier/main/tpm/studio:land-ok.txt 2>/dev/null || fail \"success case did not land the merge onto studio\"",
  "cleanup_fixture",
  "",
  "# ── 2. FAILURE ────────────────────────────────────────────────────────────────",
  "mk_fixture land-fail 2",
  "set +e",
  "OUT=\"$(bun \"$ML\" --project \"$DT\" --target-root \"$DT\" --pm-id tpm \\",
  "  --branch \"garelier/main/tpm/workbench/#2/land-fail\" --guardian PASS \\",
  "  --quality-gate 'false' --no-pull --max-wait 90 --poll-interval 2 2>/dev/null)\"",
  "RC=$?",
  "set -e",
  "[ \"$RC\" -ne 0 ] || fail \"failure case exit was 0 (expected non-zero). summary=$OUT\"",
  "echo \"$OUT\" | grep -q '\"status\":\"failed\"' || fail \"failure summary lacks status=failed: $OUT\"",
  "echo \"$OUT\" | grep -q '\"cleaned_up\":false' || fail \"failure summary lacks cleaned_up=false: $OUT\"",
  "[ -e \"$TMP/__garelier/tpm/_dispatch2\" ] || fail \"failure case WRONGLY removed the dispatch container\"",
  "[ -n \"$(git -C \"$TMP\" branch --list '*workbench*')\" ] || fail \"failure case WRONGLY deleted the workbench branch\"",
  "cleanup_fixture",
  "",
  "# ── 3. W-055 guard non-interference ───────────────────────────────────────────",
  "# A dispatch whose branch is already merged (FF into studio). A FOREIGN active.lock",
  "# (different slug) must NOT block its cleanup; the SAME-slug lock still must.",
  "mk_fixture guard-ok 3",
  "# Fast-forward the workbench into studio so the branch is a confirmed ancestor",
  "# (merge_status=merged) without running the gate.",
  "git -C \"$TMP\" branch -f \"garelier/main/tpm/studio\" \"garelier/main/tpm/workbench/#3/guard-ok\"",
  "LOCK_DIR=\"$TMP/__garelier/tpm/runtime/merge_gate/locks\"",
  "mkdir -p \"$LOCK_DIR\"",
  "# (a) FOREIGN lock: names a DIFFERENT slug → guard must not fire → cleanup succeeds.",
  "printf '{\"pid\":999999,\"request_id\":\"other\",\"request_file\":\"other.json\",\"started_at\":\"x\",\"target_root\":\"%s\"}\\n' \"$DT\" \\",
  "  > \"$LOCK_DIR/active.lock\"",
  "set +e",
  "COUT=\"$(bun \"$CLEANUP\" --project \"$DT\" --target-root \"$DT\" --pm-id tpm --id 3 --delete-branch 2>/dev/null)\"",
  "CRC=$?",
  "set -e",
  "[ \"$CRC\" -eq 0 ] || fail \"guard case: cleanup refused with a FOREIGN active.lock (exit $CRC) — W-055 guard wrongly interfered. out=$COUT\"",
  "[ -z \"$(git -C \"$TMP\" branch --list '*workbench*')\" ] || fail \"guard case: branch not deleted despite merged + foreign lock\"",
  "cleanup_fixture",
  "",
  "# (b) Negative control: a SAME-slug lock must still REFUSE (guard is real, only",
  "# slug-specific). Fresh fixture (the previous one is cleaned).",
  "mk_fixture guard-block 4",
  "git -C \"$TMP\" branch -f \"garelier/main/tpm/studio\" \"garelier/main/tpm/workbench/#4/guard-block\"",
  "LOCK_DIR=\"$TMP/__garelier/tpm/runtime/merge_gate/locks\"",
  "mkdir -p \"$LOCK_DIR\"",
  "printf '{\"pid\":999999,\"request_id\":\"x-guard-block\",\"request_file\":\"x-guard-block.json\",\"started_at\":\"x\",\"target_root\":\"%s\"}\\n' \"$DT\" \\",
  "  > \"$LOCK_DIR/active.lock\"",
  "set +e",
  "COUT=\"$(bun \"$CLEANUP\" --project \"$DT\" --target-root \"$DT\" --pm-id tpm --id 4 --delete-branch 2>/dev/null)\"",
  "CRC=$?",
  "set -e",
  "[ \"$CRC\" -eq 3 ] || fail \"guard case (negative): cleanup with a SAME-slug lock exited $CRC (expected 3 REFUSE) — the W-055 guard is not firing. out=$COUT\"",
  "[ -n \"$(git -C \"$TMP\" branch --list '*workbench*')\" ] || fail \"guard case (negative): branch was deleted despite the same-slug lock\"",
  "cleanup_fixture",
  "",
  "# ── W-093 --close-row cases ─────────────────────────────────────────────────────",
  "# The gate leaves the primary checkout ON studio (it merges there), so the backlog",
  "# the close step strikes must live on studio. Seed it there, then return to main so",
  "# the gate's own `checkout studio` starts from a clean tree. The W-100 decoy row",
  "# MENTIONS W-093 in a later column — it must survive (first-cell match only).",
  "BL_REL=\"$GREL/tpm/control/project_dashboard/backlog.md\"",
  "seed_backlog() {",
  "  git -C \"$TMP\" checkout -q \"garelier/main/tpm/studio\"",
  "  mkdir -p \"$TMP/$GREL/tpm/control/project_dashboard\"",
  "  cat > \"$TMP/$GREL/tpm/control/project_dashboard/backlog.md\" <<'BL'",
  "# Backlog",
  "",
  "| ID | Type | Status | Detail |",
  "| --- | --- | --- | --- |",
  "| W-093 | feature | ready | merge_land --close-row <id> |",
  "| W-100 | bug | ready | follow-up mentioning W-093 in a later column |",
  "BL",
  "  # Stage ONLY the backlog — `add -A` would try to embed the _dispatch worktree.",
  "  git -C \"$TMP\" add -- \"$BL_REL\"",
  "  git -C \"$TMP\" commit -q -m \"seed backlog\"",
  "  git -C \"$TMP\" checkout -q main",
  "}",
  "",
  "# ── 4. SUCCESS + --close-row ────────────────────────────────────────────────────",
  "# Gate passes → merge lands → the W-093 row is struck and committed with the",
  "# supplied trailer; the W-100 decoy (mentions W-093) is untouched.",
  "mk_fixture land-close 5",
  "seed_backlog",
  "set +e",
  "OUT=\"$(bun \"$ML\" --project \"$DT\" --target-root \"$DT\" --pm-id tpm \\",
  "  --branch \"garelier/main/tpm/workbench/#5/land-close\" --guardian PASS \\",
  "  --quality-gate 'true' --no-pull --max-wait 90 --poll-interval 2 \\",
  "  --close-row W-093 --close-trailer 'Garelier: tpm pm-direct W-082' 2>/dev/null)\"",
  "RC=$?",
  "set -e",
  "[ \"$RC\" -eq 0 ] || fail \"close case exit was $RC (expected 0). summary=$OUT\"",
  "echo \"$OUT\" | grep -q '\"status\":\"success\"' || fail \"close summary lacks status=success: $OUT\"",
  "echo \"$OUT\" | grep -qF '\"row_close\":\"closed\"' || fail \"close summary lacks row_close=closed: $OUT\"",
  "if grep -qE '^\\| W-093 \\|' \"$TMP/$BL_REL\"; then fail \"close case did NOT strike the W-093 row\"; fi",
  "grep -qE '^\\| W-100 \\|' \"$TMP/$BL_REL\" || fail \"close case WRONGLY struck the W-100 decoy (matched a later-column mention)\"",
  "CLOG=\"$(git -C \"$TMP\" log -1 --format='%s%n%b')\"",
  "echo \"$CLOG\" | grep -qF 'chore(dashboard): W-093 close (merged' || fail \"close commit subject wrong: $CLOG\"",
  "echo \"$CLOG\" | grep -qF 'Garelier: tpm pm-direct W-082' || fail \"close commit lacks the --close-trailer line: $CLOG\"",
  "cleanup_fixture",
  "",
  "# ── 5. GATE ACTIVE → row close DEFERRED ─────────────────────────────────────────",
  "# The merge still lands, but a foreign active.lock (a NEXT self-drained gate) is",
  "# present at close time, so the row is left untouched and reported deferred. The",
  "# quality-gate command plants the foreign lock DURING the gate: the gate's own",
  "# clear_lock_if_mine only removes a lock matching ITS request_id, so a foreign one",
  "# survives past success. The lock MUST reference a LIVE pid — self_drain_queue runs",
  "# a dock_merge poll that aborts+releases a DEAD-pid lock (isPidAlive via",
  "# process.kill(pid,0)), which a real next-gate lock never is. We use THIS test",
  "# process's Windows pid ($$'s /proc winpid), alive through the whole close step.",
  "mk_fixture land-defer 6",
  "seed_backlog",
  "LOCKDIR=\"$DT/__garelier/tpm/runtime/merge_gate/locks\"",
  "MYWIN=\"$(cat /proc/$$/winpid 2>/dev/null || echo $$)\"",
  "# W-045: pass MYWIN/DT as printf %s ARGS (not embedded literally inside the",
  "# single-quoted format string) -- the earlier form only escaped detection by",
  "# relying on this heredoc's unquoted-EOF expansion; %s+arg is the same",
  "# convention the rest of this file uses (see plant_lock's siblings above) and",
  "# stays correct even if this heredoc is ever requoted.",
  "cat > \"$TMP/plant-lock-gate\" <<EOF",
  "#!/usr/bin/env bash",
  "mkdir -p \"$LOCKDIR\"",
  "printf '{\"pid\":%s,\"request_id\":\"FOREIGN-NEXT-GATE\",\"request_file\":\"FOREIGN-NEXT-GATE.json\",\"started_at\":\"%s\",\"target_root\":\"%s\"}' \"$MYWIN\" \"\\$(date -u +%Y-%m-%dT%H:%M:%SZ)\" \"$DT\" > \"$LOCKDIR/active.lock\"",
  "exit 0",
  "EOF",
  "set +e",
  "OUT=\"$(bun \"$ML\" --project \"$DT\" --target-root \"$DT\" --pm-id tpm \\",
  "  --branch \"garelier/main/tpm/workbench/#6/land-defer\" --guardian PASS \\",
  "  --quality-gate \"bash '$TMP/plant-lock-gate'\" --no-pull --max-wait 90 --poll-interval 2 \\",
  "  --close-row W-093 2>/dev/null)\"",
  "RC=$?",
  "set -e",
  "[ \"$RC\" -eq 0 ] || fail \"deferred case exit was $RC (expected 0 — merge still lands). summary=$OUT\"",
  "echo \"$OUT\" | grep -qF '\"row_close\":\"deferred (gate active)\"' || fail \"deferred summary lacks row_close=deferred: $OUT\"",
  "grep -qE '^\\| W-093 \\|' \"$TMP/$BL_REL\" || fail \"deferred case WRONGLY struck the W-093 row (must defer, not touch backlog)\"",
  "cleanup_fixture",
  "",
  "# ── 6. NOT FOUND → no commit, reported not-found ────────────────────────────────",
  "# Gate passes, but the requested id is absent from the backlog: nothing struck,",
  "# nothing committed, row_close=not-found (never a failure).",
  "mk_fixture land-nf 7",
  "seed_backlog",
  "set +e",
  "OUT=\"$(bun \"$ML\" --project \"$DT\" --target-root \"$DT\" --pm-id tpm \\",
  "  --branch \"garelier/main/tpm/workbench/#7/land-nf\" --guardian PASS \\",
  "  --quality-gate 'true' --no-pull --max-wait 90 --poll-interval 2 \\",
  "  --close-row W-777 2>/dev/null)\"",
  "RC=$?",
  "set -e",
  "[ \"$RC\" -eq 0 ] || fail \"not-found case exit was $RC (expected 0). summary=$OUT\"",
  "echo \"$OUT\" | grep -qF '\"row_close\":\"not-found\"' || fail \"not-found summary lacks row_close=not-found: $OUT\"",
  "grep -qE '^\\| W-093 \\|' \"$TMP/$BL_REL\" || fail \"not-found case WRONGLY modified the backlog\"",
  "if git -C \"$TMP\" log -1 --format='%s' | grep -q 'chore(dashboard)'; then fail \"not-found case WRONGLY made a close commit\"; fi",
  "cleanup_fixture",
  "",
  "# ── W-017 argument-UX cases ─────────────────────────────────────────────────────",
  "",
  "# ── 7. --dispatch-id resolves branch + Guardian verdict auto-read (no --branch,",
  "#      no --guardian) → still lands end-to-end ────────────────────────────────────",
  "# Proves both (a) branch resolution from the dispatch container's checkout HEAD and",
  "# (c) verdict auto-read from the `## Verdict` marker: the merge could ONLY reach the",
  "# gate (and land) if pre-validation resolved a branch AND a passing Guardian verdict",
  "# from files alone. A guardian marker is planted at the dispatch_prepare-convention",
  "# path; --id is the alias (the exact flag the PM tried in the live failure).",
  "mk_fixture land-autoid 8",
  "mkdir -p \"$TMP/$GREL/tpm/runtime/guardian/results\"",
  "printf '## Verdict\\n\\nPASS\\n' > \"$TMP/$GREL/tpm/runtime/guardian/results/land-autoid-guardian.md\"",
  "ERRF=\"$(mktemp)\"",
  "set +e",
  "OUT=\"$(bun \"$ML\" --project \"$DT\" --target-root \"$DT\" --pm-id tpm \\",
  "  --id 8 --quality-gate 'true' --no-pull --max-wait 90 --poll-interval 2 2>\"$ERRF\")\"",
  "RC=$?",
  "set -e",
  "[ \"$RC\" -eq 0 ] || fail \"autoid case exit was $RC (expected 0). summary=$OUT stderr=$(cat \"$ERRF\")\"",
  "echo \"$OUT\" | grep -q '\"status\":\"success\"' || fail \"autoid summary lacks status=success: $OUT\"",
  "echo \"$OUT\" | grep -q '\"branch_deleted\":true' || fail \"autoid summary lacks branch_deleted=true: $OUT\"",
  "grep -qF 'resolved --branch garelier/main/tpm/workbench/#8/land-autoid from dispatch #8' \"$ERRF\" \\",
  "  || fail \"autoid case did not log branch resolution from --dispatch-id: $(cat \"$ERRF\")\"",
  "grep -qF \"auto-read Guardian verdict 'PASS'\" \"$ERRF\" \\",
  "  || fail \"autoid case did not log Guardian verdict auto-read: $(cat \"$ERRF\")\"",
  "git -C \"$TMP\" cat-file -e garelier/main/tpm/studio:land-autoid.txt 2>/dev/null \\",
  "  || fail \"autoid case did not land the merge onto studio\"",
  "rm -f \"$ERRF\"",
  "cleanup_fixture",
  "",
  "# ── 8. Pre-validation reports EVERY missing required input at once + usage ───────",
  "# No --branch/--dispatch-id AND no --guardian: the old flow failed one arg at a time",
  "# only at submit; now both are reported together with usage, before any submit.",
  "mk_fixture land-preval 9",
  "set +e",
  "ERR=\"$(bun \"$ML\" --project \"$DT\" --target-root \"$DT\" --pm-id tpm 2>&1 1>/dev/null)\"",
  "RC=$?",
  "set -e",
  "[ \"$RC\" -eq 2 ] || fail \"pre-validation missing-all exit was $RC (expected 2). out=$ERR\"",
  "echo \"$ERR\" | grep -qF 'cannot submit' || fail \"pre-validation lacks the batch header: $ERR\"",
  "echo \"$ERR\" | grep -qi 'branch' || fail \"pre-validation did not report the missing branch: $ERR\"",
  "echo \"$ERR\" | grep -qF 'Guardian verdict required' || fail \"pre-validation did not report the missing Guardian verdict: $ERR\"",
  "echo \"$ERR\" | grep -qF 'Usage:' || fail \"pre-validation did not print usage: $ERR\"",
  "cleanup_fixture",
  "",
  "# ── 9. --id to a nonexistent container fails clearly (before submit), and --id is",
  "#      an accepted alias (a provided --guardian is NOT spuriously flagged) ─────────",
  "mk_fixture land-badid 10",
  "set +e",
  "ERR=\"$(bun \"$ML\" --project \"$DT\" --target-root \"$DT\" --pm-id tpm --id 999 --guardian PASS 2>&1 1>/dev/null)\"",
  "RC=$?",
  "set -e",
  "[ \"$RC\" -eq 2 ] || fail \"--id nonexistent exit was $RC (expected 2). out=$ERR\"",
  "echo \"$ERR\" | grep -qF 'no dispatch checkout' || fail \"--id nonexistent lacks the checkout-not-found error: $ERR\"",
  "echo \"$ERR\" | grep -qF 'Guardian verdict required' && fail \"--id nonexistent WRONGLY flagged the provided --guardian: $ERR\"",
  "cleanup_fixture",
  "",
  "# ── 10. Non-passing AUTO-READ Guardian verdict is refused before submit (never a",
  "#       silent land); an explicit --guardian overrides the same marker ────────────",
  "mk_fixture land-block 11",
  "mkdir -p \"$TMP/$GREL/tpm/runtime/guardian/results\"",
  "printf '## Verdict\\n\\nBLOCK\\n' > \"$TMP/$GREL/tpm/runtime/guardian/results/land-block-guardian.md\"",
  "set +e",
  "ERR=\"$(bun \"$ML\" --project \"$DT\" --target-root \"$DT\" --pm-id tpm --id 11 \\",
  "  --quality-gate 'true' --no-pull 2>&1 1>/dev/null)\"",
  "RC=$?",
  "set -e",
  "[ \"$RC\" -eq 2 ] || fail \"auto-read BLOCK exit was $RC (expected 2 — must not land on a BLOCK). out=$ERR\"",
  "echo \"$ERR\" | grep -qF 'auto-read Guardian verdict is BLOCK' || fail \"auto-read BLOCK case lacks the refusal message: $ERR\"",
  "cleanup_fixture",
  "",
  "# ── W-027 verdict auto-read path/diagnostic cases ───────────────────────────────",
  "",
  "# ── 13. Relative --project ('.') auto-reads the verdict marker ──────────────────",
  "# The marker path is built from --project; with a RELATIVE --project (the PM's",
  "# `--project .`) read_marker_verdict used to cd into the parser dir and read the",
  "# relative path from the WRONG cwd → silent ENOENT → a fail-closed \"Guardian",
  "# verdict required\" misfire (2026-07-07, three consecutive land failures). Run",
  "# from INSIDE the project with --project . and prove the Guardian PASS is auto-read",
  "# and the merge still lands end-to-end.",
  "mk_fixture land-relauto 14",
  "mkdir -p \"$TMP/$GREL/tpm/runtime/guardian/results\"",
  "printf '## Verdict\\n\\nPASS\\n' > \"$TMP/$GREL/tpm/runtime/guardian/results/land-relauto-guardian.md\"",
  "ERRF=\"$(mktemp)\"",
  "set +e",
  "OUT=\"$(cd \"$TMP\" && bun \"$ML\" --project . --target-root \"$DT\" --pm-id tpm \\",
  "  --id 14 --quality-gate 'true' --no-pull --max-wait 90 --poll-interval 2 2>\"$ERRF\")\"",
  "RC=$?",
  "set -e",
  "grep -qF \"auto-read Guardian verdict 'PASS'\" \"$ERRF\" \\",
  "  || fail \"relative --project did NOT auto-read the Guardian verdict (W-027 regression): $(cat \"$ERRF\")\"",
  "if grep -qF 'MALFORMED' \"$ERRF\"; then fail \"relative --project WRONGLY flagged the present marker malformed: $(cat \"$ERRF\")\"; fi",
  "[ \"$RC\" -eq 0 ] || fail \"relative --project auto-read exit was $RC (expected 0). summary=$OUT stderr=$(cat \"$ERRF\")\"",
  "echo \"$OUT\" | grep -q '\"status\":\"success\"' || fail \"relative --project case lacks status=success: $OUT\"",
  "git -C \"$TMP\" cat-file -e garelier/main/tpm/studio:land-relauto.txt 2>/dev/null \\",
  "  || fail \"relative --project case did not land the merge onto studio\"",
  "rm -f \"$ERRF\"",
  "cleanup_fixture",
  "",
  "# ── 14. A present-but-malformed marker reports MALFORMED, distinct from absent ───",
  "# A gate role that wrote a PROSE verdict instead of a bare token (the re-failure",
  "# this fix targets): the marker EXISTS but extractVerdict captures no canonical",
  "# token, so the land is refused fail-closed — AND the reason is now visible on",
  "# stderr as \"malformed\", not conflated with an absent marker.",
  "mk_fixture land-malformed 15",
  "mkdir -p \"$TMP/$GREL/tpm/runtime/guardian/results\"",
  "printf '## Verdict\\n\\nGuardian verdict: PASS — no blockers found.\\n' \\",
  "  > \"$TMP/$GREL/tpm/runtime/guardian/results/land-malformed-guardian.md\"",
  "set +e",
  "ERR=\"$(cd \"$TMP\" && bun \"$ML\" --project . --target-root \"$DT\" --pm-id tpm \\",
  "  --id 15 --quality-gate 'true' --no-pull 2>&1 1>/dev/null)\"",
  "RC=$?",
  "set -e",
  "[ \"$RC\" -eq 2 ] || fail \"malformed-marker exit was $RC (expected 2 — no valid verdict, fail-closed). out=$ERR\"",
  "echo \"$ERR\" | grep -qF 'MALFORMED' || fail \"malformed-marker case did not report the marker as malformed: $ERR\"",
  "echo \"$ERR\" | grep -qF 'Guardian verdict required' || fail \"malformed-marker case lacks the pre-validation refusal: $ERR\"",
  "cleanup_fixture",
  "",
  "# ── W-024: merge-gate heavy_compile lock skip on a data-only gate ───────────────",
  "",
  "# ── 11. A data-only merge SKIPS the heavy-compile lock ──────────────────────────",
  "# The docs-only diff classifies gate_mode=data_only, so the gate runs the cheap",
  "# data_only_commands and must NOT acquire the heavy_compile lock (the 2026-07-06",
  "# 90-min stall was a docs-only gate queued behind that lock). Proof: the FAILING",
  "# full quality-gate ('false') would fail the merge if it ran, but the merge LANDS",
  "# because the data_only_commands ('true') ran instead; and the lock dir is never",
  "# created, so the acquire was skipped.",
  "mk_fixture_lock land-dataonly 12 \"docs/guide.md\"",
  "set +e",
  "OUT=\"$(bun \"$ML\" --project \"$DT\" --target-root \"$DT\" --pm-id tpm \\",
  "  --branch \"garelier/main/tpm/workbench/#12/land-dataonly\" --guardian PASS \\",
  "  --quality-gate 'false' --no-pull --max-wait 90 --poll-interval 2 2>/dev/null)\"",
  "RC=$?",
  "set -e",
  "[ \"$RC\" -eq 0 ] || fail \"data-only case exit was $RC (expected 0 — data_only_commands run, not the failing full gate). summary=$OUT\"",
  "echo \"$OUT\" | grep -q '\"status\":\"success\"' || fail \"data-only summary lacks status=success: $OUT\"",
  "[ ! -e \"$TMP/$HEAVY_LOCK_REL\" ] || fail \"data-only gate created the heavy_compile lock dir — the acquire was NOT skipped (W-024)\"",
  "cleanup_fixture",
  "",
  "# ── 12. A full (non-data-only) merge ENGAGES the lock (contrast / regression) ────",
  "# A src diff classifies gate_mode=full, so the gate acquires the lock (creating",
  "# the lock dir) around its build. Proves the W-024 skip is conditional on",
  "# data_only mode, not a blanket removal of the lock.",
  "mk_fixture_lock land-fullcompile 13 \"src/code.txt\"",
  "set +e",
  "OUT=\"$(bun \"$ML\" --project \"$DT\" --target-root \"$DT\" --pm-id tpm \\",
  "  --branch \"garelier/main/tpm/workbench/#13/land-fullcompile\" --guardian PASS \\",
  "  --quality-gate 'true' --no-pull --max-wait 90 --poll-interval 2 2>/dev/null)\"",
  "RC=$?",
  "set -e",
  "[ \"$RC\" -eq 0 ] || fail \"full-compile case exit was $RC (expected 0). summary=$OUT\"",
  "echo \"$OUT\" | grep -q '\"status\":\"success\"' || fail \"full-compile summary lacks status=success: $OUT\"",
  "[ -d \"$TMP/$HEAVY_LOCK_REL\" ] || fail \"full merge did NOT engage the heavy_compile lock (lock dir absent) — regression\"",
  "cleanup_fixture",
  "",
  "# ── W-022 batch-land cases ──────────────────────────────────────────────────────",
  "",
  "# ── 15. Batch success via repeated --id — TWO dispatches land in ONE command ─────",
  "# Two dispatches in one repo, landed serially by a single `--id 20 --id 21` call.",
  "# Both merges reach studio, both dispatch containers are cleaned, and the final",
  "# stdout line is the batch summary total=2/landed=2/status=success.",
  "mk_fixture batch-a 20",
  "add_dispatch batch-b 21",
  "set +e",
  "OUT=\"$(bun \"$ML\" --project \"$DT\" --target-root \"$DT\" --pm-id tpm \\",
  "  --id 20 --id 21 --guardian PASS --quality-gate 'true' --no-pull --max-wait 90 --poll-interval 2 2>/dev/null)\"",
  "RC=$?",
  "set -e",
  "[ \"$RC\" -eq 0 ] || fail \"batch success exit was $RC (expected 0). summary=$OUT\"",
  "SUMMARY=\"$(printf '%s\\n' \"$OUT\" | tail -1)\"",
  "echo \"$SUMMARY\" | grep -qF '\"batch\":true' || fail \"batch success: last line is not the batch summary: $SUMMARY\"",
  "echo \"$SUMMARY\" | grep -qF '\"total\":2' || fail \"batch success summary lacks total=2: $SUMMARY\"",
  "echo \"$SUMMARY\" | grep -qF '\"landed\":2' || fail \"batch success summary lacks landed=2: $SUMMARY\"",
  "echo \"$SUMMARY\" | grep -qF '\"status\":\"success\"' || fail \"batch success summary lacks status=success: $SUMMARY\"",
  "git -C \"$TMP\" cat-file -e garelier/main/tpm/studio:batch-a.txt 2>/dev/null || fail \"batch: first item did not land on studio\"",
  "git -C \"$TMP\" cat-file -e garelier/main/tpm/studio:batch-b.txt 2>/dev/null || fail \"batch: second item did not land on studio\"",
  "[ ! -e \"$TMP/__garelier/tpm/_dispatch20\" ] || fail \"batch: first dispatch container not cleaned\"",
  "[ ! -e \"$TMP/__garelier/tpm/_dispatch21\" ] || fail \"batch: second dispatch container not cleaned\"",
  "cleanup_fixture",
  "",
  "# ── 16. Batch abort via --batch file — first item FAILS, the rest is NOT attempted ─",
  "# A --batch file: item 1 has a failing quality-gate, item 2 a passing one. Item 1's",
  "# merge fails, so the batch ABORTS and item 2 (which WOULD have passed) is never",
  "# attempted: its dispatch + branch survive untouched, nothing of it reaches studio.",
  "# The summary reports status=failed / attempted=1 / landed=0 and names the failed",
  "# item; exit is non-zero. Proves a failure does not drag the remaining items in.",
  "mk_fixture batch-bad 22",
  "add_dispatch batch-skipped 23",
  "cat > \"$TMP/batch.txt\" <<'BATCH'",
  "# item 1 fails (quality-gate false); item 2 would pass but must NOT be attempted",
  "--id 22 --quality-gate false",
  "--id 23 --quality-gate true",
  "BATCH",
  "set +e",
  "OUT=\"$(bun \"$ML\" --project \"$DT\" --target-root \"$DT\" --pm-id tpm \\",
  "  --guardian PASS --no-pull --max-wait 90 --poll-interval 2 --batch \"$TMP/batch.txt\" 2>/dev/null)\"",
  "RC=$?",
  "set -e",
  "[ \"$RC\" -ne 0 ] || fail \"batch abort exit was 0 (expected non-zero). summary=$OUT\"",
  "SUMMARY=\"$(printf '%s\\n' \"$OUT\" | tail -1)\"",
  "echo \"$SUMMARY\" | grep -qF '\"batch\":true' || fail \"batch abort: last line is not the batch summary: $SUMMARY\"",
  "echo \"$SUMMARY\" | grep -qF '\"status\":\"failed\"' || fail \"batch abort summary lacks status=failed: $SUMMARY\"",
  "echo \"$SUMMARY\" | grep -qF '\"attempted\":1' || fail \"batch abort summary lacks attempted=1 (must stop after item 1): $SUMMARY\"",
  "echo \"$SUMMARY\" | grep -qF '\"landed\":0' || fail \"batch abort summary lacks landed=0: $SUMMARY\"",
  "echo \"$SUMMARY\" | grep -qF '\"failed_item\":\"--id 22' || fail \"batch abort summary does not name the failed item: $SUMMARY\"",
  "# The SKIPPED item 2 must be entirely untouched (never attempted).",
  "[ -e \"$TMP/__garelier/tpm/_dispatch23\" ] || fail \"batch abort WRONGLY cleaned the un-attempted item 2 dispatch\"",
  "[ -n \"$(git -C \"$TMP\" branch --list 'garelier/main/tpm/workbench/#23/*')\" ] || fail \"batch abort WRONGLY deleted the un-attempted item 2 branch\"",
  "if git -C \"$TMP\" cat-file -e garelier/main/tpm/studio:batch-skipped.txt 2>/dev/null; then fail \"batch abort WRONGLY landed the un-attempted item 2 onto studio\"; fi",
  "# The FAILED item 1 also survives (single-land failure cleans nothing).",
  "[ -e \"$TMP/__garelier/tpm/_dispatch22\" ] || fail \"batch abort WRONGLY cleaned the failed item 1 dispatch\"",
  "cleanup_fixture",
  "",
  "# ── W-042 round-3 observer: base-tracking merge must not false-positive the",
  "#    seat-trailer preflight ──────────────────────────────────────────────────",
  "",
  "# ── 17. A proxy dispatch base-tracks (mandatory pickup step, dispatch_prepare.ts",
  "#        \"merge the studio tip into your branch\") AFTER an UNRELATED, non-proxy",
  "#        commit has landed on studio from a different dispatch. A naive two-dot",
  "#        `base_sha..HEAD` range would walk that commit in via the merge's second",
  "#        parent and false-positive on ITS missing trailer (it never needed one) —",
  "#        the exact bug lint_commits.ts's `--range` now avoids with `--first-parent`",
  "#        (merge_land.ts's seat-trailer preflight, ce48c4b). The land must SUCCEED:",
  "#        the branch's own commit carries a correct trailer, and the unrelated",
  "#        commit is excluded from the checked range entirely.",
  "TMP=\"$(mktemp -d)\"; DT=\"$(cygpath -m \"$TMP\" 2>/dev/null || printf '%s' \"$TMP\")\"",
  "(",
  "  cd \"$TMP\"",
  "  git init -q -b main; git config user.email ci@ci; git config user.name t",
  "  echo base > base.txt; git add -A; git commit -q -m init",
  "  git branch \"garelier/main/tpm/studio\" main",
  "  BASE_SHA=\"$(git rev-parse HEAD)\"",
  "  git worktree add -q -b \"garelier/main/tpm/workbench/#30/basetrack\" \"wb30\" \"garelier/main/tpm/studio\"",
  "  ( cd wb30 && echo feat > basetrack.txt && git add -A && git commit -q -m \"feat(core): basetrack [#30]",
  "",
  "Garelier: tpm dock#9 W-996",
  "Garelier-Seat: codex ci-model (proxy-commit via dock seat)\" )",
  "  # An UNRELATED commit lands on studio from a DIFFERENT (self-mode) dispatch —",
  "  # correctly carries no Garelier-Seat trailer, since it isn't a proxy commit.",
  "  git checkout -q \"garelier/main/tpm/studio\"",
  "  # `add unrelated.txt` explicitly (not `-A`): the wb30 linked worktree is still",
  "  # a subdirectory of this primary checkout, and `-A` would stage it as a stray",
  "  # embedded-repo gitlink instead of leaving it as the plain worktree it is.",
  "  echo unrelated > unrelated.txt && git add unrelated.txt",
  "  git commit -q -m \"feat(core): unrelated studio work [#31]",
  "",
  "Garelier: tpm worker#31 W-995\"",
  "  # Mandatory base-track: merge studio (now ahead) into the branch worktree.",
  "  ( cd wb30 && git merge -q \"garelier/main/tpm/studio\" --no-edit )",
  "  git worktree remove wb30",
  "  mkdir -p \"__garelier/tpm/_pm\"",
  "  printf '[project]\\nname = \"test\"\\n\\n[branches]\\ntarget = \"main\"\\nintegration = \"garelier/main/tpm/studio\"\\n' \\",
  "    > \"__garelier/tpm/_pm/setup_config.toml\"",
  "  git worktree add -q \"__garelier/tpm/_dispatch30/checkout\" \"garelier/main/tpm/workbench/#30/basetrack\"",
  "  printf '# Report - #30 basetrack\\n' > \"__garelier/tpm/_dispatch30/report.md\"",
  "  printf '{\"routing\":{\"commit_mode\":\"proxy\",\"model\":\"ci-model\"},\"task\":{\"base_sha\":\"%s\"}}\\n' \"$BASE_SHA\" \\",
  "    > \"__garelier/tpm/_dispatch30/context.json\"",
  ")",
  "set +e",
  "OUT=\"$(bun \"$ML\" --project \"$DT\" --target-root \"$DT\" --pm-id tpm \\",
  "  --branch \"garelier/main/tpm/workbench/#30/basetrack\" --dispatch-id 30 --guardian PASS \\",
  "  --quality-gate 'true' --no-pull --max-wait 90 --poll-interval 2 2>\"$TMP/err30.log\")\"",
  "RC=$?",
  "set -e",
  "[ \"$RC\" -eq 0 ] || fail \"base-track seat-trailer case exit was $RC (expected 0 — must NOT false-positive on the unrelated studio commit). summary=$OUT stderr=$(cat \"$TMP/err30.log\")\"",
  "echo \"$OUT\" | grep -q '\"status\":\"success\"' || fail \"base-track case lacks status=success: $OUT\"",
  "if grep -qF \"fail --require-seat-trailer\" \"$TMP/err30.log\"; then fail \"base-track case WRONGLY flagged the unrelated studio commit: $(cat \"$TMP/err30.log\")\"; fi",
  "git -C \"$TMP\" cat-file -e garelier/main/tpm/studio:basetrack.txt 2>/dev/null || fail \"base-track case did not land the merge onto studio\"",
  "cleanup_fixture",
  "",
  "# ── W-051: seat handover (target-project incident) — a dispatch's context.json still says",
  "#    commit_mode=proxy from the ORIGINAL codex dispatch, but the producer seat",
  "#    handed over to a Claude self-commit seat mid-flight (e.g. codex quota",
  "#    exhaustion), so the LATER commits on the branch carry ordinary self-mode",
  "#    trailers, not the proxy Garelier-Seat line. The strict",
  "#    --require-seat-trailer check would false-positive on every one of them —",
  "#    the exact false ERROR that forced a manual --seat-trailer checked",
  "#    override in #254. The preflight now classifies every commit in range",
  "#    first and auto-switches to self-mode ONLY when the evidence is fully",
  "#    consistent (all self, zero proxy, zero missing) ────────────────────────",
  "",
  "# ── 18. Clean handover: all commits since base_sha carry self trailers only ->",
  "#        auto-switch fires, land SUCCEEDS, and a loud audit line is emitted",
  "#        (never a silent switch).",
  "TMP=\"$(mktemp -d)\"; DT=\"$(cygpath -m \"$TMP\" 2>/dev/null || printf '%s' \"$TMP\")\"",
  "(",
  "  cd \"$TMP\"",
  "  git init -q -b main; git config user.email ci@ci; git config user.name t",
  "  echo base > base.txt; git add -A; git commit -q -m init",
  "  git branch \"garelier/main/tpm/studio\" main",
  "  BASE_SHA=\"$(git rev-parse HEAD)\"",
  "  git worktree add -q -b \"garelier/main/tpm/workbench/#40/handover\" \"wb40\" \"garelier/main/tpm/studio\"",
  "  ( cd wb40 && echo feat1 > handover.txt && git add -A && git commit -q -m \"feat(core): handover step 1 [#40]",
  "",
  "Garelier: tpm worker#40 W-994\" )",
  "  ( cd wb40 && echo feat2 >> handover.txt && git add -A && git commit -q -m \"feat(core): handover step 2 (post-handover) [#40]",
  "",
  "Garelier: tpm worker#40 W-994\" )",
  "  git worktree remove wb40",
  "  mkdir -p \"__garelier/tpm/_pm\"",
  "  printf '[project]\\nname = \"test\"\\n\\n[branches]\\ntarget = \"main\"\\nintegration = \"garelier/main/tpm/studio\"\\n' \\",
  "    > \"__garelier/tpm/_pm/setup_config.toml\"",
  "  git worktree add -q \"__garelier/tpm/_dispatch40/checkout\" \"garelier/main/tpm/workbench/#40/handover\"",
  "  printf '# Report - #40 handover\\n' > \"__garelier/tpm/_dispatch40/report.md\"",
  "  printf '{\"routing\":{\"commit_mode\":\"proxy\",\"model\":\"ci-model\"},\"task\":{\"base_sha\":\"%s\"}}\\n' \"$BASE_SHA\" \\",
  "    > \"__garelier/tpm/_dispatch40/context.json\"",
  ")",
  "set +e",
  "OUT=\"$(bun \"$ML\" --project \"$DT\" --target-root \"$DT\" --pm-id tpm \\",
  "  --branch \"garelier/main/tpm/workbench/#40/handover\" --dispatch-id 40 --guardian PASS \\",
  "  --quality-gate 'true' --no-pull --max-wait 90 --poll-interval 2 2>\"$TMP/err40.log\")\"",
  "RC=$?",
  "set -e",
  "[ \"$RC\" -eq 0 ] || fail \"seat-handover clean case exit was $RC (expected 0 — clean handover must auto-switch). summary=$OUT stderr=$(cat \"$TMP/err40.log\")\"",
  "echo \"$OUT\" | grep -q '\"status\":\"success\"' || fail \"seat-handover clean case lacks status=success: $OUT\"",
  "grep -qF \"seat handover detected\" \"$TMP/err40.log\" || fail \"seat-handover clean case did not emit the loud audit line: $(cat \"$TMP/err40.log\")\"",
  "if grep -qF \"fail --require-seat-trailer\" \"$TMP/err40.log\"; then fail \"seat-handover clean case WRONGLY ran the strict proxy check: $(cat \"$TMP/err40.log\")\"; fi",
  "cleanup_fixture",
  "",
  "# ── 19. Mixed trailers (one proxy-style, one self, since base_sha) must NOT",
  "#        auto-switch — a partial handover is an audit anomaly, not evidence of",
  "#        a clean one, so the strict --require-seat-trailer check still runs",
  "#        and still fails closed (exit non-zero, no land).",
  "TMP=\"$(mktemp -d)\"; DT=\"$(cygpath -m \"$TMP\" 2>/dev/null || printf '%s' \"$TMP\")\"",
  "(",
  "  cd \"$TMP\"",
  "  git init -q -b main; git config user.email ci@ci; git config user.name t",
  "  echo base > base.txt; git add -A; git commit -q -m init",
  "  git branch \"garelier/main/tpm/studio\" main",
  "  BASE_SHA=\"$(git rev-parse HEAD)\"",
  "  git worktree add -q -b \"garelier/main/tpm/workbench/#41/mixed\" \"wb41\" \"garelier/main/tpm/studio\"",
  "  ( cd wb41 && echo feat1 > mixed.txt && git add -A && git commit -q -m \"feat(core): mixed step 1 [#41]",
  "",
  "Garelier: tpm worker#41 W-993",
  "Garelier-Seat: codex ci-model (proxy-commit via dock seat)\" )",
  "  ( cd wb41 && echo feat2 >> mixed.txt && git add -A && git commit -q -m \"feat(core): mixed step 2 (post-handover) [#41]",
  "",
  "Garelier: tpm worker#41 W-993\" )",
  "  git worktree remove wb41",
  "  mkdir -p \"__garelier/tpm/_pm\"",
  "  printf '[project]\\nname = \"test\"\\n\\n[branches]\\ntarget = \"main\"\\nintegration = \"garelier/main/tpm/studio\"\\n' \\",
  "    > \"__garelier/tpm/_pm/setup_config.toml\"",
  "  git worktree add -q \"__garelier/tpm/_dispatch41/checkout\" \"garelier/main/tpm/workbench/#41/mixed\"",
  "  printf '# Report - #41 mixed\\n' > \"__garelier/tpm/_dispatch41/report.md\"",
  "  printf '{\"routing\":{\"commit_mode\":\"proxy\",\"model\":\"ci-model\"},\"task\":{\"base_sha\":\"%s\"}}\\n' \"$BASE_SHA\" \\",
  "    > \"__garelier/tpm/_dispatch41/context.json\"",
  ")",
  "set +e",
  "OUT=\"$(bun \"$ML\" --project \"$DT\" --target-root \"$DT\" --pm-id tpm \\",
  "  --branch \"garelier/main/tpm/workbench/#41/mixed\" --dispatch-id 41 --guardian PASS \\",
  "  --quality-gate 'true' --no-pull --max-wait 90 --poll-interval 2 2>\"$TMP/err41.log\")\"",
  "RC=$?",
  "set -e",
  "[ \"$RC\" -ne 0 ] || fail \"mixed-trailer case unexpectedly succeeded (should fail closed, no auto-switch on partial evidence): $OUT\"",
  "grep -qF \"fail --require-seat-trailer\" \"$TMP/err41.log\" || fail \"mixed-trailer case did not run the strict proxy check: $(cat \"$TMP/err41.log\")\"",
  "if grep -qF \"seat handover detected\" \"$TMP/err41.log\"; then fail \"mixed-trailer case WRONGLY auto-switched to self-mode on partial evidence: $(cat \"$TMP/err41.log\")\"; fi",
  "cleanup_fixture",
  "",
  "# ── 20. An explicit --seat-trailer override still short-circuits BOTH the",
  "#        auto-switch detection and the strict proxy check, even over the same",
  "#        mixed/inconsistent trailers as case 19 — the operator's manual",
  "#        override remains the trusted final word (unchanged pre-W-051 rule).",
  "TMP=\"$(mktemp -d)\"; DT=\"$(cygpath -m \"$TMP\" 2>/dev/null || printf '%s' \"$TMP\")\"",
  "(",
  "  cd \"$TMP\"",
  "  git init -q -b main; git config user.email ci@ci; git config user.name t",
  "  echo base > base.txt; git add -A; git commit -q -m init",
  "  git branch \"garelier/main/tpm/studio\" main",
  "  BASE_SHA=\"$(git rev-parse HEAD)\"",
  "  git worktree add -q -b \"garelier/main/tpm/workbench/#42/override\" \"wb42\" \"garelier/main/tpm/studio\"",
  "  ( cd wb42 && echo feat1 > override.txt && git add -A && git commit -q -m \"feat(core): override step 1 [#42]",
  "",
  "Garelier: tpm worker#42 W-992",
  "Garelier-Seat: codex ci-model (proxy-commit via dock seat)\" )",
  "  ( cd wb42 && echo feat2 >> override.txt && git add -A && git commit -q -m \"feat(core): override step 2 (post-handover) [#42]",
  "",
  "Garelier: tpm worker#42 W-992\" )",
  "  git worktree remove wb42",
  "  mkdir -p \"__garelier/tpm/_pm\"",
  "  printf '[project]\\nname = \"test\"\\n\\n[branches]\\ntarget = \"main\"\\nintegration = \"garelier/main/tpm/studio\"\\n' \\",
  "    > \"__garelier/tpm/_pm/setup_config.toml\"",
  "  git worktree add -q \"__garelier/tpm/_dispatch42/checkout\" \"garelier/main/tpm/workbench/#42/override\"",
  "  printf '# Report - #42 override\\n' > \"__garelier/tpm/_dispatch42/report.md\"",
  "  printf '{\"routing\":{\"commit_mode\":\"proxy\",\"model\":\"ci-model\"},\"task\":{\"base_sha\":\"%s\"}}\\n' \"$BASE_SHA\" \\",
  "    > \"__garelier/tpm/_dispatch42/context.json\"",
  ")",
  "set +e",
  "OUT=\"$(bun \"$ML\" --project \"$DT\" --target-root \"$DT\" --pm-id tpm \\",
  "  --branch \"garelier/main/tpm/workbench/#42/override\" --dispatch-id 42 --guardian PASS \\",
  "  --seat-trailer checked \\",
  "  --quality-gate 'true' --no-pull --max-wait 90 --poll-interval 2 2>\"$TMP/err42.log\")\"",
  "RC=$?",
  "set -e",
  "[ \"$RC\" -eq 0 ] || fail \"explicit --seat-trailer override case exit was $RC (expected 0). summary=$OUT stderr=$(cat \"$TMP/err42.log\")\"",
  "echo \"$OUT\" | grep -q '\"status\":\"success\"' || fail \"explicit override case lacks status=success: $OUT\"",
  "grep -qF \"explicit --seat-trailer checked override\" \"$TMP/err42.log\" || fail \"explicit override case did not log the override message: $(cat \"$TMP/err42.log\")\"",
  "if grep -qF \"seat handover detected\" \"$TMP/err42.log\"; then fail \"explicit override case should not run auto-switch detection at all: $(cat \"$TMP/err42.log\")\"; fi",
  "cleanup_fixture",
  "",
  "# ── W-055: aftercare must survive a missing sibling driver dir ─────────────────",
  "# Root cause (target-project #274 live incident — cleanup + --close-row silently skipped",
  "# after the gate reported success, no error text): `DOCK_MERGE_TS=\"$(cd",
  "# \"$SELF_DIR/../driver/src/dispatch\" 2>/dev/null && pwd -P)/dock_merge.ts\"` had no",
  "# `|| true`. Under `set -e` (armed a few lines earlier), when that cd target does",
  "# not exist, the ENTIRE assignment's exit status is the failed cd's and the whole",
  "# script dies right there — before gate_result_waiter, before cleanup, before",
  "# --close-row — with NO diagnostic (confirmed via `bash -c 'set -e; X=\"$(cd",
  "# /nonexistent 2>/dev/null && pwd -P)\"; echo reached'`: never prints, rc=1).",
  "#",
  "# This is a narrow, stub-driven reproduction (same lighter style as the guard",
  "# cases 3a/3b above, which call scripts directly rather than through a real gate):",
  "# it runs the REAL merge_land.ts with a scratch entry directory and a deliberately",
  "# missing driver dispatch directory, alongside trivial stand-in",
  "# merge_request.ts / gate_result_waiter.ts / dispatch_cleanup.ts that report a",
  "# clean success — isolating the ONE code path under test (DOCK_MERGE_TS",
  "# resolution + the aftercare crash-warning trap) from the real merge-gate",
  "# machinery already covered end to end by case 1 above.",
  "W55_ROOT=\"$(mktemp -d)\"",
  "mkdir -p \"$W55_ROOT/entries\" \\",
  "         \"$W55_ROOT/proj/__garelier/tpm/runtime/merge_gate/results\" \\",
  "         \"$W55_ROOT/proj/__garelier/tpm/runtime/merge_gate/locks\" \\",
  "         \"$W55_ROOT/proj/__garelier/tpm/_dispatch9/checkout\"",
  "(",
  "  cd \"$W55_ROOT/proj/__garelier/tpm/_dispatch9/checkout\"",
  "  git init -q; git config user.email ci@ci; git config user.name t",
  "  echo f > f.txt; git add -A; git commit -q -m init",
  "  git checkout -qb \"garelier/main/tpm/workbench/#9/w55case\"",
  ")",
  "printf '{\"routing\":{\"commit_mode\":\"self\"}}\\n' > \"$W55_ROOT/proj/__garelier/tpm/_dispatch9/context.json\"",
  "cat > \"$W55_ROOT/entries/merge_request.ts\" <<'STUB'",
  "process.stdout.write('{\"request_id\":\"W55REQ\",\"request_file\":\"x\",\"polled\":false,\"waiter_cmd\":\"y\"}\\n');",
  "STUB",
  "cat > \"$W55_ROOT/entries/gate_result_waiter.ts\" <<'STUB'",
  "process.stdout.write('MERGE_RESULT: success W55REQ deadbee5\\n');",
  "STUB",
  "cat > \"$W55_ROOT/entries/dispatch_cleanup.ts\" <<'STUB'",
  "process.stdout.write('{\"id\":9,\"removed\":\"x\",\"branch\":\"b\",\"branch_deleted\":true,\"cleanup_status\":\"success\",\"merge_status\":\"merged\",\"report_source\":\"none\",\"task_mirror_hint\":\"h\"}\\n');",
  "STUB",
  "[ ! -e \"$W55_ROOT/missing-dispatch\" ] || fail \"W-055 fixture setup: the deliberately missing dispatch dir already exists\"",
  "set +e",
  "# W-111: direct Bun entrypoint with injected sibling and dispatch directories.",
  "# The latter is deliberately absent, preserving the W-055 missing dock_merge",
  "# aftercare condition without relocating the production module.",
  "W55_OUT=\"$(GARELIER_SCRIPT_ENTRY_DIR=\"$W55_ROOT/entries\" GARELIER_DRIVER_DISPATCH_DIR=\"$W55_ROOT/missing-dispatch\" bun \"$ML\" --project \"$W55_ROOT/proj\" --pm-id tpm \\",
  "  --dispatch-id 9 --guardian PASS --no-pull 2>\"$W55_ROOT/err.log\")\"",
  "W55_RC=$?",
  "set -e",
  "[ \"$W55_RC\" -eq 0 ] || fail \"W-055: merge_land died (rc=$W55_RC) instead of completing aftercare with a missing driver dir. stdout=$W55_OUT stderr=$(cat \"$W55_ROOT/err.log\")\"",
  "[ -n \"$W55_OUT\" ] || fail \"W-055: merge_land produced NO stdout JSON at all — this is the exact silent-death symptom the fix addresses. stderr=$(cat \"$W55_ROOT/err.log\")\"",
  "printf '%s' \"$W55_OUT\" | grep -q '\"status\":\"success\"' || fail \"W-055: missing status=success: $W55_OUT\"",
  "printf '%s' \"$W55_OUT\" | grep -q '\"cleanup_status\":\"success\"' || fail \"W-055: aftercare cleanup did not run/complete (cleanup_status != success): $W55_OUT\"",
  "grep -qF \"dock_merge.ts not found\" \"$W55_ROOT/err.log\" || fail \"W-055: expected the graceful 'dock_merge.ts not found' fallback message, got: $(cat \"$W55_ROOT/err.log\")\"",
  "# The crash-warning trap must stay SILENT on the normal (non-crashing) path.",
  "grep -qF \"aftercare crashed\" \"$W55_ROOT/err.log\" && fail \"W-055: the aftercare crash-warning trap fired on a CLEAN run: $(cat \"$W55_ROOT/err.log\")\"",
  "rm -rf \"$W55_ROOT\" 2>/dev/null || true",
  "",
  "echo \"merge_land.test: all cases pass (success / failure / guard non-interference + negative control / close-row success+deferred+not-found / W-017 dispatch-id+verdict auto-read + batch pre-validation + bad-id + auto-BLOCK refusal / W-027 relative-project auto-read + malformed-marker diagnostic / W-024 data-only lock-skip + full-mode lock engage / W-022 batch land 2-item success + abort-on-first-failure / round-3 base-tracking-merge seat-trailer false-positive fix / W-051 seat handover clean-switch + mixed-still-error + explicit-override-wins / W-055 aftercare survives a missing sibling driver dir, crash-warning trap silent on the clean path)\"",
].join("\n") + "\n";

test("merge_land shell parity oracle", () => {
  const result = runShellOracle(shellScript, import.meta.path);
  const stdout = result.stdout?.toString() ?? "";
  const stderr = result.stderr?.toString() ?? "";
  expect(result.exitCode, stdout + stderr).toBe(0);
}, 600_000);
