import { expect, test } from "bun:test";
import { runShellOracle } from "../driver/src/scripts/shell_oracle_test_runner.ts";

// W-111: Bun registers this parity oracle. Its existing shell assertions remain
// verbatim while every Garelier CLI under test is invoked directly with Bun.
const shellScript = [
  "#!/usr/bin/env bash",
  "#",
  "# merge_land.test.ts — pins the merge_land.ts macro (W-088).",
  "#",
  "# Uses the W-087 dummy-gate rig: a REAL merge gate run, but with a trivial",
  "# quality-gate command (`true` / `false`) standing in for a multi-minute build, so",
  "# the whole submit → wait → cleanup → pull chain is exercised end to end in seconds.",
  "#",
  "#   1. SUCCESS  — gate passes → merge lands, dispatch cleaned up (worktree removed,",
  "#                 branch deleted, report archived), summary status=success, exit 0.",
  "#   2. FAILURE  — gate fails → NOTHING is cleaned up (dispatch + branch survive),",
  "#                 summary status=failed, exit non-zero.",
  "#   3. W-055 guard non-interference — a merged dispatch is cleaned even while a",
  "#      FOREIGN gate (a different slug) holds active.lock; the same cleanup is still",
  "#      REFUSED when the lock names THIS slug (the guard is slug-specific, so",
  "#      merge_land's post-success cleanup is not blocked by a concurrent gate).",
  "#",
  "# Self-contained: run directly (`bun test merge_land.test.ts`) or from ci.ts. Needs",
  "# bun + git + a POSIX shell. Exits 0 only if every case holds.",
  "set -uo pipefail",
  "",
  "ORIG_CWD=\"$(pwd -P)\"",
  "SELF_DIR=\"$(cd \"$(dirname \"$0\")\" && pwd)\"",
  "ML=\"$SELF_DIR/../driver/src/scripts/merge_land.ts\"",
  "MG=\"$SELF_DIR/../driver/src/scripts/merge-gate.ts\"",
  "CLEANUP=\"$SELF_DIR/../driver/src/scripts/dispatch_cleanup.ts\"",
  "CONTROL_FIXTURE=\"$(cygpath -m \"$SELF_DIR/../driver/src/control/fixtures/v3_control.ts\")\"",
  "CONTROL_SESSIONS=\"$(cygpath -m \"$SELF_DIR/../driver/src/control/sessions.ts\")\"",
  "CONTROL_CLAIMS=\"$(cygpath -m \"$SELF_DIR/../driver/src/control/claims.ts\")\"",
  "CONTROL_PLAN_GRAPH=\"$(cygpath -m \"$SELF_DIR/../driver/src/control/plan_graph_write.ts\")\"",
  "CONTROL_SERIALIZATION=\"$(cygpath -m \"$SELF_DIR/../driver/src/control/serialization.ts\")\"",
  "ROLE_BINDING=\"$(cygpath -m \"$SELF_DIR/../driver/src/dispatch/role_binding.ts\")\"",
  "KNOWLEDGE_BINDING=\"$(cygpath -m \"$SELF_DIR/../driver/src/dispatch/knowledge_binding.ts\")\"",
  "DOCK_REVIEW_RECORD=\"$(cygpath -m \"$SELF_DIR/../driver/src/dispatch/dock_review_record.ts\")\"",
  "GATE_RUN_RECORD=\"$(cygpath -m \"$SELF_DIR/../driver/src/dispatch/gate_run_record.ts\")\"",
  "GATE_STEP_ARTIFACTS=\"$(cygpath -m \"$SELF_DIR/../driver/src/dispatch/gate_step_artifacts.ts\")\"",
  "SECURITY_REGISTRIES=\"$SELF_DIR/../../garelier-librarian/templates/security/registries\"",
  "[ -f \"$ML\" ] || { echo \"merge_land.test: cannot find merge_land.ts next to me\" >&2; exit 1; }",
  "[ -f \"$MG\" ] || { echo \"merge_land.test: cannot find merge-gate.ts next to me\" >&2; exit 1; }",
  "",
  "fail() { echo \"  FAIL: $*\" >&2; exit 1; }",
  "GREL=\"__garelier\"",
  "LP=\"$SELF_DIR/../driver/src/scripts/land_pipeline.ts\"",
  "seed_control() {",
  "  bun -e 'import { pathToFileURL } from \"node:url\"; const [root, fixturePath] = process.argv.slice(1); const { writeV3Fixture } = await import(pathToFileURL(fixturePath).href); writeV3Fixture(root, 60, \"tpm\");' \"$DT\" \"$CONTROL_FIXTURE\"",
  "  if [ -n \"${FIXTURE_DECLARED_PM_STEP:-}\" ]; then",
  "    bun -e 'import { mkdirSync, writeFileSync } from \"node:fs\"; import { join } from \"node:path\"; const path = join(process.argv[1], \"__garelier\", \"tpm\", \"control\", \"blueprints\", \"fixture-pm-step.md\"); mkdirSync(join(path, \"..\"), { recursive: true }); writeFileSync(path, [\"+++\", \"schema_version = 3\", \"kind = \\\"garelier_blueprint\\\"\", \"slug = \\\"fixture-pm-step\\\"\", \"title = \\\"Fixture PM step\\\"\", \"status = \\\"active\\\"\", \"created = \\\"2026-09-23T00:00:00.000Z\\\"\", \"updated = \\\"2026-09-23T00:00:00.000Z\\\"\", \"pm_step = \\\"fixture declared step\\\"\", \"+++\", \"\", \"# Fixture PM step\", \"\"].join(\"\\n\"));' \"$DT\"",
  "  fi",
  "  if git -C \"$DT\" rev-parse --git-dir >/dev/null 2>&1; then",
  "    git -C \"$DT\" add -- __garelier/tpm/control",
  "    git -C \"$DT\" commit -q -m 'seed Control fixture'",
  "    git -C \"$DT\" update-ref refs/heads/garelier/main/tpm/studio HEAD",
  "  fi",
  "}",
  "bind_control() {",
  "  local id=\"$1\" work_id session_id",
  "  work_id=\"$(printf 'W-%03d' \"$id\")\"; session_id=\"cs_lane_$id\"",
  "  bun -e 'import { pathToFileURL } from \"node:url\"; const [root, workId, sessionId, sessionsPath, claimsPath, planPath] = process.argv.slice(1); const [{ openControlSession }, { claimWork }, { planGraphRuntimeCallbacks }] = await Promise.all([sessionsPath, claimsPath, planPath].map((path) => import(pathToFileURL(path).href))); openControlSession({ targetRoot: root, pmId: \"tpm\", agent: \"fixture\", cwd: root, sessionId, runtimeCallbacks: planGraphRuntimeCallbacks }); claimWork({ targetRoot: root, pmId: \"tpm\", workId, sessionId, runtimeCallbacks: planGraphRuntimeCallbacks });' \"$DT\" \"$work_id\" \"$session_id\" \"$CONTROL_SESSIONS\" \"$CONTROL_CLAIMS\" \"$CONTROL_PLAN_GRAPH\"",
  "}",
  "write_control_binding() {",
  "  local id=\"$1\" base_sha=\"$2\" work_id session_id",
  "  work_id=\"$(printf 'W-%03d' \"$id\")\"; session_id=\"cs_lane_$id\"",
  "  printf '{\"schema_version\":3,\"dispatch_id\":\"%s\",\"work_id\":\"%s\",\"session_id\":\"%s\",\"touches\":[],\"base_sha\":\"%s\"}\\n' \"$id\" \"$work_id\" \"$session_id\" \"$base_sha\" > \"__garelier/tpm/_crew/dispatch$id/control_binding.json\"",
  "}",
  "bind_role() {",
  "  local id=\"$1\" gate_command=\"${FIXTURE_GATE_COMMAND:-true}\"",
  "  mkdir -p \"__garelier/tpm/_crew/dispatch$id\"",
  "  printf '# Assignment %s\\n' \"$id\" > \"__garelier/tpm/_crew/dispatch$id/assignment.md\"",
  "  git add -f -- \"__garelier/tpm/_crew/dispatch$id/assignment.md\"",
  "  git commit -q -m \"bind dispatch $id assignment authority\"",
  "  git update-ref refs/heads/garelier/main/tpm/studio HEAD",
  "  grep -q '^\\[quality_gate\\]$' \"__garelier/tpm/_crew/pm/setup_config.toml\" || printf '\\n[quality_gate]\\ncommands = [\"true\"]\\n' >> \"__garelier/tpm/_crew/pm/setup_config.toml\"",
  "  grep -q '^\\[guardian_tools\\]$' \"__garelier/tpm/_crew/pm/setup_config.toml\" || printf '\\n[guardian_tools]\\nsecret_scan = \"gitleaks dir . --no-banner --redact --report-format json --report-path -\"\\n' >> \"__garelier/tpm/_crew/pm/setup_config.toml\"",
  "  bun -e 'import { pathToFileURL } from \"node:url\"; import { join } from \"node:path\"; import { mkdirSync, readFileSync, writeFileSync } from \"node:fs\"; const [root, id, rolePath, knowledgePath] = process.argv.slice(1); const [{ acknowledgeRoleLaunch, bindingReference, dispatchExecutionIdentity, issueRoleAuthorization }, { resolveRoleKnowledgeBinding }] = await Promise.all([rolePath, knowledgePath].map((path) => import(pathToFileURL(path).href))); const container = join(root, \"__garelier\", \"tpm\", \"_crew\", `dispatch${id}`); const assignment = join(container, \"assignment.md\"); const prompt = join(container, \"lane\", \"prompt.md\"); const report = join(container, \"report.md\"); const ledger = join(container, \"instructions.md\"); const contextPath = join(container, \"context.json\"); const context = JSON.parse(readFileSync(contextPath, \"utf8\")); const control = JSON.parse(readFileSync(join(container, \"control_binding.json\"), \"utf8\")); mkdirSync(join(container, \"lane\"), { recursive: true }); writeFileSync(assignment, `# Assignment ${id}\\n`); writeFileSync(prompt, `Execute dispatch ${id}.\\n`); writeFileSync(ledger, \"+++\\n[ledger]\\n+++\\n\\n# Instruction ledger\\n\"); writeFileSync(join(container, \"STATE.md\"), `# Dispatch #${id}\\n\\n## Status\\n\\nREPORTING\\n`); const identity = dispatchExecutionIdentity(id); const authorization = issueRoleAuthorization({ project_root: root, pm_id: \"tpm\", identity, role: \"worker\", carabiner: \"implementation\", item: { work_id: control.work_id, revision: \"fixture\", session_id: control.session_id, authority_path: assignment }, assignment_path: assignment, prompt_path: prompt, initial_instructions_path: ledger, routing: { provider: \"attended-agent\", model: \"test-model\", effort: \"medium\", source: \"aggregate\" }, lens: { ref: null, source: \"none\", registry_path: null, pack_path: null }, knowledge: resolveRoleKnowledgeBinding({ projectRoot: root, pmId: \"tpm\", role: \"worker\", required: [] }), integration: { ref: \"garelier/main/tpm/studio\", base_sha: control.base_sha }, issuer: { role: \"dock\", id: \"aggregate\" } }); acknowledgeRoleLaunch({ project_root: root, pm_id: \"tpm\", identity, generation: authorization.core.generation, expect_digest: authorization.core_digest, transport: \"attended-agent\", provider_session_id: `agent-${id}`, success_evidence: \"aggregate launch\", writer: { role: \"attended-parent\", id: \"aggregate\" } }); context.producer_binding = bindingReference(authorization); writeFileSync(contextPath, `${JSON.stringify(context)}\\n`);' \"$DT\" \"$id\" \"$ROLE_BINDING\" \"$KNOWLEDGE_BINDING\" || fail \"bind_role $id failed\"",
  "  bun -e 'import { pathToFileURL } from \"node:url\"; import { join } from \"node:path\"; import { readFileSync, writeFileSync } from \"node:fs\"; const [root, id, rolePath, command] = process.argv.slice(1); const { updateRoleQualityGateSelection } = await import(pathToFileURL(rolePath).href); const path = join(root, \"__garelier\", \"tpm\", \"_crew\", `dispatch${id}`, \"context.json\"); const context = JSON.parse(readFileSync(path, \"utf8\")); context.quality_gate_selection = updateRoleQualityGateSelection({ project_root: root, pm_id: \"tpm\", reference: context.producer_binding, expected_context_selection: null, next: { name: `fixture-${id}`, commands: [command], source: \"aggregate\", declared_at: \"2026-09-21T00:00:00.000Z\" }, writer: { role: \"pm\", id: \"aggregate\" } }); writeFileSync(path, `${JSON.stringify(context)}\\n`);' \"$DT\" \"$id\" \"$ROLE_BINDING\" \"$gate_command\" || fail \"bind_role $id gate selection failed\"",
  "  bun -e 'import { join } from \"node:path\"; import { readFileSync, writeFileSync } from \"node:fs\"; const [root, id] = process.argv.slice(1); const container = join(root, \"__garelier\", \"tpm\", \"_crew\", `dispatch${id}`); const path = join(container, \"context.json\"); const context = JSON.parse(readFileSync(path, \"utf8\")); context.worktree = join(container, \"checkout\"); context.branch ??= context.task?.branch; context.base_sha ??= context.task?.base_sha; writeFileSync(path, `${JSON.stringify(context)}\\n`);' \"$DT\" \"$id\" || fail \"bind_role $id context normalization failed\"",
  "  [ -z \"${FIXTURE_PRESERVATION:-}\" ] || seed_preservation \"$id\"",
  "  bun -e 'import { pathToFileURL } from \"node:url\"; import { join, resolve } from \"node:path\"; import { existsSync, mkdirSync, readFileSync, writeFileSync } from \"node:fs\"; const [root, id, recordPath, runRecordModule] = process.argv.slice(1); const [{ engineTreeHash, reviewGateLogPath, writeDockReviewHandoffRecord }, { gateRunRecordPath }] = await Promise.all([recordPath, runRecordModule].map((path) => import(pathToFileURL(path).href))); const container = join(root, \"__garelier\", \"tpm\", \"_crew\", `dispatch${id}`); const lane = join(container, \"lane\"); const context = JSON.parse(readFileSync(join(container, \"context.json\"), \"utf8\")); const git = (...args) => { const child = Bun.spawnSync([\"git\", \"-C\", context.worktree, ...args], { stdout: \"pipe\", stderr: \"pipe\" }); if (child.exitCode !== 0) throw new Error(child.stderr.toString()); return child.stdout.toString().trim(); }; const head = git(\"rev-parse\", \"HEAD^{commit}\"); const base = git(\"rev-parse\", `${context.base_sha}^{commit}`); const engineHash = engineTreeHash(context.worktree, head, (cwd, args) => { const child = Bun.spawnSync([\"git\", \"-C\", cwd, ...args], { stdout: \"pipe\", stderr: \"pipe\" }); return { exitCode: child.exitCode ?? 1, stdout: child.stdout.toString(), stderr: child.stderr.toString() }; }); mkdirSync(lane, { recursive: true }); const scan = join(lane, \"secret-scan.md\"); const scanner = join(lane, `scanner-${head.slice(0, 12)}.md`); const scannerJson = `${scanner}.json`; const log = reviewGateLogPath(lane, head); const accounting = join(lane, \"final_accounting.md\"); const slash = (path) => resolve(path).replaceAll(\"\\\\\", \"/\"); const scannerCommand = \"gitleaks dir . --no-banner --redact --report-format json --report-path -\"; writeFileSync(scan, JSON.stringify({ scan_state: \"complete\", scope: { base_ref: base, head_ref: head } })); writeFileSync(scanner, \"fixture scanner evidence\\n\"); writeFileSync(scannerJson, JSON.stringify({ schema_version: 1, generated_by: \"scanner_evidence.ts\", base, head, exit: 0, scanner_command: scannerCommand, cwd: resolve(context.worktree) })); writeFileSync(log, \"fixture gate GREEN\\n\"); writeFileSync(accounting, [`- Branch: \\`${context.branch}\\``, `- Declared base SHA: \\`${base}\\``, `- Proxy / review SHA: \\`${head}\\``, `- Engine tree hash (excludes control/docs/__garelier): \\`${engineHash}\\``, `- Guardian scan: \\`${slash(scan)}\\``, `- Mandatory scanner evidence: \\`${slash(scanner)}\\``, `- Mandatory scanner evidence JSON: \\`${slash(scannerJson)}\\``, `- Gate log: \\`${slash(log)}\\``, \"- Gate result: GREEN (exit 0)\", \"- Coverage: COVERED (1 of 1 changed paths)\", \"- Coverage map source: candidate checkout\", \"- Coverage map vs studio: UNCHANGED\", \"\"].join(\"\\n\")); writeDockReviewHandoffRecord({ project: root, pmId: \"tpm\", dispatchId: id, branch: context.branch, baseSha: base, reviewSha: head, engineTreeHash: engineHash, gateEngineTreeHash: engineHash, gateRunId: `fixture-${id}`, gateRequiredBlockDigest: \"fixture\", gateStartHead: head, gateEndHead: head, gateExit: 0, gateResult: \"GREEN (exit 0)\", coverage: \"COVERED (1 of 1 changed paths)\", coverageMapSource: \"candidate checkout\", coverageMapVsStudio: \"UNCHANGED\", dockSeat: \"fixture-dock\", dockRecord: join(container, \"dock.dispatch.json\"), evidence: [scan, scanner, scannerJson, log, accounting, ...(existsSync(gateRunRecordPath(root, \"tpm\", log)) ? [gateRunRecordPath(root, \"tpm\", log)] : [])] });' \"$DT\" \"$id\" \"$DOCK_REVIEW_RECORD\" \"$GATE_RUN_RECORD\" || fail \"bind_role $id review handoff failed\"",
  "}",
  "write_self_context() {",
  "  local id=\"$1\" work_id session_id branch base_sha",
  "  work_id=\"$(printf 'W-%03d' \"$id\")\"; session_id=\"cs_lane_$id\"",
  "  branch=\"$(git -C \"__garelier/tpm/_crew/dispatch$id/checkout\" branch --show-current)\"",
  "  base_sha=\"$(git merge-base \"$branch\" \"garelier/main/tpm/studio\")\"",
  "  write_control_binding \"$id\" \"$base_sha\"",
  "  printf '{\"routing\":{\"commit_mode\":\"self\"},\"task\":{\"id\":\"%s\",\"branch\":\"%s\",\"base_sha\":\"%s\",\"touches\":[]},\"control\":{\"schema_version\":3,\"work_id\":\"%s\",\"session_id\":\"%s\"}}\\n' \"$id\" \"$branch\" \"$base_sha\" \"$work_id\" \"$session_id\" > \"__garelier/tpm/_crew/dispatch$id/context.json\"",
  "  bind_role \"$id\"",
  "}",
  "# seed_preservation <id> — give dispatch <id> the gate evidence a real land",
  "# carries (W-843): gate_runner's run records for the review gate log and a",
  "# PM-step log, plus the Guardian registries preservation admission reads. The",
  "# aftercare then publishes run_records/<hex>/payload, the PM-step summary and",
  "# security_admission.json into tracked Control — the exact paths #649's",
  "# settlement refused as unbound.",
  "seed_preservation() {",
  "  local id=\"$1\" name",
  "  mkdir -p \"$TMP/__garelier/tpm/knowledge/security/registries\"",
  "  for name in secret_patterns.toml pii_patterns.toml injection_patterns.toml false_positive_exceptions.toml; do",
  "    cp \"$SECURITY_REGISTRIES/$name\" \"$TMP/__garelier/tpm/knowledge/security/registries/$name\" || fail \"seed_preservation $id could not install $name\"",
  "  done",
  "  bun -e 'import { pathToFileURL } from \"node:url\"; import { join } from \"node:path\"; import { readFileSync, writeFileSync } from \"node:fs\"; const [root, id, recordPath, stepPath] = process.argv.slice(1); const [{ gateRunRecordPath, writeGateRunRecord }, { pmStepGateLogName }] = await Promise.all([recordPath, stepPath].map((path) => import(pathToFileURL(path).href))); const container = join(root, \"__garelier\", \"tpm\", \"_crew\", `dispatch${id}`); const context = JSON.parse(readFileSync(join(container, \"context.json\"), \"utf8\")); const child = Bun.spawnSync([\"git\", \"-C\", context.worktree, \"rev-parse\", \"HEAD^{commit}\"], { stdout: \"pipe\", stderr: \"pipe\" }); if (child.exitCode !== 0) throw new Error(child.stderr.toString()); const head = child.stdout.toString().trim(); const lane = join(container, \"lane\"); const step = join(lane, pmStepGateLogName(head)); const logs = [[join(lane, `gate-${head.slice(0, 12)}.log`), `fixture-review-${id}`]]; if (!process.env.FIXTURE_DECLARED_PM_STEP) { writeFileSync(step, \"fixture PM step GREEN\\nRESULT GREEN\\n\"); logs.push([step, `fixture-pm-step-${id}`]); } for (const [log, runId] of logs) writeGateRunRecord({ path: gateRunRecordPath(root, \"tpm\", log), logPath: log, runId, startedAt: \"2026-09-23T00:00:00.000Z\", endedAt: \"2026-09-23T00:00:01.000Z\", cwd: context.worktree, startHead: head, endHead: head, status: \"GREEN\", exit: 0, preservation: { schema_version: 1, events: [`GATE_START run_id=${runId} started_at=2026-09-23T00:00:00.000Z`, \"RESULT GREEN\", `GATE_END run_id=${runId}`], failed_steps: [] } });' \"$DT\" \"$id\" \"$GATE_RUN_RECORD\" \"$GATE_STEP_ARTIFACTS\" || fail \"seed_preservation $id run records failed\"",
  "}",
  "run_declared_pm_step() {",
  "  local id=\"$1\"",
  "  bun -e 'import { pathToFileURL } from \"node:url\"; import { dirname, join } from \"node:path\"; import { existsSync, mkdirSync, readFileSync, writeFileSync } from \"node:fs\"; const [root, id, pipelinePath, recordPath] = process.argv.slice(1); const [{ stagePmStep, pmStepFileDestination }, { gateRunRecordPath }] = await Promise.all([pipelinePath, recordPath].map(path => import(pathToFileURL(path).href))); const container = join(root, \"__garelier\", \"tpm\", \"_crew\", `dispatch${id}`); const contextPath = join(container, \"context.json\"); const context = JSON.parse(readFileSync(contextPath, \"utf8\")); context.anchors = { source: \"__garelier/tpm/control/blueprints/fixture-pm-step.md\" }; writeFileSync(contextPath, `${JSON.stringify(context)}\\n`); const stepFile = pmStepFileDestination(root, \"tpm\", id); mkdirSync(dirname(stepFile), { recursive: true }); writeFileSync(stepFile, \"pm_step = \\\"fixture declared step\\\"\\n[[step]]\\nname = \\\"fixture-declared\\\"\\ncmd = \\\"true\\\"\\n\"); const run = (argv, cwd, env) => { const child = Bun.spawnSync(argv, { cwd, env: { ...process.env, ...env }, stdout: \"pipe\", stderr: \"pipe\" }); return { exitCode: child.exitCode ?? 1, stdout: child.stdout.toString(), stderr: child.stderr.toString() }; }; const checkout = join(container, \"checkout\"); const head = run([\"git\", \"-C\", checkout, \"rev-parse\", \"HEAD^{commit}\"], root).stdout.trim(); const ctx = { args: { project: root, pmId: \"tpm\", dispatchId: id, pmStep: stepFile }, deps: { runScript: (script, args, env) => run([\"bun\", script, ...args], root, env), gitRun: (cwd, args) => run([\"git\", \"-C\", cwd, ...args], cwd), now: () => new Date(), gateRecoveryCommand: () => null }, project: root, container, checkout, lane: join(container, \"lane\"), pmRoot: join(root, \"__garelier\", \"tpm\"), scripts: dirname(pipelinePath), context, workId: `W-${id.padStart(3, \"0\")}`, stages: [], spawns: [], preserved: [] }; const result = stagePmStep(ctx, head); if (result?.status !== \"GREEN\") throw new Error(`declared PM step did not turn GREEN: ${JSON.stringify(result)}`); const log = readFileSync(result.log, \"utf8\"); const record = gateRunRecordPath(root, \"tpm\", result.log); if (!log.includes(\"PM_STEP_BINDING \")) throw new Error(\"PM step log lacks pipeline path/digest binding\"); if (!existsSync(record)) throw new Error(`gate_runner did not publish PM step run record: ${record}`); console.log(`DECLARED_PM_STEP_GREEN log=${result.log} record=${record}`);' \"$DT\" \"$id\" \"$LP\" \"$GATE_RUN_RECORD\" || fail \"declared PM step $id failed\"",
  "}",
  "",
  "# W-053: run this whole file from a throwaway scratch cwd, never from the",
  "# invoker's real cwd (target project 実戦 2026-07-12: a literal `$DT/…` dir",
  "# was found sitting in a real project root — every case below already scopes",
  "# its OWN fixture under `mktemp -d` ($TMP/$DT), but the top-level process cwd",
  "# itself was still whatever the invoker launched this script from; any future",
  "# latent bug in $ML/$CLEANUP that resolves a path against cwd instead of its",
  "# --project/--target-root argument would land there). This is pure isolation,",
  "# not a fix for a reproduced leak in the fixtures below (none found on",
  "# inspection — see references/stray-var-dir-leak.md); assert_no_cwd_residue",
  "# below is the self-detecting backstop in case that analysis is ever wrong.",
  "RUN_CWD=\"$(mktemp -d)\"",
  "cd \"$RUN_CWD\"",
  "",
  "# W-053 (c): self-detect a recurrence — fail loudly if anything landed in the",
  "# ORIGINAL invoker cwd (not $RUN_CWD, not a fixture's own $TMP) by the time",
  "# this script exits, success or failure. A literal `$`-prefixed name is the",
  "# specific signature of an unexpanded-variable leak; report it, don't clean it",
  "# silently, so the run stays evidence for triage.",
  "assert_no_cwd_residue() {",
  "  local stray",
  "  stray=\"$(find \"$ORIG_CWD\" -maxdepth 1 -name '$*' 2>/dev/null)\"",
  "  if [ -n \"$stray\" ]; then",
  "    echo \"  FAIL: stray literal \\$VAR dir(s) leaked into invoker cwd $ORIG_CWD:\" >&2",
  "    printf '%s\\n' \"$stray\" >&2",
  "    return 1",
  "  fi",
  "  return 0",
  "}",
  "trap 'rc=$?; rm -rf \"$RUN_CWD\" 2>/dev/null || true; assert_no_cwd_residue || rc=1; exit $rc' EXIT",
  "",
  "# mk_fixture <slug> <id> -> sets TMP (posix) + DT (windows-usable path). A git repo",
  "# with studio + a workbench branch (one commit) + setup_config + a _crew/dispatch<id>",
  "# worktree, ready for a merge gate run.",
  "mk_fixture() {",
  "  local slug=\"$1\" id=\"$2\"",
  "  TMP=\"$(mktemp -d)\"; DT=\"$(cygpath -m \"$TMP\" 2>/dev/null || printf '%s' \"$TMP\")\"",
  "  (",
  "    cd \"$TMP\"",
  "    git init -q -b main; git config user.email ci@ci; git config user.name t",
  "    echo base > base.txt; git add -A; git commit -q -m init",
  "    git branch \"garelier/main/tpm/studio\" main",
  "    git worktree add -q -b \"garelier/main/tpm/workbench/#$id/$slug\" \"wb\" \"garelier/main/tpm/studio\"",
  "    ( cd wb && echo feat > \"$slug.txt\" && git add -A && git commit -q -m \"feat $slug\" )",
  "    git worktree remove wb",
  "    mkdir -p \"__garelier/tpm/_crew/pm\"",
  "    printf '[project]\\nname = \"test\"\\n\\n[branches]\\ntarget = \"main\"\\nintegration = \"garelier/main/tpm/studio\"\\n' \\",
  "      > \"__garelier/tpm/_crew/pm/setup_config.toml\"",
  "    seed_control",
  "    bind_control \"$id\"",
  "    git worktree add -q \"__garelier/tpm/_crew/dispatch$id/checkout\" \"garelier/main/tpm/workbench/#$id/$slug\"",
  "    printf '# Report - #%s %s\\n' \"$id\" \"$slug\" > \"__garelier/tpm/_crew/dispatch$id/report.md\"",
  "    write_self_context \"$id\"",
  "    # commit_mode=self (guardian round-3 N1): a real dispatch_prepare-created",
  "    # container always carries context.json; these fixtures simulate a plain",
  "    # (non-proxy) worker dispatch, so the seat-trailer preflight must see self,",
  "    # not treat the container as unresolvable and fail closed.",
  "  )",
  "}",
  "cleanup_fixture() { cd /; rm -rf \"$TMP\" 2>/dev/null || true; }",
  "",
  "# add_run <slug> <id> — add ANOTHER workbench branch + _crew/dispatch<id> to the",
  "# CURRENT $TMP repo (created by mk_fixture), so one fixture can host several",
  "# dispatches for a batch-land test.",
  "add_run() {",
  "  local slug=\"$1\" id=\"$2\"",
  "  (",
  "    cd \"$TMP\"",
  "    bind_control \"$id\"",
  "    git worktree add -q -b \"garelier/main/tpm/workbench/#$id/$slug\" \"wb$id\" \"garelier/main/tpm/studio\"",
  "    ( cd \"wb$id\" && echo feat > \"$slug.txt\" && git add -A && git commit -q -m \"feat $slug\" )",
  "    git worktree remove \"wb$id\"",
  "    git worktree add -q \"__garelier/tpm/_crew/dispatch$id/checkout\" \"garelier/main/tpm/workbench/#$id/$slug\"",
  "    printf '# Report - #%s %s\\n' \"$id\" \"$slug\" > \"__garelier/tpm/_crew/dispatch$id/report.md\"",
  "    write_self_context \"$id\"",
  "  )",
  "}",
  "",
  "# mk_fixture_lock <slug> <id> <relpath> — like mk_fixture, but the workbench adds",
  "# <relpath> (to drive the merge gate's data-only classification) and the config",
  "# declares the W-031 data-only fast path + the heavy_compile lock, so the W-024",
  "# gate_mode→lock-skip behavior can be observed end to end.",
  "mk_fixture_lock() {",
  "  local slug=\"$1\" id=\"$2\" rel=\"$3\"",
  "  TMP=\"$(mktemp -d)\"; DT=\"$(cygpath -m \"$TMP\" 2>/dev/null || printf '%s' \"$TMP\")\"",
  "  (",
  "    cd \"$TMP\"",
  "    git init -q -b main; git config user.email ci@ci; git config user.name t",
  "    echo base > base.txt; git add -A; git commit -q -m init",
  "    git branch \"garelier/main/tpm/studio\" main",
  "    git worktree add -q -b \"garelier/main/tpm/workbench/#$id/$slug\" \"wb\" \"garelier/main/tpm/studio\"",
  "    ( cd wb && mkdir -p \"$(dirname \"$rel\")\" && echo feat > \"$rel\" && git add -A && git commit -q -m \"feat $slug\" )",
  "    git worktree remove wb",
  "    mkdir -p \"__garelier/tpm/_crew/pm\"",
  "    printf '[project]\\nname = \"test\"\\n\\n[branches]\\ntarget = \"main\"\\nintegration = \"garelier/main/tpm/studio\"\\n\\n[heavy_compile]\\nenabled = true\\nmax_concurrent = 1\\n\\n[merge_gate]\\ndata_only_paths = [\"docs/**\"]\\ndata_only_commands = [\"true\"]\\n' \\",
  "      > \"__garelier/tpm/_crew/pm/setup_config.toml\"",
  "    seed_control",
  "    bind_control \"$id\"",
  "    git worktree add -q \"__garelier/tpm/_crew/dispatch$id/checkout\" \"garelier/main/tpm/workbench/#$id/$slug\"",
  "    printf '# Report - #%s %s\\n' \"$id\" \"$slug\" > \"__garelier/tpm/_crew/dispatch$id/report.md\"",
  "    write_self_context \"$id\"",
  "  )",
  "}",
  "HEAVY_LOCK_REL=\"__garelier/tpm/runtime/locks/heavy_compile\"",
  "",
  "# ── 1. SUCCESS ────────────────────────────────────────────────────────────────",
  "FIXTURE_PRESERVATION=1 FIXTURE_DECLARED_PM_STEP=1 mk_fixture land-ok 1",
  "run_declared_pm_step 1",
  "set +e",
  "OUT=\"$(bun \"$ML\" --project \"$DT\" --target-root \"$DT\" --pm-id tpm \\",
  "  --branch \"garelier/main/tpm/workbench/#1/land-ok\" --guardian PASS \\",
  "  --quality-gate 'true' --no-pull --max-wait 90 --poll-interval 2 2>\"$TMP/land-ok.err\")\"",
  "RC=$?",
  "set -e",
  "[ \"$RC\" -eq 0 ] || fail \"success case exit was $RC (expected 0). summary=$OUT stderr=$(cat \"$TMP/land-ok.err\")\"",
  "echo \"$OUT\" | grep -q '\"status\":\"success\"' || fail \"success summary lacks status=success: $OUT\"",
  "echo \"$OUT\" | grep -q '\"cleanup_status\":\"success\"' || fail \"success summary lacks cleanup_status=success: $OUT\"",
  "echo \"$OUT\" | grep -q '\"branch_deleted\":true' || fail \"success summary lacks branch_deleted=true: $OUT\"",
  "[ ! -e \"$TMP/__garelier/tpm/_crew/dispatch1\" ] || fail \"success case retained dispatch container residue\"",
  "echo \"$OUT\" | grep -q '\"settlement_commit\":\"[0-9a-f]' || fail \"success summary lacks settlement commit: $OUT\"",
  "[ -z \"$(git -C \"$TMP\" status --porcelain -- __garelier/tpm/control/reports)\" ] || fail \"success case left uncommitted Control reports\"",
  "[ -z \"$(find \"$TMP/__garelier/tpm\" -maxdepth 1 -type d -name '.control.txn-*' -print -quit)\" ] || fail \"success case left Control transaction staging residue\"",
  "[ -f \"$TMP/__garelier/tpm/runtime/land_aftercare/retired_dispatches/1.json\" ] || fail \"success case lacks the authenticated logical-retirement marker\"",
  "# W-843 AC-1: the aftercare published this land's gate evidence after the",
  "# settlement write set was authorized; the ordinary land settles it from the",
  "# aftercare's own path + digest return, with no PM hand commit.",
  "PRESERVED_TRACKED=\"$(git -C \"$TMP\" ls-files -- __garelier/tpm/control/reports/gates/W-001/dispatch1)\"",
  "echo \"$PRESERVED_TRACKED\" | grep -q '/dispatch1/security_admission\\.json$' || fail \"success case did not settle the preservation admission: $PRESERVED_TRACKED stderr=$(cat \"$TMP/land-ok.err\")\"",
  "echo \"$PRESERVED_TRACKED\" | grep -q '/dispatch1/run_records/.*/payload$' || fail \"success case did not settle the preserved gate run record: $PRESERVED_TRACKED\"",
  "echo \"$PRESERVED_TRACKED\" | grep -q '/dispatch1/gate-step4-[0-9a-f]\\{12\\}\\.log$' || fail \"success case did not settle the preserved PM-step record: $PRESERVED_TRACKED\"",
  "grep -q '\"authority\": \"generated:aftercare-preservation:' \"$TMP\"/__garelier/tpm/runtime/land_aftercare/settlement/*.json || fail \"settlement manifest does not bind the aftercare writes to their generator\"",
  "[ -z \"$(git -C \"$TMP\" branch --list '*workbench*')\" ] || fail \"success case did not delete the workbench branch\"",
  "git -C \"$TMP\" cat-file -e garelier/main/tpm/studio:land-ok.txt 2>/dev/null || fail \"success case did not land the merge onto studio\"",
  "cleanup_fixture",
  "",
  "# ── CONTROL CAP PREFLIGHT: refuse before merge, preserve studio exactly ─────",
  "mk_fixture preflight-cap 60",
  "CAP_HEAD_BEFORE=\"$(git -C \"$TMP\" rev-parse garelier/main/tpm/studio)\"",
  "mkdir -p \"$TMP/__garelier/tpm/control/reports/gates/W-060/cap\"",
  "bun -e 'import { truncateSync, writeFileSync } from \"node:fs\"; import { join } from \"node:path\"; const root=process.argv[1]; for(let i=0;i<9;i++){ const path=join(root, `cap-${i}.bin`); writeFileSync(path, \"\"); truncateSync(path, 15*1024*1024); }' \"$DT/__garelier/tpm/control/reports/gates/W-060/cap\"",
  "set +e",
  "OUT=\"$(bun \"$ML\" --project \"$DT\" --target-root \"$DT\" --pm-id tpm \\",
  "  --branch \"garelier/main/tpm/workbench/#60/preflight-cap\" --guardian PASS \\",
  "  --quality-gate 'true' --no-pull --max-wait 90 --poll-interval 2 2>\"$TMP/preflight-cap.err\")\"",
  "RC=$?",
  "set -e",
  "[ \"$RC\" -ne 0 ] || fail \"cap-over preflight unexpectedly landed: $OUT\"",
  "echo \"$OUT\" | grep -q '\"status\":\"preflight_refused\"' || fail \"cap-over lacks preflight refusal: $OUT\"",
  "echo \"$OUT\" | grep -q '\"studio_unchanged\":true' || fail \"cap-over lacks studio invariant: $OUT\"",
  "grep -q 'control-tree-too-large' \"$TMP/preflight-cap.err\" || fail \"cap-over lacks capacity reason: $(cat \"$TMP/preflight-cap.err\")\"",
  "grep -q 'NEXT_COMMAND:' \"$TMP/preflight-cap.err\" || fail \"cap-over lacks recovery command\"",
  "[ \"$(git -C \"$TMP\" rev-parse garelier/main/tpm/studio)\" = \"$CAP_HEAD_BEFORE\" ] || fail \"cap-over moved studio before refusal\"",
  "cleanup_fixture",
  "",
  "# ── CONTROL SETTLEMENT RESERVE: below hard cap but no settlement room ─────",
  "mk_fixture preflight-reserve 59",
  "RESERVE_HEAD_BEFORE=\"$(git -C \"$TMP\" rev-parse garelier/main/tpm/studio)\"",
  "mkdir -p \"$TMP/__garelier/tpm/control/reports/gates/W-059/reserve\"",
  "bun -e 'import { truncateSync, writeFileSync } from \"node:fs\"; import { join } from \"node:path\"; const root=process.argv[1]; for(let i=0;i<8;i++){ const path=join(root, `reserve-${i}.bin`); writeFileSync(path, \"\"); truncateSync(path, 15*1024*1024); }' \"$DT/__garelier/tpm/control/reports/gates/W-059/reserve\"",
  "set +e",
  "OUT=\"$(bun \"$ML\" --project \"$DT\" --target-root \"$DT\" --pm-id tpm \\",
  "  --branch \"garelier/main/tpm/workbench/#59/preflight-reserve\" --guardian PASS \\",
  "  --quality-gate 'true' --no-pull --max-wait 90 --poll-interval 2 2>\"$TMP/preflight-reserve.err\")\"",
  "RC=$?",
  "set -e",
  "[ \"$RC\" -ne 0 ] || fail \"reserve preflight unexpectedly landed: $OUT\"",
  "grep -q 'settlement projection' \"$TMP/preflight-reserve.err\" || fail \"reserve refusal did not exercise projected capacity: $(cat \"$TMP/preflight-reserve.err\")\"",
  "[ \"$(git -C \"$TMP\" rev-parse garelier/main/tpm/studio)\" = \"$RESERVE_HEAD_BEFORE\" ] || fail \"reserve refusal moved studio\"",
  "cleanup_fixture",
  "",
  "# ── FINALIZE-ONLY: landed merge resumes after settlement interruption ───────",
  "FIXTURE_PRESERVATION=1 FIXTURE_DECLARED_PM_STEP=1 mk_fixture finalize-only 3",
  "run_declared_pm_step 3",
  "mkdir -p \"$TMP/__garelier/tpm/.control.txn-interrupted\"",
  "printf 'operator-owned interrupted transaction state\\n' > \"$TMP/__garelier/tpm/.control.txn-interrupted/owner.txt\"",
  "set +e",
  "OUT=\"$(bun \"$ML\" --project \"$DT\" --target-root \"$DT\" --pm-id tpm \\",
  "  --branch \"garelier/main/tpm/workbench/#3/finalize-only\" --guardian PASS \\",
  "  --quality-gate 'true' --no-pull --max-wait 90 --poll-interval 2 2>\"$TMP/finalize-only-first.err\")\"",
  "RC=$?",
  "set -e",
  "[ \"$RC\" -ne 0 ] || fail \"interrupted settlement unexpectedly completed: $OUT\"",
  "git -C \"$TMP\" cat-file -e garelier/main/tpm/studio:finalize-only.txt 2>/dev/null || fail \"interrupted settlement did not land candidate: $OUT stderr=$(cat \"$TMP/finalize-only-first.err\")\"",
  "[ ! -e \"$TMP/__garelier/tpm/_crew/dispatch3\" ] || fail \"interrupted post-cleanup settlement retained the dispatch container\"",
  "grep -q 'Control transaction residue remains: .control.txn-interrupted' \"$TMP/finalize-only-first.err\" || fail \"interrupted settlement did not name its retained transaction residue: $(cat \"$TMP/finalize-only-first.err\")\"",
  "grep -q 'NEXT_COMMAND: bun .*control.ts doctor --profile strict' \"$TMP/finalize-only-first.err\" || fail \"transaction residue did not emit its inspection command: $(cat \"$TMP/finalize-only-first.err\")\"",
  "grep -q 'AFTER_RECOVERY: bun .*merge_land.ts .*--finalize-only' \"$TMP/finalize-only-first.err\" || fail \"transaction residue did not emit the settlement continuation: $(cat \"$TMP/finalize-only-first.err\")\"",
  "FINALIZE_RECOVERY_CMD=\"$(sed -n 's/^AFTER_RECOVERY: //p' \"$TMP/finalize-only-first.err\" | tail -1)\"",
  "[ -n \"$FINALIZE_RECOVERY_CMD\" ] || fail \"transaction residue did not yield a runnable settlement continuation\"",
  "rm -rf \"$TMP/__garelier/tpm/.control.txn-interrupted\"",
  "REQ=\"$(find \"$TMP/__garelier/tpm/runtime/merge_gate/results\" -type f -name '*.json' -printf '%f\\n' | sed 's/\\.json$//' | head -1)\"",
  "[ -n \"$REQ\" ] || fail \"interrupted settlement request id not found\"",
  "mv \"$TMP/__garelier/tpm/runtime/merge_gate/results/$REQ.json\" \"$TMP/__garelier/tpm/runtime/merge_gate/archive/$REQ.result.json\"",
  "# W-843: the #649 shape — merge landed, the aftercare already published this",
  "# land's gate records into Control, and the settlement has not committed them.",
  "PUBLICATION=\"$TMP/__garelier/tpm/runtime/land_aftercare/preservation_publications/$REQ.json\"",
  "[ -f \"$PUBLICATION\" ] || fail \"the aftercare returned no preservation publication record: $(cat \"$TMP/finalize-only-first.err\")\"",
  "PRESERVED_ROOT=__garelier/tpm/control/reports/gates/W-003/dispatch3",
  "[ \"$(git -C \"$TMP\" ls-files --others --exclude-standard -- \"$PRESERVED_ROOT\" | wc -l)\" -eq 3 ] || fail \"interrupted settlement did not leave the three uncommitted gate records: $(git -C \"$TMP\" status --porcelain -- \"$PRESERVED_ROOT\")\"",
  "SETTLEMENT_AUTHORIZATION=\"$TMP/__garelier/tpm/runtime/land_aftercare/settlement_authorizations/$REQ.json\"",
  "cp \"$SETTLEMENT_AUTHORIZATION\" \"$TMP/finalize-only.authorization.json\"",
  "BROKEN_RENEWAL=\"$TMP/__garelier/tpm/control/reports/claim_renewals/W-003/ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff.json\"",
  "bun -e 'import { mkdirSync, writeFileSync } from \"node:fs\"; import { dirname } from \"node:path\"; const path=process.argv[1]; mkdirSync(dirname(path),{recursive:true}); writeFileSync(path, Buffer.from([0]));' \"$BROKEN_RENEWAL\"",
  "MALFORMED_RENEWAL=\"$TMP/__garelier/tpm/control/reports/claim_renewals/W-003/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.json\"",
  "LEAK_IDENTIFIER='SYNTHETIC_PRIVATE_IDENTIFIER_W842'",
  "bun -e 'import { writeFileSync } from \"node:fs\"; const [path, identifier]=process.argv.slice(1); writeFileSync(path, `{\"x\":${identifier}}`);' \"$MALFORMED_RENEWAL\" \"$LEAK_IDENTIFIER\"",
  "# W-843 AC-3: a well-formed record bound to this request whose bytes are not",
  "# what its content-addressed name says is a CONTENT defect -> invalid_record.",
  "IDENTITY_RENEWAL=\"$TMP/__garelier/tpm/control/reports/claim_renewals/W-003/dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd.json\"",
  "printf '{\"kind\":\"claim_renewal_authorization\",\"request_id\":\"%s\"}\\n' \"$REQ\" > \"$IDENTITY_RENEWAL\"",
  "git -C \"$TMP\" add -- \"$BROKEN_RENEWAL\" \"$MALFORMED_RENEWAL\" \"$IDENTITY_RENEWAL\"",
  "git -C \"$TMP\" commit -q -m 'fixture committed corrupt unrelated renewal'",
  "git -C \"$TMP\" update-ref refs/heads/garelier/main/tpm/studio HEAD",
  "PREFLIGHT_RECEIPT=\"$TMP/__garelier/tpm/runtime/land_aftercare/preflight/W-003.json\"",
  "cp \"$PREFLIGHT_RECEIPT\" \"$TMP/finalize-only.preflight.json\"",
  "mkdir -p \"$TMP/__garelier/tpm/control/reports\"",
  "printf 'unreviewed concurrent Control bytes\\n' > \"$TMP/__garelier/tpm/control/reports/unbound-settlement.txt\"",
  "set +e",
  "OUT=\"$(bun \"$ML\" --project \"$DT\" --target-root \"$DT\" --pm-id tpm --finalize-only --request-id \"$REQ\" --no-pull 2>\"$TMP/finalize-only-unbound.err\")\"",
  "UNBOUND_RC=$?",
  "set -e",
  "[ \"$UNBOUND_RC\" -ne 0 ] || fail \"finalize-only committed an unbound Control path: $OUT\"",
  "grep -q 'control settlement refuses unbound Control paths: __garelier/tpm/control/reports/unbound-settlement.txt$' \"$TMP/finalize-only-unbound.err\" || fail \"unbound Control path refusal missing: $(cat \"$TMP/finalize-only-unbound.err\")\"",
  "[ -f \"$TMP/__garelier/tpm/control/reports/unbound-settlement.txt\" ] || fail \"unbound Control source was not preserved on refusal\"",
  "[ -z \"$(git -C \"$TMP\" diff --cached --name-only)\" ] || fail \"unbound settlement changed the index before refusal\"",
  "rm \"$TMP/__garelier/tpm/control/reports/unbound-settlement.txt\"",
  "WORK_PATH=\"$TMP/__garelier/tpm/control/backlog/open/W-003-runtime.md\"",
  "cp \"$WORK_PATH\" \"$TMP/authorized-work.before\"",
  "printf '\\nunreviewed same-path bytes\\n' >> \"$WORK_PATH\"",
  "set +e",
  "OUT=\"$(bun \"$ML\" --project \"$DT\" --target-root \"$DT\" --pm-id tpm --finalize-only --request-id \"$REQ\" --no-pull 2>\"$TMP/finalize-only-digest.err\")\"",
  "DIGEST_RC=$?",
  "set -e",
  "[ \"$DIGEST_RC\" -ne 0 ] || fail \"finalize-only committed changed bytes at an authenticated path: $OUT\"",
  "grep -q 'control settlement authenticated digest changed: __garelier/tpm/control/backlog/open/W-003-runtime.md' \"$TMP/finalize-only-digest.err\" || fail \"same-path digest refusal missing: $(cat \"$TMP/finalize-only-digest.err\")\"",
  "grep -q 'unreviewed same-path bytes' \"$WORK_PATH\" || fail \"same-path source was not preserved on refusal\"",
  "[ -z \"$(git -C \"$TMP\" diff --cached --name-only)\" ] || fail \"same-path digest refusal changed the index\"",
  "cp \"$TMP/authorized-work.before\" \"$WORK_PATH\"",
  "# W-843 AC-1, other direction: take away the aftercare's return and exactly",
  "# its three gate records fall out of the write set and are refused as unbound.",
  "mv \"$PUBLICATION\" \"$TMP/publication.aside\"",
  "set +e",
  "OUT=\"$(bun \"$ML\" --project \"$DT\" --target-root \"$DT\" --pm-id tpm --finalize-only --request-id \"$REQ\" --no-pull 2>\"$TMP/finalize-only-no-generator.err\")\"",
  "NO_GENERATOR_RC=$?",
  "set -e",
  "[ \"$NO_GENERATOR_RC\" -ne 0 ] || fail \"finalize-only settled gate records without their generator's return: $OUT\"",
  "grep -q \"control settlement refuses unbound Control paths: $PRESERVED_ROOT/gate-step4-[0-9a-f]\\{12\\}\\.log, $PRESERVED_ROOT/run_records/[0-9a-f/]*/payload, $PRESERVED_ROOT/security_admission\\.json$\" \"$TMP/finalize-only-no-generator.err\" || fail \"generator-less settlement did not refuse exactly the aftercare's gate records: $(cat \"$TMP/finalize-only-no-generator.err\")\"",
  "[ -z \"$(git -C \"$TMP\" diff --cached --name-only)\" ] || fail \"generator-less refusal changed the index\"",
  "mv \"$TMP/publication.aside\" \"$PUBLICATION\"",
  "# W-843 AC-3: a returned path that does not resolve inside Control is a path",
  "# failure, reported as unresolved_path — not as a content defect.",
  "bun -e 'import { readFileSync, writeFileSync } from \"node:fs\"; const path = process.argv[1]; const record = JSON.parse(readFileSync(path, \"utf8\")); record.writes.push({ path: \"../outside-control.json\", digest: `sha256:${\"0\".repeat(64)}` }); writeFileSync(path, JSON.stringify(record));' \"$PUBLICATION\"",
  "bun -e 'import { pathToFileURL } from \"node:url\"; import { mkdirSync, writeFileSync } from \"node:fs\"; import { join } from \"node:path\"; const [root, requestId, serializationPath] = process.argv.slice(1); const { canonicalJson, sha256 } = await import(pathToFileURL(serializationPath).href); const source=canonicalJson({ schema_version:1, control_schema_version:3, kind:\"claim_renewal_authorization\", authorization_status:\"authorized\", work_id:\"W-003\", session_id:\"cs_lane_3\", actor:\"fixture\", observed_at:\"2026-09-21T00:00:00.000Z\", source:\"merge-settlement\", request_id:requestId, reason:\"merge-bound Control settlement after gate execution\", previous_expires_at:\"2026-09-21T00:00:00.000Z\", authorized_expires_at:\"2026-09-21T01:00:00.000Z\", touches:[], authority_refresh:null }); const digest=sha256(source); const file=`${digest.replace(/^sha256:/, \"\")}.json`; const dir=join(root, \"__garelier\", \"tpm\", \"control\", \"reports\", \"claim_renewals\", \"W-003\"); mkdirSync(dir,{recursive:true}); writeFileSync(join(dir, file), source);' \"$DT\" \"$REQ\" \"$CONTROL_SERIALIZATION\"",
  "[ \"$(find \"$TMP/__garelier/tpm/control/reports/claim_renewals/W-003\" -type f -name '*.json' | wc -l)\" -eq 4 ] || fail \"finalize-only recovery fixture did not retain three committed corrupt files plus one bound output\"",
  "[ \"$(git -C \"$TMP\" ls-files --others --exclude-standard -- __garelier/tpm/control/reports/claim_renewals/W-003 | wc -l)\" -eq 1 ] || fail \"finalize-only recovery fixture did not inject exactly one untracked bound claim renewal output\"",
  "set +e",
  "OUT=\"$(\"$BASH\" -lc \"$FINALIZE_RECOVERY_CMD\" 2>\"$TMP/finalize-only-resume.err\")\"",
  "FINALIZE_RC=$?",
  "set -e",
  "[ \"$FINALIZE_RC\" -eq 0 ] || fail \"finalize-only exited $FINALIZE_RC: $OUT stderr=$(cat \"$TMP/finalize-only-resume.err\")\"",
  "echo \"$OUT\" | grep -q '\"mode\":\"finalize-only\"' || fail \"finalize-only summary missing mode: $OUT\"",
  "echo \"$OUT\" | grep -q '\"status\":\"success\"' || fail \"finalize-only did not complete: $OUT stderr=$(cat \"$TMP/finalize-only-resume.err\")\"",
  "grep -q 'skipped generated Control write reports/claim_renewals/W-003/ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff.json: unreadable' \"$TMP/finalize-only-resume.err\" || fail \"NUL-corrupt renewal was not named with a bounded skip reason: $(cat \"$TMP/finalize-only-resume.err\")\"",
  "grep -q 'skipped generated Control write reports/claim_renewals/W-003/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.json: invalid_json' \"$TMP/finalize-only-resume.err\" || fail \"malformed renewal was not named with a bounded skip reason: $(cat \"$TMP/finalize-only-resume.err\")\"",
  "grep -q 'skipped generated Control write reports/claim_renewals/W-003/dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd.json: invalid_record$' \"$TMP/finalize-only-resume.err\" || fail \"content-defective renewal was not reported as invalid_record: $(cat \"$TMP/finalize-only-resume.err\")\"",
  "grep -q 'skipped generated Control write \\.\\./outside-control\\.json: unresolved_path$' \"$TMP/finalize-only-resume.err\" || fail \"unresolvable returned path was not reported as unresolved_path: $(cat \"$TMP/finalize-only-resume.err\")\"",
  "[ \"$(git -C \"$TMP\" ls-files -- \"$PRESERVED_ROOT\" | wc -l)\" -eq 3 ] || fail \"finalize-only did not settle the aftercare's three gate records: $(git -C \"$TMP\" status --porcelain -- \"$PRESERVED_ROOT\")\"",
  "! grep -Fq \"$LEAK_IDENTIFIER\" \"$TMP/finalize-only-resume.err\" || fail \"malformed renewal content leaked to stderr\"",
  "! printf '%s' \"$OUT\" | grep -Fq \"$LEAK_IDENTIFIER\" || fail \"malformed renewal content leaked to stdout\"",
  "[ ! -e \"$TMP/__garelier/tpm/_crew/dispatch3\" ] || fail \"finalize-only retained container residue\"",
  "[ -z \"$(git -C \"$TMP\" status --porcelain -- __garelier/tpm/control/reports)\" ] || fail \"finalize-only left report residue\"",
  "[ -z \"$(find \"$TMP/__garelier/tpm\" -maxdepth 1 -type d -name '.control.txn-*' -print -quit)\" ] || fail \"finalize-only left Control transaction staging residue\"",
  "# A failure after the settlement commit but before its receipts are cleaned",
  "# up leaves this exact recovery shape: committed writes (canonical AND the",
  "# aftercare's gate records), the settlement authorization still naming them,",
  "# and the original preflight receipt. W-843 AC-2: the retry completes without",
  "# moving studio — an authenticated write already committed with its exact",
  "# bytes is settled, not a refusal.",
  "cp \"$TMP/finalize-only.preflight.json\" \"$PREFLIGHT_RECEIPT\"",
  "cp \"$TMP/finalize-only.authorization.json\" \"$SETTLEMENT_AUTHORIZATION\"",
  "STUDIO_BEFORE_RETRY=\"$(git -C \"$TMP\" rev-parse garelier/main/tpm/studio)\"",
  "set +e",
  "OUT=\"$(\"$BASH\" -lc \"$FINALIZE_RECOVERY_CMD\" 2>\"$TMP/finalize-only-post-commit.err\")\"",
  "POST_COMMIT_RC=$?",
  "set -e",
  "[ \"$POST_COMMIT_RC\" -eq 0 ] || fail \"post-commit finalize-only retry exited $POST_COMMIT_RC: $OUT stderr=$(cat \"$TMP/finalize-only-post-commit.err\")\"",
  "echo \"$OUT\" | grep -q '\"status\":\"success\"' || fail \"post-commit finalize-only retry did not complete: $OUT\"",
  "[ \"$(git -C \"$TMP\" rev-parse garelier/main/tpm/studio)\" = \"$STUDIO_BEFORE_RETRY\" ] || fail \"post-commit finalize-only retry moved studio\"",
  "[ ! -e \"$SETTLEMENT_AUTHORIZATION\" ] || fail \"post-commit retry left its settlement authorization behind\"",
  "[ -z \"$(git -C \"$TMP\" status --porcelain -- __garelier/tpm/control)\" ] || fail \"post-commit retry re-admitted an already committed Control write\"",
  "cleanup_fixture",
  "",
  "# ── 2. FAILURE ────────────────────────────────────────────────────────────────",
  "FIXTURE_GATE_COMMAND=false mk_fixture land-fail 2",
  "set +e",
  "OUT=\"$(bun \"$ML\" --project \"$DT\" --target-root \"$DT\" --pm-id tpm \\",
  "  --branch \"garelier/main/tpm/workbench/#2/land-fail\" --guardian PASS \\",
  "  --quality-gate 'false' --no-pull --max-wait 90 --poll-interval 2 2>/dev/null)\"",
  "RC=$?",
  "set -e",
  "[ \"$RC\" -ne 0 ] || fail \"failure case exit was 0 (expected non-zero). summary=$OUT\"",
  "echo \"$OUT\" | grep -q '\"status\":\"failed\"' || fail \"failure summary lacks status=failed: $OUT\"",
  "echo \"$OUT\" | grep -q '\"cleaned_up\":false' || fail \"failure summary lacks cleaned_up=false: $OUT\"",
  "[ -e \"$TMP/__garelier/tpm/_crew/dispatch2\" ] || fail \"failure case WRONGLY removed the dispatch container\"",
  "[ -n \"$(git -C \"$TMP\" branch --list '*workbench*')\" ] || fail \"failure case WRONGLY deleted the workbench branch\"",
  "cleanup_fixture",
  "",
  "# ── W-286 DIRTY STUDIO INDEX → fail before merge, preserve staged bytes ────",
  "mk_fixture dirty-index 43",
  "git -C \"$TMP\" checkout -q \"garelier/main/tpm/studio\"",
  "printf 'user-owned staged bytes\\n' > \"$TMP/unrelated-staged.txt\"",
  "git -C \"$TMP\" add -- unrelated-staged.txt",
  "INDEX_BEFORE=\"$(git -C \"$TMP\" diff --cached --binary | git hash-object --stdin)\"",
  "HEAD_BEFORE=\"$(git -C \"$TMP\" rev-parse HEAD)\"",
  "set +e",
  "OUT=\"$(bun \"$ML\" --project \"$DT\" --target-root \"$DT\" --pm-id tpm \\",
  "  --branch \"garelier/main/tpm/workbench/#43/dirty-index\" --guardian PASS \\",
  "  --quality-gate 'true' --no-pull --max-wait 90 --poll-interval 2 2>/dev/null)\"",
  "RC=$?",
  "set -e",
  "[ \"$RC\" -ne 0 ] || fail \"dirty-index case exit was 0 (expected non-zero). summary=$OUT\"",
  "echo \"$OUT\" | grep -q '\"status\":\"preflight_refused\"' || fail \"dirty-index summary lacks status=preflight_refused: $OUT\"",
  "echo \"$OUT\" | grep -q '\"studio_unchanged\":true' || fail \"dirty-index refusal lacks studio invariant: $OUT\"",
  "echo \"$OUT\" | grep -q 'unrelated-staged.txt' || fail \"dirty-index diagnostic lacks staged path: $OUT\"",
  "echo \"$OUT\" | grep -q 'diff --cached --name-status' || fail \"dirty-index diagnostic lacks safe inspection step: $OUT\"",
  "[ \"$(git -C \"$TMP\" rev-parse HEAD)\" = \"$HEAD_BEFORE\" ] || fail \"dirty-index case created a merge commit before refusing\"",
  "[ \"$(git -C \"$TMP\" diff --cached --binary | git hash-object --stdin)\" = \"$INDEX_BEFORE\" ] || fail \"dirty-index case changed or unstaged the user index\"",
  "[ \"$(git -C \"$TMP\" show :unrelated-staged.txt)\" = 'user-owned staged bytes' ] || fail \"dirty-index case changed staged bytes\"",
  "if git -C \"$TMP\" merge-base --is-ancestor \"garelier/main/tpm/workbench/#43/dirty-index\" \"garelier/main/tpm/studio\"; then",
  "  fail \"dirty-index case landed the workbench despite the dirty-index refusal\"",
  "fi",
  "cleanup_fixture",
  "",
  "# ── W-286 PRE-EXISTING MERGE → refuse and never abort user-owned state ─────",
  "mk_fixture preexisting-merge 44",
  "git -C \"$TMP\" worktree add -q -b user/preexisting-merge \"$TMP/user-merge-wt\" \"garelier/main/tpm/studio\"",
  "printf 'user merge bytes\\n' > \"$TMP/user-merge-wt/user-merge.txt\"",
  "git -C \"$TMP/user-merge-wt\" add -- user-merge.txt",
  "git -C \"$TMP/user-merge-wt\" commit -q -m 'user merge source'",
  "git -C \"$TMP\" worktree remove \"$TMP/user-merge-wt\"",
  "git -C \"$TMP\" checkout -q \"garelier/main/tpm/studio\"",
  "git -C \"$TMP\" merge --no-ff --no-commit user/preexisting-merge >/dev/null",
  "PREMERGE_INDEX=\"$(git -C \"$TMP\" diff --cached --binary | git hash-object --stdin)\"",
  "PREMERGE_HEAD=\"$(cat \"$TMP/.git/MERGE_HEAD\")\"",
  "PREMERGE_STUDIO_HEAD=\"$(git -C \"$TMP\" rev-parse HEAD)\"",
  "set +e",
  "OUT=\"$(bun \"$ML\" --project \"$DT\" --target-root \"$DT\" --pm-id tpm \\",
  "  --branch \"garelier/main/tpm/workbench/#44/preexisting-merge\" --guardian PASS \\",
  "  --quality-gate 'true' --no-pull --max-wait 90 --poll-interval 2 2>/dev/null)\"",
  "RC=$?",
  "set -e",
  "[ \"$RC\" -ne 0 ] || fail \"pre-existing-merge case exit was 0 (expected non-zero). summary=$OUT\"",
  "echo \"$OUT\" | grep -q 'pre-existing merge' || fail \"pre-existing-merge diagnostic missing: $OUT\"",
  "[ \"$(cat \"$TMP/.git/MERGE_HEAD\")\" = \"$PREMERGE_HEAD\" ] || fail \"pre-existing-merge refusal changed MERGE_HEAD\"",
  "[ \"$(git -C \"$TMP\" diff --cached --binary | git hash-object --stdin)\" = \"$PREMERGE_INDEX\" ] || fail \"pre-existing-merge refusal changed staged bytes\"",
  "[ \"$(git -C \"$TMP\" rev-parse HEAD)\" = \"$PREMERGE_STUDIO_HEAD\" ] || fail \"pre-existing-merge refusal changed HEAD\"",
  "",
  "# Signal after active.lock acquisition, while the gate still has no owned",
  "# MERGE_HEAD marker. The signal handler must report/clean its own lock only;",
  "# it must not abort the pre-existing user merge.",
  "SIG_REQ_DIR=\"$TMP/__garelier/tpm/runtime/merge_gate/requests\"",
  "SIG_RES_DIR=\"$TMP/__garelier/tpm/runtime/merge_gate/results\"",
  "SIG_LOG_DIR=\"$TMP/__garelier/tpm/runtime/merge_gate/logs\"",
  "SIG_LOCK=\"$TMP/__garelier/tpm/runtime/merge_gate/locks/active.lock\"",
  "mkdir -p \"$SIG_REQ_DIR\"",
  "cat > \"$SIG_REQ_DIR/w286-signal.json\" <<EOF",
  "{",
  "  \"request_id\": \"w286-signal\",",
  "  \"workbench_branch\": \"garelier/main/tpm/workbench/#44/preexisting-merge\",",
  "  \"studio_branch\": \"garelier/main/tpm/studio\",",
  "  \"merge_message\": \"merge W-286 signal fixture\",",
  "  \"target_root\": \"$DT\",",
  "  \"quality_gate_commands\": [\"true\"]",
  "}",
  "EOF",
  "bun \"$MG\" \"$SIG_REQ_DIR/w286-signal.json\" >/dev/null 2>&1 & SIG_PID=$!",
  "SIG_READY=0",
  "for _ in $(seq 1 20000); do",
  "  if [ -f \"$SIG_LOCK\" ]; then SIG_READY=1; break; fi",
  "  kill -0 \"$SIG_PID\" 2>/dev/null || break",
  "done",
  "[ \"$SIG_READY\" -eq 1 ] || fail \"early-signal fixture never observed active.lock before gate exit\"",
  "kill -TERM \"$SIG_PID\" 2>/dev/null || fail \"early-signal fixture could not deliver SIGTERM\"",
  "wait \"$SIG_PID\" 2>/dev/null || true",
  "# POSIX delivers SIGTERM to the registered handler; Windows Git Bash may map",
  "# kill to native process termination, which cannot execute JS cleanup. In the",
  "# handler-capable path, require the explicit unowned-merge skip oracle.",
  "if grep -qF 'cleanup_and_abort: signal=SIGTERM' \"$SIG_LOG_DIR/w286-signal.log\"; then",
  "  grep -qF 'this gate has no owned MERGE_HEAD marker' \"$SIG_LOG_DIR/w286-signal.log\" || fail \"early-signal cleanup did not prove the unowned-merge skip\"",
  "fi",
  "[ \"$(cat \"$TMP/.git/MERGE_HEAD\")\" = \"$PREMERGE_HEAD\" ] || fail \"early signal changed the pre-existing MERGE_HEAD\"",
  "[ \"$(git -C \"$TMP\" diff --cached --binary | git hash-object --stdin)\" = \"$PREMERGE_INDEX\" ] || fail \"early signal changed pre-existing staged bytes\"",
  "[ \"$(git -C \"$TMP\" rev-parse HEAD)\" = \"$PREMERGE_STUDIO_HEAD\" ] || fail \"early signal changed HEAD\"",
  "cleanup_fixture",
  "",
  "# ── 3. W-055 guard non-interference ───────────────────────────────────────────",
  "# A dispatch whose branch is already merged (FF into studio). A FOREIGN active.lock",
  "# (different slug) must NOT block its cleanup; the SAME-slug lock still must.",
  "mk_fixture guard-ok 3",
  "# Land an explicit ungated merge so schema-3 cleanup can durably acknowledge",
  "# the bypass while this case isolates the slug-specific active-lock guard.",
  "git -C \"$TMP\" checkout -q \"garelier/main/tpm/studio\"",
  "git -C \"$TMP\" merge -q --no-ff \"garelier/main/tpm/workbench/#3/guard-ok\" -m 'guard-ok ungated fixture'",
  "LOCK_DIR=\"$TMP/__garelier/tpm/runtime/merge_gate/locks\"",
  "mkdir -p \"$LOCK_DIR\"",
  "# (a) FOREIGN lock: names a DIFFERENT slug → guard must not fire → cleanup succeeds.",
  "printf '{\"pid\":999999,\"request_id\":\"other\",\"request_file\":\"other.json\",\"started_at\":\"x\",\"target_root\":\"%s\"}\\n' \"$DT\" \\",
  "  > \"$LOCK_DIR/active.lock\"",
  "set +e",
  "COUT=\"$(bun \"$CLEANUP\" --project \"$DT\" --target-root \"$DT\" --pm-id tpm --id 3 --checkout \"$DT/__garelier/tpm/_crew/dispatch3/checkout\" --delete-branch --accept-ungated-merge 2>\"$TMP/guard-ok.err\")\"",
  "CRC=$?",
  "set -e",
  "[ \"$CRC\" -eq 0 ] || fail \"guard case: cleanup refused with a FOREIGN active.lock (exit $CRC) — W-055 guard wrongly interfered. out=$COUT stderr=$(cat \"$TMP/guard-ok.err\")\"",
  "[ -z \"$(git -C \"$TMP\" branch --list '*workbench*')\" ] || fail \"guard case: branch not deleted despite merged + foreign lock\"",
  "cleanup_fixture",
  "",
  "# (b) Negative control: a SAME-slug lock must still REFUSE (guard is real, only",
  "# slug-specific). Fresh fixture (the previous one is cleaned).",
  "mk_fixture guard-block 4",
  "git -C \"$TMP\" checkout -q \"garelier/main/tpm/studio\"",
  "git -C \"$TMP\" merge -q --no-ff \"garelier/main/tpm/workbench/#4/guard-block\" -m 'guard-block ungated fixture'",
  "LOCK_DIR=\"$TMP/__garelier/tpm/runtime/merge_gate/locks\"",
  "mkdir -p \"$LOCK_DIR\"",
  "printf '{\"pid\":999999,\"request_id\":\"x-guard-block\",\"request_file\":\"x-guard-block.json\",\"started_at\":\"x\",\"target_root\":\"%s\"}\\n' \"$DT\" \\",
  "  > \"$LOCK_DIR/active.lock\"",
  "set +e",
  "COUT=\"$(bun \"$CLEANUP\" --project \"$DT\" --target-root \"$DT\" --pm-id tpm --id 4 --checkout \"$DT/__garelier/tpm/_crew/dispatch4/checkout\" --delete-branch --accept-ungated-merge 2>/dev/null)\"",
  "CRC=$?",
  "set -e",
  "[ \"$CRC\" -eq 3 ] || fail \"guard case (negative): cleanup with a SAME-slug lock exited $CRC (expected 3 REFUSE) — the W-055 guard is not firing. out=$COUT\"",
  "[ -n \"$(git -C \"$TMP\" branch --list '*workbench*')\" ] || fail \"guard case (negative): branch was deleted despite the same-slug lock\"",
  "cleanup_fixture",
  "",
  "# ── W-017 argument-UX cases ─────────────────────────────────────────────────────",
  "",
  "# ── 7. --dispatch-id resolves branch + Guardian verdict auto-read (no --branch,",
  "#      no --guardian) → still lands end-to-end ────────────────────────────────────",
  "# Proves both (a) branch resolution from the dispatch container's checkout HEAD and",
  "# (c) verdict auto-read from the `[verdict] result` front matter: the merge could ONLY reach the",
  "# gate (and land) if pre-validation resolved a branch AND a passing Guardian verdict",
  "# from files alone. A guardian marker is planted at the dispatch_prepare-convention",
  "# path; --id is the alias (the exact flag the PM tried in the live failure).",
  "mk_fixture land-autoid 8",
  "mkdir -p \"$TMP/$GREL/tpm/runtime/guardian/results\"",
  "REVIEW_SHA=\"$(git -C \"$TMP\" rev-parse 'garelier/main/tpm/workbench/#8/land-autoid')\"",
  "printf '+++\\n[verdict]\\nresult = '\\''PASS'\\''\\nreview_sha = '\\''%s'\\''\\n+++\\n' \"$REVIEW_SHA\" > \"$TMP/$GREL/tpm/runtime/guardian/results/land-autoid-guardian.md\"",
  "ERRF=\"$(mktemp)\"",
  "set +e",
  "OUT=\"$(bun \"$ML\" --project \"$DT\" --target-root \"$DT\" --pm-id tpm \\",
  "  --id 8 --quality-gate 'true' --no-pull --max-wait 90 --poll-interval 2 2>\"$ERRF\")\"",
  "RC=$?",
  "set -e",
  "[ \"$RC\" -eq 0 ] || fail \"autoid case exit was $RC (expected 0). summary=$OUT stderr=$(cat \"$ERRF\")\"",
  "echo \"$OUT\" | grep -q '\"status\":\"success\"' || fail \"autoid summary lacks status=success: $OUT\"",
  "echo \"$OUT\" | grep -q '\"branch_deleted\":true' || fail \"autoid summary lacks branch_deleted=true: $OUT\"",
  "grep -qF 'resolved --branch garelier/main/tpm/workbench/#8/land-autoid from dispatch #8' \"$ERRF\" \\",
  "  || fail \"autoid case did not log branch resolution from --dispatch-id: $(cat \"$ERRF\")\"",
  "grep -qF \"auto-read Guardian verdict 'PASS'\" \"$ERRF\" \\",
  "  || fail \"autoid case did not log Guardian verdict auto-read: $(cat \"$ERRF\")\"",
  "git -C \"$TMP\" cat-file -e garelier/main/tpm/studio:land-autoid.txt 2>/dev/null \\",
  "  || fail \"autoid case did not land the merge onto studio\"",
  "rm -f \"$ERRF\"",
  "cleanup_fixture",
  "",
  "# ── 8. Pre-validation reports EVERY missing required input at once + usage ───────",
  "# No --branch/--dispatch-id AND no --guardian: the old flow failed one arg at a time",
  "# only at submit; now both are reported together with usage, before any submit.",
  "mk_fixture land-preval 9",
  "set +e",
  "ERR=\"$(bun \"$ML\" --project \"$DT\" --target-root \"$DT\" --pm-id tpm --work-id W-009 --control-session cs_lane_9 2>&1 1>/dev/null)\"",
  "RC=$?",
  "set -e",
  "[ \"$RC\" -eq 2 ] || fail \"pre-validation missing-all exit was $RC (expected 2). out=$ERR\"",
  "echo \"$ERR\" | grep -qF 'cannot submit' || fail \"pre-validation lacks the batch header: $ERR\"",
  "echo \"$ERR\" | grep -qi 'branch' || fail \"pre-validation did not report the missing branch: $ERR\"",
  "echo \"$ERR\" | grep -qF 'Guardian verdict required' || fail \"pre-validation did not report the missing Guardian verdict: $ERR\"",
  "echo \"$ERR\" | grep -qF 'Usage:' || fail \"pre-validation did not print usage: $ERR\"",
  "cleanup_fixture",
  "",
  "# ── 9. --id to a nonexistent container fails clearly (before submit), and --id is",
  "#      an accepted alias (a provided --guardian is NOT spuriously flagged) ─────────",
  "mk_fixture land-badid 10",
  "set +e",
  "ERR=\"$(bun \"$ML\" --project \"$DT\" --target-root \"$DT\" --pm-id tpm --id 999 --guardian PASS 2>&1 1>/dev/null)\"",
  "RC=$?",
  "set -e",
  "[ \"$RC\" -eq 2 ] || fail \"--id nonexistent exit was $RC (expected 2). out=$ERR\"",
  "echo \"$ERR\" | grep -qF 'schema-v3 dispatch context is missing' || fail \"--id nonexistent lacks the canonical context-not-found error: $ERR\"",
  "echo \"$ERR\" | grep -qF 'Guardian verdict required' && fail \"--id nonexistent WRONGLY flagged the provided --guardian: $ERR\"",
  "cleanup_fixture",
  "",
  "# ── 10. Non-passing AUTO-READ Guardian verdict is refused before submit (never a",
  "#       silent land); an explicit --guardian overrides the same marker ────────────",
  "mk_fixture land-block 11",
  "mkdir -p \"$TMP/$GREL/tpm/runtime/guardian/results\"",
  "REVIEW_SHA=\"$(git -C \"$TMP\" rev-parse 'garelier/main/tpm/workbench/#11/land-block')\"",
  "printf '+++\\n[verdict]\\nresult = '\\''BLOCK'\\''\\nreview_sha = '\\''%s'\\''\\n+++\\n' \"$REVIEW_SHA\" > \"$TMP/$GREL/tpm/runtime/guardian/results/land-block-guardian.md\"",
  "set +e",
  "ERR=\"$(bun \"$ML\" --project \"$DT\" --target-root \"$DT\" --pm-id tpm --id 11 \\",
  "  --quality-gate 'true' --no-pull 2>&1 1>/dev/null)\"",
  "RC=$?",
  "set -e",
  "[ \"$RC\" -eq 2 ] || fail \"auto-read BLOCK exit was $RC (expected 2 — must not land on a BLOCK). out=$ERR\"",
  "echo \"$ERR\" | grep -qF 'auto-read Guardian verdict is BLOCK' || fail \"auto-read BLOCK case lacks the refusal message: $ERR\"",
  "cleanup_fixture",
  "",
  "# ── W-027 verdict auto-read path/diagnostic cases ───────────────────────────────",
  "",
  "# ── 13. Relative --project ('.') auto-reads the verdict marker ──────────────────",
  "# The marker path is built from --project; with a RELATIVE --project (the PM's",
  "# `--project .`) read_marker_verdict used to cd into the parser dir and read the",
  "# relative path from the WRONG cwd → silent ENOENT → a fail-closed \"Guardian",
  "# verdict required\" misfire (2026-07-07, three consecutive land failures). Run",
  "# from INSIDE the project with --project . and prove the Guardian PASS is auto-read",
  "# and the merge still lands end-to-end.",
  "mk_fixture land-relauto 14",
  "mkdir -p \"$TMP/$GREL/tpm/runtime/guardian/results\"",
  "REVIEW_SHA=\"$(git -C \"$TMP\" rev-parse 'garelier/main/tpm/workbench/#14/land-relauto')\"",
  "printf '+++\\n[verdict]\\nresult = '\\''PASS'\\''\\nreview_sha = '\\''%s'\\''\\n+++\\n' \"$REVIEW_SHA\" > \"$TMP/$GREL/tpm/runtime/guardian/results/land-relauto-guardian.md\"",
  "ERRF=\"$(mktemp)\"",
  "set +e",
  "OUT=\"$(cd \"$TMP\" && bun \"$ML\" --project . --target-root \"$DT\" --pm-id tpm \\",
  "  --id 14 --quality-gate 'true' --no-pull --max-wait 90 --poll-interval 2 2>\"$ERRF\")\"",
  "RC=$?",
  "set -e",
  "grep -qF \"auto-read Guardian verdict 'PASS'\" \"$ERRF\" \\",
  "  || fail \"relative --project did NOT auto-read the Guardian verdict (W-027 regression): $(cat \"$ERRF\")\"",
  "if grep -qF 'MALFORMED' \"$ERRF\"; then fail \"relative --project WRONGLY flagged the present marker malformed: $(cat \"$ERRF\")\"; fi",
  "[ \"$RC\" -eq 0 ] || fail \"relative --project auto-read exit was $RC (expected 0). summary=$OUT stderr=$(cat \"$ERRF\")\"",
  "echo \"$OUT\" | grep -q '\"status\":\"success\"' || fail \"relative --project case lacks status=success: $OUT\"",
  "git -C \"$TMP\" cat-file -e garelier/main/tpm/studio:land-relauto.txt 2>/dev/null \\",
  "  || fail \"relative --project case did not land the merge onto studio\"",
  "rm -f \"$ERRF\"",
  "cleanup_fixture",
  "",
  "# ── 14. A present-but-malformed marker reports MALFORMED, distinct from absent ───",
  "# A gate role that wrote a PROSE verdict instead of a bare token (the re-failure",
  "# this fix targets): the marker EXISTS but extractVerdict captures no canonical",
  "# token, so the land is refused fail-closed — AND the reason is now visible on",
  "# stderr as \"malformed\", not conflated with an absent marker.",
  "mk_fixture land-malformed 15",
  "mkdir -p \"$TMP/$GREL/tpm/runtime/guardian/results\"",
  "REVIEW_SHA=\"$(git -C \"$TMP\" rev-parse 'garelier/main/tpm/workbench/#15/land-malformed')\"",
  "printf '+++\\n[verdict]\\nresult = '\\''PASSED'\\''\\nreview_sha = '\\''%s'\\''\\n+++\\n\\nGuardian verdict: PASS — no blockers found.\\n' \"$REVIEW_SHA\" \\",
  "  > \"$TMP/$GREL/tpm/runtime/guardian/results/land-malformed-guardian.md\"",
  "set +e",
  "ERR=\"$(cd \"$TMP\" && bun \"$ML\" --project . --target-root \"$DT\" --pm-id tpm \\",
  "  --id 15 --quality-gate 'true' --no-pull 2>&1 1>/dev/null)\"",
  "RC=$?",
  "set -e",
  "[ \"$RC\" -eq 2 ] || fail \"malformed-marker exit was $RC (expected 2 — no valid verdict, fail-closed). out=$ERR\"",
  "echo \"$ERR\" | grep -qF 'MALFORMED' || fail \"malformed-marker case did not report the marker as malformed: $ERR\"",
  "echo \"$ERR\" | grep -qF 'Guardian verdict required' || fail \"malformed-marker case lacks the pre-validation refusal: $ERR\"",
  "cleanup_fixture",
  "",
  "# ── W-024: merge-gate heavy_compile lock skip on a data-only gate ───────────────",
  "",
  "# ── 11. A data-only merge SKIPS the heavy-compile lock ──────────────────────────",
  "# The docs-only diff classifies gate_mode=data_only, so the gate runs the cheap",
  "# data_only_commands and must NOT acquire the heavy_compile lock (the 2026-07-06",
  "# 90-min stall was a docs-only gate queued behind that lock). Proof: the FAILING",
  "# full quality-gate ('false') would fail the merge if it ran, but the merge LANDS",
  "# because the data_only_commands ('true') ran instead; and the lock dir is never",
  "# created, so the acquire was skipped.",
  "FIXTURE_GATE_COMMAND=false mk_fixture_lock land-dataonly 12 \"docs/guide.md\"",
  "set +e",
  "OUT=\"$(bun \"$ML\" --project \"$DT\" --target-root \"$DT\" --pm-id tpm \\",
  "  --branch \"garelier/main/tpm/workbench/#12/land-dataonly\" --guardian PASS \\",
  "  --quality-gate 'false' --no-pull --max-wait 90 --poll-interval 2 2>/dev/null)\"",
  "RC=$?",
  "set -e",
  "[ \"$RC\" -eq 0 ] || fail \"data-only case exit was $RC (expected 0 — data_only_commands run, not the failing full gate). summary=$OUT\"",
  "echo \"$OUT\" | grep -q '\"status\":\"success\"' || fail \"data-only summary lacks status=success: $OUT\"",
  "[ ! -e \"$TMP/$HEAVY_LOCK_REL\" ] || fail \"data-only gate created the heavy_compile lock dir — the acquire was NOT skipped (W-024)\"",
  "cleanup_fixture",
  "",
  "# ── 12. A full (non-data-only) merge ENGAGES the lock (contrast / regression) ────",
  "# A src diff classifies gate_mode=full, so the gate acquires the lock (creating",
  "# the lock dir) around its build. Proves the W-024 skip is conditional on",
  "# data_only mode, not a blanket removal of the lock.",
  "mk_fixture_lock land-fullcompile 13 \"src/code.txt\"",
  "set +e",
  "OUT=\"$(bun \"$ML\" --project \"$DT\" --target-root \"$DT\" --pm-id tpm \\",
  "  --branch \"garelier/main/tpm/workbench/#13/land-fullcompile\" --guardian PASS \\",
  "  --quality-gate 'true' --no-pull --max-wait 90 --poll-interval 2 2>/dev/null)\"",
  "RC=$?",
  "set -e",
  "[ \"$RC\" -eq 0 ] || fail \"full-compile case exit was $RC (expected 0). summary=$OUT\"",
  "echo \"$OUT\" | grep -q '\"status\":\"success\"' || fail \"full-compile summary lacks status=success: $OUT\"",
  "[ -d \"$TMP/$HEAVY_LOCK_REL\" ] || fail \"full merge did NOT engage the heavy_compile lock (lock dir absent) — regression\"",
  "cleanup_fixture",
  "",
  "# ── W-022 batch-land cases ──────────────────────────────────────────────────────",
  "",
  "# ── 15. Batch success via repeated --id — TWO dispatches land in ONE command ─────",
  "# Two dispatches in one repo, landed serially by a single `--id 20 --id 21` call.",
  "# Both merges reach studio, both dispatch containers are cleaned, and the final",
  "# stdout line is the batch summary total=2/landed=2/status=success.",
  "mk_fixture batch-a 20",
  "add_run batch-b 21",
  "set +e",
  "OUT=\"$(bun \"$ML\" --project \"$DT\" --target-root \"$DT\" --pm-id tpm \\",
  "  --id 20 --id 21 --guardian PASS --quality-gate 'true' --no-pull --max-wait 90 --poll-interval 2 2>/dev/null)\"",
  "RC=$?",
  "set -e",
  "[ \"$RC\" -eq 0 ] || fail \"batch success exit was $RC (expected 0). summary=$OUT\"",
  "SUMMARY=\"$(printf '%s\\n' \"$OUT\" | tail -1)\"",
  "echo \"$SUMMARY\" | grep -qF '\"batch\":true' || fail \"batch success: last line is not the batch summary: $SUMMARY\"",
  "echo \"$SUMMARY\" | grep -qF '\"total\":2' || fail \"batch success summary lacks total=2: $SUMMARY\"",
  "echo \"$SUMMARY\" | grep -qF '\"landed\":2' || fail \"batch success summary lacks landed=2: $SUMMARY\"",
  "echo \"$SUMMARY\" | grep -qF '\"status\":\"success\"' || fail \"batch success summary lacks status=success: $SUMMARY\"",
  "git -C \"$TMP\" cat-file -e garelier/main/tpm/studio:batch-a.txt 2>/dev/null || fail \"batch: first item did not land on studio\"",
  "git -C \"$TMP\" cat-file -e garelier/main/tpm/studio:batch-b.txt 2>/dev/null || fail \"batch: second item did not land on studio\"",
  "[ -f \"$TMP/__garelier/tpm/runtime/land_aftercare/retired_dispatches/20.json\" ] || fail \"batch: first dispatch lacks logical-retirement evidence\"",
  "[ -f \"$TMP/__garelier/tpm/runtime/land_aftercare/retired_dispatches/21.json\" ] || fail \"batch: second dispatch lacks logical-retirement evidence\"",
  "cleanup_fixture",
  "",
  "# ── 16. Batch abort via --batch file — first item FAILS, the rest is NOT attempted ─",
  "# A --batch file: item 1 has a failing quality-gate, item 2 a passing one. Item 1's",
  "# merge fails, so the batch ABORTS and item 2 (which WOULD have passed) is never",
  "# attempted: its dispatch + branch survive untouched, nothing of it reaches studio.",
  "# The summary reports status=failed / attempted=1 / landed=0 and names the failed",
  "# item; exit is non-zero. Proves a failure does not drag the remaining items in.",
  "FIXTURE_GATE_COMMAND=false mk_fixture batch-bad 22",
  "add_run batch-skipped 23",
  "cat > \"$TMP/batch.txt\" <<'BATCH'",
  "# item 1 fails (quality-gate false); item 2 would pass but must NOT be attempted",
  "--id 22 --quality-gate false",
  "--id 23 --quality-gate true",
  "BATCH",
  "set +e",
  "OUT=\"$(bun \"$ML\" --project \"$DT\" --target-root \"$DT\" --pm-id tpm \\",
  "  --guardian PASS --no-pull --max-wait 90 --poll-interval 2 --batch \"$TMP/batch.txt\" 2>/dev/null)\"",
  "RC=$?",
  "set -e",
  "[ \"$RC\" -ne 0 ] || fail \"batch abort exit was 0 (expected non-zero). summary=$OUT\"",
  "SUMMARY=\"$(printf '%s\\n' \"$OUT\" | tail -1)\"",
  "echo \"$SUMMARY\" | grep -qF '\"batch\":true' || fail \"batch abort: last line is not the batch summary: $SUMMARY\"",
  "echo \"$SUMMARY\" | grep -qF '\"status\":\"failed\"' || fail \"batch abort summary lacks status=failed: $SUMMARY\"",
  "echo \"$SUMMARY\" | grep -qF '\"attempted\":1' || fail \"batch abort summary lacks attempted=1 (must stop after item 1): $SUMMARY\"",
  "echo \"$SUMMARY\" | grep -qF '\"landed\":0' || fail \"batch abort summary lacks landed=0: $SUMMARY\"",
  "echo \"$SUMMARY\" | grep -qF '\"failed_item\":\"--id 22' || fail \"batch abort summary does not name the failed item: $SUMMARY\"",
  "# The SKIPPED item 2 must be entirely untouched (never attempted).",
  "[ -e \"$TMP/__garelier/tpm/_crew/dispatch23\" ] || fail \"batch abort WRONGLY cleaned the un-attempted item 2 dispatch\"",
  "[ -n \"$(git -C \"$TMP\" branch --list 'garelier/main/tpm/workbench/#23/*')\" ] || fail \"batch abort WRONGLY deleted the un-attempted item 2 branch\"",
  "if git -C \"$TMP\" cat-file -e garelier/main/tpm/studio:batch-skipped.txt 2>/dev/null; then fail \"batch abort WRONGLY landed the un-attempted item 2 onto studio\"; fi",
  "# The FAILED item 1 also survives (single-land failure cleans nothing).",
  "[ -e \"$TMP/__garelier/tpm/_crew/dispatch22\" ] || fail \"batch abort WRONGLY cleaned the failed item 1 dispatch\"",
  "cleanup_fixture",
  "",
  "# ── W-042 round-3 observer: base-tracking merge must not false-positive the",
  "#    seat-trailer preflight ──────────────────────────────────────────────────",
  "",
  "# ── 17. A proxy dispatch base-tracks (mandatory pickup step, dispatch_prepare.ts",
  "#        \"merge the studio tip into your branch\") AFTER an UNRELATED, non-proxy",
  "#        commit has landed on studio from a different dispatch. A naive two-dot",
  "#        `base_sha..HEAD` range would walk that commit in via the merge's second",
  "#        parent and false-positive on ITS missing trailer (it never needed one) —",
  "#        the exact bug lint_commits.ts's `--range` now avoids with `--first-parent`",
  "#        (merge_land.ts's seat-trailer preflight, ce48c4b). The land must SUCCEED:",
  "#        the branch's own commit carries a correct trailer, and the unrelated",
  "#        commit is excluded from the checked range entirely.",
  "TMP=\"$(mktemp -d)\"; DT=\"$(cygpath -m \"$TMP\" 2>/dev/null || printf '%s' \"$TMP\")\"",
  "(",
  "  cd \"$TMP\"",
  "  git init -q -b main; git config user.email ci@ci; git config user.name t",
  "  echo base > base.txt; git add -A; git commit -q -m init",
  "  git branch \"garelier/main/tpm/studio\" main",
  "  BASE_SHA=\"$(git rev-parse HEAD)\"",
  "  git worktree add -q -b \"garelier/main/tpm/workbench/#30/basetrack\" \"wb30\" \"garelier/main/tpm/studio\"",
  "  ( cd wb30 && echo feat > basetrack.txt && git add -A && git commit -q -m \"feat(core): basetrack [#30]",
  "",
  "Garelier: tpm dock#9 W-996",
  "Garelier-Seat: codex ci-model (proxy-commit via dock seat)\" )",
  "  # An UNRELATED commit lands on studio from a DIFFERENT (self-mode) dispatch —",
  "  # correctly carries no Garelier-Seat trailer, since it isn't a proxy commit.",
  "  git checkout -q \"garelier/main/tpm/studio\"",
  "  # `add unrelated.txt` explicitly (not `-A`): the wb30 linked worktree is still",
  "  # a subdirectory of this primary checkout, and `-A` would stage it as a stray",
  "  # embedded-repo gitlink instead of leaving it as the plain worktree it is.",
  "  echo unrelated > unrelated.txt && git add unrelated.txt",
  "  git commit -q -m \"feat(core): unrelated studio work [#31]",
  "",
  "Garelier: tpm worker#31 W-995\"",
  "  # Mandatory base-track: merge studio (now ahead) into the branch worktree.",
  "  ( cd wb30 && git merge -q \"garelier/main/tpm/studio\" --no-edit )",
  "  git worktree remove wb30",
  "  mkdir -p \"__garelier/tpm/_crew/pm\"",
  "  printf '[project]\\nname = \"test\"\\n\\n[branches]\\ntarget = \"main\"\\nintegration = \"garelier/main/tpm/studio\"\\n' \\",
  "    > \"__garelier/tpm/_crew/pm/setup_config.toml\"",
  "  seed_control",
  "  bind_control 30",
  "  git worktree add -q \"__garelier/tpm/_crew/dispatch30/checkout\" \"garelier/main/tpm/workbench/#30/basetrack\"",
  "  printf '# Report - #30 basetrack\\n' > \"__garelier/tpm/_crew/dispatch30/report.md\"",
  "  write_control_binding 30 \"$BASE_SHA\"",
  "  printf '{\"routing\":{\"commit_mode\":\"proxy\",\"model\":\"ci-model\"},\"task\":{\"id\":\"30\",\"branch\":\"garelier/main/tpm/workbench/#30/basetrack\",\"base_sha\":\"%s\",\"touches\":[]},\"control\":{\"schema_version\":3,\"work_id\":\"W-030\",\"session_id\":\"cs_lane_30\"}}\\n' \"$BASE_SHA\" \\",
  "    > \"__garelier/tpm/_crew/dispatch30/context.json\"",
  "  bind_role 30",
  ")",
  "set +e",
  "OUT=\"$(bun \"$ML\" --project \"$DT\" --target-root \"$DT\" --pm-id tpm \\",
  "  --branch \"garelier/main/tpm/workbench/#30/basetrack\" --dispatch-id 30 --guardian PASS \\",
  "  --quality-gate 'true' --no-pull --max-wait 90 --poll-interval 2 2>\"$TMP/err30.log\")\"",
  "RC=$?",
  "set -e",
  "[ \"$RC\" -eq 0 ] || fail \"base-track seat-trailer case exit was $RC (expected 0 — must NOT false-positive on the unrelated studio commit). summary=$OUT stderr=$(cat \"$TMP/err30.log\")\"",
  "echo \"$OUT\" | grep -q '\"status\":\"success\"' || fail \"base-track case lacks status=success: $OUT\"",
  "if grep -qF \"fail --require-seat-trailer\" \"$TMP/err30.log\"; then fail \"base-track case WRONGLY flagged the unrelated studio commit: $(cat \"$TMP/err30.log\")\"; fi",
  "git -C \"$TMP\" cat-file -e garelier/main/tpm/studio:basetrack.txt 2>/dev/null || fail \"base-track case did not land the merge onto studio\"",
  "cleanup_fixture",
  "",
  "# ── W-051: seat handover (target-project incident) — a dispatch's context.json still says",
  "#    commit_mode=proxy from the ORIGINAL codex dispatch, but the role seat",
  "#    handed over to a Claude self-commit seat mid-flight (e.g. codex quota",
  "#    exhaustion), so the LATER commits on the branch carry ordinary self-mode",
  "#    trailers, not the proxy Garelier-Seat line. The strict",
  "#    --require-seat-trailer check would false-positive on every one of them —",
  "#    the exact false ERROR that forced a manual --seat-trailer checked",
  "#    override in #254. The preflight now classifies every commit in range",
  "#    first and auto-switches to self-mode ONLY when the evidence is fully",
  "#    consistent (all self, zero proxy, zero missing) ────────────────────────",
  "",
  "# ── 18. Clean handover: all commits since base_sha carry self trailers only ->",
  "#        auto-switch fires, land SUCCEEDS, and a loud audit line is emitted",
  "#        (never a silent switch).",
  "TMP=\"$(mktemp -d)\"; DT=\"$(cygpath -m \"$TMP\" 2>/dev/null || printf '%s' \"$TMP\")\"",
  "(",
  "  cd \"$TMP\"",
  "  git init -q -b main; git config user.email ci@ci; git config user.name t",
  "  echo base > base.txt; git add -A; git commit -q -m init",
  "  git branch \"garelier/main/tpm/studio\" main",
  "  BASE_SHA=\"$(git rev-parse HEAD)\"",
  "  git worktree add -q -b \"garelier/main/tpm/workbench/#40/handover\" \"wb40\" \"garelier/main/tpm/studio\"",
  "  ( cd wb40 && echo feat1 > handover.txt && git add -A && git commit -q -m \"feat(core): handover step 1 [#40]",
  "",
  "Garelier: tpm worker#40 W-994\" )",
  "  ( cd wb40 && echo feat2 >> handover.txt && git add -A && git commit -q -m \"feat(core): handover step 2 (post-handover) [#40]",
  "",
  "Garelier: tpm worker#40 W-994\" )",
  "  git worktree remove wb40",
  "  mkdir -p \"__garelier/tpm/_crew/pm\"",
  "  printf '[project]\\nname = \"test\"\\n\\n[branches]\\ntarget = \"main\"\\nintegration = \"garelier/main/tpm/studio\"\\n' \\",
  "    > \"__garelier/tpm/_crew/pm/setup_config.toml\"",
  "  seed_control",
  "  bind_control 40",
  "  git worktree add -q \"__garelier/tpm/_crew/dispatch40/checkout\" \"garelier/main/tpm/workbench/#40/handover\"",
  "  printf '# Report - #40 handover\\n' > \"__garelier/tpm/_crew/dispatch40/report.md\"",
  "  write_control_binding 40 \"$BASE_SHA\"",
  "  printf '{\"routing\":{\"commit_mode\":\"proxy\",\"model\":\"ci-model\"},\"task\":{\"id\":\"40\",\"branch\":\"garelier/main/tpm/workbench/#40/handover\",\"base_sha\":\"%s\",\"touches\":[]},\"control\":{\"schema_version\":3,\"work_id\":\"W-040\",\"session_id\":\"cs_lane_40\"}}\\n' \"$BASE_SHA\" \\",
  "    > \"__garelier/tpm/_crew/dispatch40/context.json\"",
  "  bind_role 40",
  ")",
  "set +e",
  "OUT=\"$(bun \"$ML\" --project \"$DT\" --target-root \"$DT\" --pm-id tpm \\",
  "  --branch \"garelier/main/tpm/workbench/#40/handover\" --dispatch-id 40 --guardian PASS \\",
  "  --quality-gate 'true' --no-pull --max-wait 90 --poll-interval 2 2>\"$TMP/err40.log\")\"",
  "RC=$?",
  "set -e",
  "[ \"$RC\" -eq 0 ] || fail \"seat-handover clean case exit was $RC (expected 0 — clean handover must auto-switch). summary=$OUT stderr=$(cat \"$TMP/err40.log\")\"",
  "echo \"$OUT\" | grep -q '\"status\":\"success\"' || fail \"seat-handover clean case lacks status=success: $OUT\"",
  "grep -qF \"seat handover detected\" \"$TMP/err40.log\" || fail \"seat-handover clean case did not emit the loud audit line: $(cat \"$TMP/err40.log\")\"",
  "if grep -qF \"fail --require-seat-trailer\" \"$TMP/err40.log\"; then fail \"seat-handover clean case WRONGLY ran the strict proxy check: $(cat \"$TMP/err40.log\")\"; fi",
  "cleanup_fixture",
  "",
  "# ── 19. Mixed trailers (one proxy-style, one self, since base_sha) must NOT",
  "#        auto-switch — a partial handover is an audit anomaly, not evidence of",
  "#        a clean one, so the strict --require-seat-trailer check still runs",
  "#        and still fails closed (exit non-zero, no land).",
  "TMP=\"$(mktemp -d)\"; DT=\"$(cygpath -m \"$TMP\" 2>/dev/null || printf '%s' \"$TMP\")\"",
  "(",
  "  cd \"$TMP\"",
  "  git init -q -b main; git config user.email ci@ci; git config user.name t",
  "  echo base > base.txt; git add -A; git commit -q -m init",
  "  git branch \"garelier/main/tpm/studio\" main",
  "  BASE_SHA=\"$(git rev-parse HEAD)\"",
  "  git worktree add -q -b \"garelier/main/tpm/workbench/#41/mixed\" \"wb41\" \"garelier/main/tpm/studio\"",
  "  ( cd wb41 && echo feat1 > mixed.txt && git add -A && git commit -q -m \"feat(core): mixed step 1 [#41]",
  "",
  "Garelier: tpm worker#41 W-993",
  "Garelier-Seat: codex ci-model (proxy-commit via dock seat)\" )",
  "  ( cd wb41 && echo feat2 >> mixed.txt && git add -A && git commit -q -m \"feat(core): mixed step 2 (post-handover) [#41]",
  "",
  "Garelier: tpm worker#41 W-993\" )",
  "  git worktree remove wb41",
  "  mkdir -p \"__garelier/tpm/_crew/pm\"",
  "  printf '[project]\\nname = \"test\"\\n\\n[branches]\\ntarget = \"main\"\\nintegration = \"garelier/main/tpm/studio\"\\n' \\",
  "    > \"__garelier/tpm/_crew/pm/setup_config.toml\"",
  "  seed_control",
  "  bind_control 41",
  "  git worktree add -q \"__garelier/tpm/_crew/dispatch41/checkout\" \"garelier/main/tpm/workbench/#41/mixed\"",
  "  printf '# Report - #41 mixed\\n' > \"__garelier/tpm/_crew/dispatch41/report.md\"",
  "  write_control_binding 41 \"$BASE_SHA\"",
  "  printf '{\"routing\":{\"commit_mode\":\"proxy\",\"model\":\"ci-model\"},\"task\":{\"id\":\"41\",\"branch\":\"garelier/main/tpm/workbench/#41/mixed\",\"base_sha\":\"%s\",\"touches\":[]},\"control\":{\"schema_version\":3,\"work_id\":\"W-041\",\"session_id\":\"cs_lane_41\"}}\\n' \"$BASE_SHA\" \\",
  "    > \"__garelier/tpm/_crew/dispatch41/context.json\"",
  "  bind_role 41",
  ")",
  "set +e",
  "OUT=\"$(bun \"$ML\" --project \"$DT\" --target-root \"$DT\" --pm-id tpm \\",
  "  --branch \"garelier/main/tpm/workbench/#41/mixed\" --dispatch-id 41 --guardian PASS \\",
  "  --quality-gate 'true' --no-pull --max-wait 90 --poll-interval 2 2>\"$TMP/err41.log\")\"",
  "RC=$?",
  "set -e",
  "[ \"$RC\" -ne 0 ] || fail \"mixed-trailer case unexpectedly succeeded (should fail closed, no auto-switch on partial evidence): $OUT\"",
  "grep -qF \"fail --require-seat-trailer\" \"$TMP/err41.log\" || fail \"mixed-trailer case did not run the strict proxy check: $(cat \"$TMP/err41.log\")\"",
  "if grep -qF \"seat handover detected\" \"$TMP/err41.log\"; then fail \"mixed-trailer case WRONGLY auto-switched to self-mode on partial evidence: $(cat \"$TMP/err41.log\")\"; fi",
  "cleanup_fixture",
  "",
  "# ── 20. An explicit --seat-trailer override still short-circuits BOTH the",
  "#        auto-switch detection and the strict proxy check, even over the same",
  "#        mixed/inconsistent trailers as case 19 — the operator's manual",
  "#        override remains the trusted final word (unchanged pre-W-051 rule).",
  "TMP=\"$(mktemp -d)\"; DT=\"$(cygpath -m \"$TMP\" 2>/dev/null || printf '%s' \"$TMP\")\"",
  "(",
  "  cd \"$TMP\"",
  "  git init -q -b main; git config user.email ci@ci; git config user.name t",
  "  echo base > base.txt; git add -A; git commit -q -m init",
  "  git branch \"garelier/main/tpm/studio\" main",
  "  BASE_SHA=\"$(git rev-parse HEAD)\"",
  "  git worktree add -q -b \"garelier/main/tpm/workbench/#42/override\" \"wb42\" \"garelier/main/tpm/studio\"",
  "  ( cd wb42 && echo feat1 > override.txt && git add -A && git commit -q -m \"feat(core): override step 1 [#42]",
  "",
  "Garelier: tpm worker#42 W-992",
  "Garelier-Seat: codex ci-model (proxy-commit via dock seat)\" )",
  "  ( cd wb42 && echo feat2 >> override.txt && git add -A && git commit -q -m \"feat(core): override step 2 (post-handover) [#42]",
  "",
  "Garelier: tpm worker#42 W-992\" )",
  "  git worktree remove wb42",
  "  mkdir -p \"__garelier/tpm/_crew/pm\"",
  "  printf '[project]\\nname = \"test\"\\n\\n[branches]\\ntarget = \"main\"\\nintegration = \"garelier/main/tpm/studio\"\\n' \\",
  "    > \"__garelier/tpm/_crew/pm/setup_config.toml\"",
  "  seed_control",
  "  bind_control 42",
  "  git worktree add -q \"__garelier/tpm/_crew/dispatch42/checkout\" \"garelier/main/tpm/workbench/#42/override\"",
  "  printf '# Report - #42 override\\n' > \"__garelier/tpm/_crew/dispatch42/report.md\"",
  "  write_control_binding 42 \"$BASE_SHA\"",
  "  printf '{\"routing\":{\"commit_mode\":\"proxy\",\"model\":\"ci-model\"},\"task\":{\"id\":\"42\",\"branch\":\"garelier/main/tpm/workbench/#42/override\",\"base_sha\":\"%s\",\"touches\":[]},\"control\":{\"schema_version\":3,\"work_id\":\"W-042\",\"session_id\":\"cs_lane_42\"}}\\n' \"$BASE_SHA\" \\",
  "    > \"__garelier/tpm/_crew/dispatch42/context.json\"",
  "  bind_role 42",
  ")",
  "set +e",
  "OUT=\"$(bun \"$ML\" --project \"$DT\" --target-root \"$DT\" --pm-id tpm \\",
  "  --branch \"garelier/main/tpm/workbench/#42/override\" --dispatch-id 42 --guardian PASS \\",
  "  --seat-trailer checked \\",
  "  --quality-gate 'true' --no-pull --max-wait 90 --poll-interval 2 2>\"$TMP/err42.log\")\"",
  "RC=$?",
  "set -e",
  "[ \"$RC\" -eq 0 ] || fail \"explicit --seat-trailer override case exit was $RC (expected 0). summary=$OUT stderr=$(cat \"$TMP/err42.log\")\"",
  "echo \"$OUT\" | grep -q '\"status\":\"success\"' || fail \"explicit override case lacks status=success: $OUT\"",
  "grep -qF \"explicit --seat-trailer checked override\" \"$TMP/err42.log\" || fail \"explicit override case did not log the override message: $(cat \"$TMP/err42.log\")\"",
  "if grep -qF \"seat handover detected\" \"$TMP/err42.log\"; then fail \"explicit override case should not run auto-switch detection at all: $(cat \"$TMP/err42.log\")\"; fi",
  "cleanup_fixture",
  "",
  "# ── W-055: aftercare must survive a missing sibling driver dir ─────────────────",
  "# Root cause (target-project #274 live incident — cleanup + --close-row silently skipped",
  "# after the gate reported success, no error text): `DOCK_MERGE_TS=\"$(cd",
  "# \"$SELF_DIR/../driver/src/dispatch\" 2>/dev/null && pwd -P)/dock_merge.ts\"` had no",
  "# `|| true`. Under `set -e` (armed a few lines earlier), when that cd target does",
  "# not exist, the ENTIRE assignment's exit status is the failed cd's and the whole",
  "# script dies right there — before gate_result_waiter, before cleanup, before",
  "# --close-row — with NO diagnostic (confirmed via `bash -c 'set -e; X=\"$(cd",
  "# /nonexistent 2>/dev/null && pwd -P)\"; echo reached'`: never prints, rc=1).",
  "#",
  "# This is a narrow, stub-driven reproduction (same lighter style as the guard",
  "# cases 3a/3b above, which call scripts directly rather than through a real gate):",
  "# it runs the REAL merge_land.ts with a scratch entry directory and a deliberately",
  "# missing driver dispatch directory, alongside trivial stand-in",
  "# merge_request.ts / gate_result_waiter.ts / dispatch_cleanup.ts that advance",
  "# past sibling resolution — isolating the ONE code path under test (DOCK_MERGE_TS",
  "# resolution + the aftercare crash-warning trap) from the real merge-gate",
  "# machinery already covered end to end by case 1 above.",
  "W55_ROOT=\"$(mktemp -d)\"",
  "TMP=\"$W55_ROOT/proj\"; DT=\"$(cygpath -m \"$TMP\" 2>/dev/null || printf '%s' \"$TMP\")\"",
  "mkdir -p \"$TMP/__garelier/tpm/_crew/pm\"",
  "git -C \"$TMP\" init -q -b main; git -C \"$TMP\" config user.email ci@ci; git -C \"$TMP\" config user.name t",
  "printf 'w55 root\\n' > \"$TMP/root.txt\"; git -C \"$TMP\" add root.txt; git -C \"$TMP\" commit -q -m init",
  "git -C \"$TMP\" branch garelier/main/tpm/studio main",
  "printf '[project]\\nname = \"test\"\\n\\n[branches]\\ntarget = \"main\"\\nintegration = \"garelier/main/tpm/studio\"\\n' > \"$TMP/__garelier/tpm/_crew/pm/setup_config.toml\"",
  "seed_control",
  "bind_control 9",
  "mkdir -p \"$W55_ROOT/entries\" \\",
  "         \"$W55_ROOT/proj/__garelier/tpm/runtime/merge_gate/results\" \\",
  "         \"$W55_ROOT/proj/__garelier/tpm/runtime/merge_gate/locks\" \\",
  "         \"$W55_ROOT/proj/__garelier/tpm/_crew/dispatch9/checkout\"",
  "(",
  "  cd \"$W55_ROOT/proj/__garelier/tpm/_crew/dispatch9/checkout\"",
  "  git init -q; git config user.email ci@ci; git config user.name t",
  "  echo f > f.txt; git add -A; git commit -q -m init",
  "  git checkout -qb \"garelier/main/tpm/workbench/#9/w55case\"",
  ")",
  "W55_BASE=\"$(git -C \"$W55_ROOT/proj/__garelier/tpm/_crew/dispatch9/checkout\" rev-parse HEAD)\"",
  "( cd \"$W55_ROOT/proj\" && write_control_binding 9 \"$W55_BASE\" )",
  "printf '{\"routing\":{\"commit_mode\":\"self\"},\"task\":{\"id\":\"9\",\"branch\":\"garelier/main/tpm/workbench/#9/w55case\",\"base_sha\":\"%s\",\"touches\":[]},\"control\":{\"schema_version\":3,\"work_id\":\"W-009\",\"session_id\":\"cs_lane_9\"}}\\n' \"$W55_BASE\" > \"$W55_ROOT/proj/__garelier/tpm/_crew/dispatch9/context.json\"",
  "printf '# Report - #9 W-055\\n' > \"$W55_ROOT/proj/__garelier/tpm/_crew/dispatch9/report.md\"",
  "( cd \"$W55_ROOT/proj\" && bind_role 9 )",
  "cat > \"$W55_ROOT/entries/merge_request.ts\" <<'STUB'",
  "process.stdout.write('{\"request_id\":\"W55REQ\",\"request_file\":\"x\",\"polled\":false,\"waiter_cmd\":\"y\"}\\n');",
  "STUB",
  "cat > \"$W55_ROOT/entries/gate_result_waiter.ts\" <<'STUB'",
  "process.stdout.write('MERGE_RESULT: success W55REQ deadbee5\\n');",
  "STUB",
  "cat > \"$W55_ROOT/entries/dispatch_cleanup.ts\" <<'STUB'",
  "process.stdout.write('{\"id\":9,\"removed\":\"x\",\"branch\":\"b\",\"branch_deleted\":true,\"cleanup_status\":\"success\",\"merge_status\":\"merged\",\"report_source\":\"none\",\"task_mirror_hint\":\"h\"}\\n');",
  "STUB",
  "[ ! -e \"$W55_ROOT/missing-dispatch\" ] || fail \"W-055 fixture setup: the deliberately missing dispatch dir already exists\"",
  "set +e",
  "# W-111: direct Bun entrypoint with injected sibling and dispatch directories.",
  "# The latter is deliberately absent, preserving the W-055 missing dock_merge",
  "# aftercare condition without relocating the production module.",
  "W55_OUT=\"$(GARELIER_SCRIPT_ENTRY_DIR=\"$W55_ROOT/entries\" GARELIER_DRIVER_DISPATCH_DIR=\"$W55_ROOT/missing-dispatch\" bun \"$ML\" --project \"$W55_ROOT/proj\" --pm-id tpm \\",
  "  --dispatch-id 9 --guardian PASS --no-pull 2>\"$W55_ROOT/err.log\")\"",
  "W55_RC=$?",
  "set -e",
  "[ \"$W55_RC\" -eq 1 ] || fail \"W-055: merge_land exited $W55_RC instead of failing closed when dock_merge.ts is unavailable. stdout=$W55_OUT stderr=$(cat \"$W55_ROOT/err.log\")\"",
  "[ -z \"$W55_OUT\" ] || fail \"W-055: unavailable dock_merge.ts unexpectedly emitted a settlement result: $W55_OUT\"",
  "grep -qF \"dock_merge.ts not found\" \"$W55_ROOT/err.log\" || fail \"W-055: expected the graceful 'dock_merge.ts not found' fallback message, got: $(cat \"$W55_ROOT/err.log\")\"",
  "grep -qF \"NEXT_COMMAND: bun\" \"$W55_ROOT/err.log\" || fail \"W-055: missing dock_merge.ts failure omitted its recovery command: $(cat \"$W55_ROOT/err.log\")\"",
  "# The crash-warning trap must stay SILENT on the normal (non-crashing) path.",
  "grep -qF \"aftercare crashed\" \"$W55_ROOT/err.log\" && fail \"W-055: the aftercare crash-warning trap fired on a CLEAN run: $(cat \"$W55_ROOT/err.log\")\"",
  "rm -rf \"$W55_ROOT\" 2>/dev/null || true",
  "",
  "echo \"merge_land.test: all cases pass (success / failure / W-286 dirty-index+pre-existing-merge refusal, byte/MERGE_HEAD preservation, early-signal non-abort / guard non-interference + negative control / W-017 dispatch-id+verdict auto-read + batch pre-validation + bad-id + auto-BLOCK refusal / W-027 relative-project auto-read + malformed-marker diagnostic / W-024 data-only lock-skip + full-mode lock engage / W-022 batch land 2-item success + abort-on-first-failure / round-3 base-tracking-merge seat-trailer false-positive fix / W-051 seat handover clean-switch + mixed-still-error + explicit-override-wins / W-055 missing sibling resolution fails closed with a recovery command, crash-warning trap silent)\"",
].join("\n") + "\n";

test("merge_land shell parity oracle", () => {
  const result = runShellOracle(shellScript, import.meta.path);
  const stdout = result.stdout?.toString() ?? "";
  const stderr = result.stderr?.toString() ?? "";
  expect(result.exitCode, stdout + stderr).toBe(0);
}, 600_000);
