import { expect, test } from "bun:test";
import { runShellOracle } from "../driver/src/scripts/shell_oracle_test_runner.ts";

// W-111: Bun registers this parity oracle. Its existing shell assertions remain
// verbatim while every Garelier CLI under test is invoked directly with Bun.
const shellScript = [
  "#!/usr/bin/env bash",
  "#",
  "# worker_finalize.test.ts — pins worker_finalize.ts's branches (W-069).",
  "#",
  "# Builds a throwaway git repo with a fake Worker container (STATE.md, report.md,",
  "# context.json, a workbench-branch checkout/ worktree) and asserts:",
  "#   1. gate GREEN + dirty tree   -> commit (verbatim Garelier trailer) + REPORTING",
  "#                                   + register block + one-line stdout register.",
  "#   2. idempotent (clean re-run) -> NO new commit, STATE stays REPORTING, the",
  "#                                   register refreshes (not stacked).",
  "#   3. gate RED                  -> NO commit, STATE stays WORKING, failed command",
  "#                                   + output tail surfaced, dirty change preserved.",
  "#   4. studio safety guard        -> refuses to commit on an integration branch.",
  "#   5. undefined gate            -> refuses (MUST-BLOCK) when no gate command.",
  "#",
  "# Self-contained: run directly (`bun test worker_finalize.test.ts`) or from ci.ts.",
  "# Exits 0 only if every branch holds.",
  "set -uo pipefail",
  "",
  "SELF_DIR=\"$(cd \"$(dirname \"$0\")\" && pwd)\"",
  "FIN=\"$SELF_DIR/../driver/src/scripts/worker_finalize.ts\"",
  "[ -f \"$FIN\" ] || { echo \"worker_finalize.test: cannot find worker_finalize.ts next to me\" >&2; exit 1; }",
  "",
  "TMP=\"$(mktemp -d)\"",
  "trap 'rm -rf \"$TMP\"' EXIT",
  "",
  "fail() { echo \"  FAIL: $*\" >&2; exit 1; }",
  "",
  "(",
  "  set -e",
  "  cd \"$TMP\"",
  "  git init -q -b main .",
  "  git config user.email ci@ci; git config user.name ci",
  "  echo base > file.txt",
  "  git add -A",
  "  git -c commit.gpgsign=false commit -qm init",
  "  BASE_SHA=\"$(git rev-parse --short HEAD)\"",
  "  git branch \"garelier/main/tpm/studio\" main",
  "",
  "  # --- Fake Worker container #7 (dispatch-native scaffold) -------------------",
  "  C=\"$TMP/__garelier/tpm/_dispatch7\"",
  "  mkdir -p \"$C\"",
  "  git worktree add -q \"$C/checkout\" -b \"garelier/main/tpm/workbench/#7/demo\" \"garelier/main/tpm/studio\"",
  "  printf '# Dispatch #7 - worker demo\\n\\n## Status\\n\\nWORKING\\n\\n## Current task\\n\\n#7 demo\\n\\n## Last activity\\n\\n(none)\\n' > \"$C/STATE.md\"",
  "  printf '# Report - #7 demo (worker)\\n\\n## Status\\n\\n(REPORTING | BLOCKED)\\n\\n## Summary\\n\\n(x)\\n' > \"$C/report.md\"",
  "  # Minimal context.json (subset context_pack.ts emits): scoped fast gate =",
  "  # `true`, and a commit_template whose Garelier trailer must land verbatim.",
  "  cat > \"$C/context.json\" <<JSON",
  "{",
  "  \"schema_version\": 1,",
  "  \"kind\": \"dispatch_fact_pack\",",
  "  \"task\": { \"id\": 7, \"role\": \"worker\", \"slug\": \"demo\", \"base_sha\": \"$BASE_SHA\" },",
  "  \"quality_gate\": { \"stack\": \"typescript\", \"full\": [\"echo FULL-WORKSPACE-GATE\"], \"fast\": [\"true\"], \"run_verify\": [] },",
  "  \"commit_template\": \"<type>(<scope>): <summary>  [#7]\\n\\nGarelier: tpm worker#7 #7\"",
  "}",
  "JSON",
  "",
  "  # === 1. GREEN + dirty -> commit + REPORTING ===============================",
  "  echo \"new work\" >> \"$C/checkout/file.txt\"",
  "  OUT=\"$(bun \"$FIN\" --container \"$C\" --subject 'feat(demo): add finalize demo  [#7]')\" \\",
  "    || fail \"green branch exited non-zero\"",
  "  echo \"$OUT\" | grep -q \"REPORTING\" || fail \"stdout register line missing REPORTING: $OUT\"",
  "  echo \"$OUT\" | grep -q \"PM review\" || fail \"stdout register line missing 'PM review 待ち': $OUT\"",
  "  # committed with the VERBATIM trailer from context.json (W-051).",
  "  git -C \"$C/checkout\" log -1 --format='%s' | grep -q 'feat(demo): add finalize demo' \\",
  "    || fail \"commit subject not the --subject line\"",
  "  git -C \"$C/checkout\" log -1 --format='%B' | grep -qx 'Garelier: tpm worker#7 #7' \\",
  "    || fail \"commit is missing the verbatim Garelier trailer\"",
  "  # STATE flipped to REPORTING.",
  "  awk '/^## Status/{getline;getline;print;exit}' \"$C/STATE.md\" | grep -qx 'REPORTING' \\",
  "    || fail \"STATE.md not flipped to REPORTING\"",
  "  # register block written.",
  "  grep -q \"## Finalize register\" \"$C/report.md\" || fail \"no register block in report.md\"",
  "  grep -q 'State: REPORTING — PM review' \"$C/report.md\" || fail \"register block missing PM-review line\"",
  "  SHA_AFTER1=\"$(git -C \"$C/checkout\" rev-parse HEAD)\"",
  "",
  "  # === 2. Idempotent re-run (clean tree) -> STATE flip only ==================",
  "  OUT2=\"$(bun \"$FIN\" --container \"$C\" --subject 'feat(demo): SHOULD NOT BE USED  [#7]')\" \\",
  "    || fail \"idempotent re-run exited non-zero\"",
  "  [ \"$(git -C \"$C/checkout\" rev-parse HEAD)\" = \"$SHA_AFTER1\" ] \\",
  "    || fail \"idempotent re-run created a NEW commit (should not)\"",
  "  echo \"$OUT2\" | grep -q \"already-committed\" || fail \"idempotent register not marked already-committed: $OUT2\"",
  "  [ \"$(grep -c '## Finalize register' \"$C/report.md\")\" -eq 1 ] \\",
  "    || fail \"register block stacked instead of refreshing\"",
  "",
  "  # === 3. Gate RED -> no commit, STATE stays WORKING ========================",
  "  C8=\"$TMP/__garelier/tpm/_dispatch8\"",
  "  mkdir -p \"$C8\"",
  "  git worktree add -q \"$C8/checkout\" -b \"garelier/main/tpm/workbench/#8/red\" \"garelier/main/tpm/studio\"",
  "  printf '# Dispatch #8\\n\\n## Status\\n\\nWORKING\\n\\n## Current task\\n\\n#8 red\\n' > \"$C8/STATE.md\"",
  "  printf '# Report - #8 red\\n\\n## Status\\n\\n(x)\\n' > \"$C8/report.md\"",
  "  printf '{ \"task\": {\"id\":8,\"role\":\"worker\",\"slug\":\"red\"}, \"quality_gate\": {\"fast\":[\"true\"]}, \"commit_template\": \"<t>: <s>  [#8]\\\\n\\\\nGarelier: tpm worker#8 #8\" }\\n' > \"$C8/context.json\"",
  "  echo \"broken\" >> \"$C8/checkout/file.txt\"",
  "  set +e",
  "  OUT3=\"$(bun \"$FIN\" --container \"$C8\" --gate-cmd 'echo compiling...; echo \"error: boom\" >&2; exit 3' --subject 'feat(red): x  [#8]' 2>\"$TMP/err3\")\"",
  "  RC3=$?",
  "  set -e",
  "  [ \"$RC3\" -eq 1 ] || fail \"gate-red exit was $RC3 (expected 1)\"",
  "  [ -z \"$OUT3\" ] || fail \"gate-red printed a stdout register line (should be silent): $OUT3\"",
  "  grep -q \"GATE RED\" \"$TMP/err3\" || fail \"gate-red did not announce GATE RED\"",
  "  grep -q \"failed command: echo compiling\" \"$TMP/err3\" || fail \"gate-red did not show the failed command\"",
  "  grep -q \"error: boom\" \"$TMP/err3\" || fail \"gate-red did not surface the output tail\"",
  "  awk '/^## Status/{getline;getline;print;exit}' \"$C8/STATE.md\" | grep -qx 'WORKING' \\",
  "    || fail \"gate-red flipped STATE off WORKING\"",
  "  [ \"$(git -C \"$C8/checkout\" rev-list --count \"garelier/main/tpm/studio\"..HEAD)\" -eq 0 ] \\",
  "    || fail \"gate-red created a commit\"",
  "  [ -n \"$(git -C \"$C8/checkout\" status --porcelain)\" ] || fail \"gate-red discarded the dirty change\"",
  "",
  "  # === 4. Studio safety guard ==============================================",
  "  SC=\"$TMP/__garelier/tpm/_studioc\"",
  "  mkdir -p \"$SC\"",
  "  git worktree add -q \"$SC/checkout\" \"garelier/main/tpm/studio\"",
  "  set +e",
  "  bun \"$FIN\" --checkout \"$SC/checkout\" --gate-cmd 'true' --subject 'x: y  [#9]' 2>\"$TMP/err4\"",
  "  RC4=$?",
  "  set -e",
  "  [ \"$RC4\" -eq 2 ] || fail \"studio guard exit was $RC4 (expected 2)\"",
  "  grep -q \"integration branch\" \"$TMP/err4\" || fail \"studio guard message missing\"",
  "",
  "  # === 5. Undefined gate -> MUST-BLOCK refuse ==============================",
  "  C9=\"$TMP/__garelier/tpm/_dispatch9\"",
  "  mkdir -p \"$C9\"",
  "  git worktree add -q \"$C9/checkout\" -b \"garelier/main/tpm/workbench/#9/nogate\" \"garelier/main/tpm/studio\"",
  "  printf '# Dispatch #9\\n\\n## Status\\n\\nWORKING\\n' > \"$C9/STATE.md\"",
  "  printf '# Report - #9\\n' > \"$C9/report.md\"",
  "  printf '{ \"task\": {\"id\":9,\"role\":\"worker\",\"slug\":\"nogate\"}, \"quality_gate\": {\"fast\":[],\"full\":[]} }\\n' > \"$C9/context.json\"",
  "  echo x >> \"$C9/checkout/file.txt\"",
  "  set +e",
  "  bun \"$FIN\" --container \"$C9\" --subject 'feat: x  [#9]' 2>\"$TMP/err5\"",
  "  RC5=$?",
  "  set -e",
  "  [ \"$RC5\" -eq 2 ] || fail \"undefined-gate exit was $RC5 (expected 2)\"",
  "  grep -q \"MUST-BLOCK\" \"$TMP/err5\" || fail \"undefined-gate did not cite MUST-BLOCK\"",
  "  [ \"$(git -C \"$C9/checkout\" rev-list --count \"garelier/main/tpm/studio\"..HEAD)\" -eq 0 ] \\",
  "    || fail \"undefined-gate created a commit\"",
  ") || exit 1",
  "",
  "echo \"worker_finalize.test: all branches pass (green-commit / idempotent / gate-red / studio-guard / undefined-gate)\"",
].join("\n") + "\n";

test("worker_finalize shell parity oracle", () => {
  const result = runShellOracle(shellScript, import.meta.path);
  const stdout = result.stdout?.toString() ?? "";
  const stderr = result.stderr?.toString() ?? "";
  expect(result.exitCode, stdout + stderr).toBe(0);
}, 240_000);
